### ISSUE TITLE
[ADD PACKAGE] Eva

### ISSUE THREAD

**Issue by JCKodel** [fluttergems/fluttergems#1]
Eva - https://pub.dev/packages/eva

<img src="https://user-images.githubusercontent.com/379339/222987224-bc08f054-4b88-4082-9a18-80c6037ba490.svg" width="256" />

# EVent-driven Architecture for SOLID Flutter applications

## Features

* Automatic multithreading - Flutter runs on its isolate while the event orchestrator, your domain code and your repositories run on a separate isolate.

* Separation of concerns - Clear separation between UI orchestration (which UI event triggers a domain response), unit testable business logic in domain classes that uses data-driven repositories (local databases, APIs, etc.)

* Built-in dependency injection system - All layers are configurated through simple dependency injection, so you can inject whatever you need in your constructors (for example: use a `SomeClass` whenever someone asks for a `IInterfaceOfSomeClass`)

* Built-in environments - All dependency injection configuration resides in environment classes, so you can have `DevelopmentEnvironment` with one setting and `ProductionEnvironment` with other settings. You can have as many environments as you want.

* No code-generation required - Eva runs with one single line of code: `Eva.useEnvironment(() => const YourEnvironmentClass())`

* No boiler-plate - Aside from dependency injection, there is no framework-related code (aka boiler-plate)

* Unit test friendly - Your domain classes are pure and can be safely tested

* No exceptions thrown - Repositories and events works with a functional stateful response with `empty`, `waiting` (events only), `success(value)` and `failure(exception)` with functional handlers (such as `.map`, `.match`, `.maybeMatch`). No more `try/catch`!

* No nulls - Repositories and events have a special state called `empty` for empty values.

* Automatic loading handling - Events have a `waiting` state, so the UI can show some progress indicators while the domain is busy doing its stuff.

* Event builders - Widgets that respond to events, with automatic `empty` (blank), `waiting` (CircularProgressIndicator), `failure` (FlutterError) and `success` builders, so no `if/switch` is required to decide what to build in response to a domain call. You can even set your own custom widget for each kind of response.

* Event-driven: the UI emits `Command`, which is handled by your code (whenever a TCommand is dispatched, what you wanna do?), call your domain and dispatch events to be listened to by the Flutter UI.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package. This issue will be closed once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @JCKodel 
I have reviewed eva and it will be added to Flutter Gems in a new category along with other Flutter frameworks.
Meanwhile, I am updating the tag to `requires new category` and will update this issue once it is published.

**Comment by ashitaprasad** [comment]
Package eva is now live.
https://fluttergems.dev/packages/eva/
