### ISSUE TITLE
[ADD PACKAGE] quill_html_editor

### ISSUE THREAD

**Issue by the-airbender** [fluttergems/fluttergems#10]
### Package Name:   
quill_html_edtitor 

**Pub URL:**  https://pub.dev/packages/quill_html_editor

**Category/Section :**  Editor & Syntax Highlighter

Quill Html Editor is a HTML rich text editor for Android, iOS, and Web, it is built with the powerful QuillJs library, an open source WYSIWYG editor for the modern web.

**Salient Features** 

- Highly customizable Editor and Toolbar widgets
- Supports copy pasting the RichText from other files or webpages
- Because the Toolbar is completely detached from editor, it can be placed anywhere in the page, as per the requirement
- We can also add custom buttons to the toolbar
- Supports Embedding Images, Videos, Inserting Tables

Thanks!

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @the-airbender. This issue will be closed once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package quill_html_edtitor is now live.
https://fluttergems.dev/packages/quill_html_editor/

**Comment by the-airbender** [comment]
Thank you @ashitaprasad
