### ISSUE TITLE
[ADD PACKAGE] typed_json

### ISSUE THREAD

**Issue by npu3pak** [fluttergems/fluttergems#100]
A package to work with JSON. It's similar to deep_pick but with a more brief syntax and the ability to create JSON as well.

- typed_json
- [It's pub URL ](https://pub.dev/packages/typed_json)
- [XML, JSON & Interchange Formats](https://fluttergems.dev/xml-json-other-interchange-formats/)
- (Reason) It was a library for internal use in two huge projects with a thousand JSONs in total. I think it might come in handy, so I made it public.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @npu3pak.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package typed_json is now live.
https://fluttergems.dev/packages/typed_json/
