### ISSUE TITLE
[ADD PACKAGE] atproto

### ISSUE THREAD

**Issue by myConsciousness** [fluttergems/fluttergems#101]
- Name: **atproto**
- URL: https://pub.dev/packages/atproto
- Category: Social Media
- Why: This is the best-known and only package that makes it easy to use AT Protocol's API from Dart/Flutter. It has been used in the Dart and Flutter apps and is listed on the [official AT Protocol page](https://atproto.com/community/projects#at-protocol-implementations).

**Comment by ashitaprasad** [comment]
Package atproto is now live.
https://fluttergems.dev/packages/atproto/
