### ISSUE TITLE
[ADD PACKAGE] bluesky

### ISSUE THREAD

**Issue by myConsciousness** [fluttergems/fluttergems#102]
- Name: **bluesky**
- URL: https://pub.dev/packages/bluesky
- Category: Social Media
- Why: This is the best-known and only package that makes it easy to use Bluesky Social's API from Dart/Flutter. It has been used in the Dart and Flutter apps and is listed on the [official AT Protocol page](https://atproto.com/community/projects#at-protocol-implementations).

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @myConsciousness.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package bluesky is now live.
https://fluttergems.dev/packages/bluesky/
