### ISSUE TITLE
[ADD PACKAGE] bluesky_text

### ISSUE THREAD

**Issue by myConsciousness** [fluttergems/fluttergems#103]
- Name: **bluesky_text**
- URL: https://pub.dev/packages/bluesky_text
- Category: Social Media
- Why: This package provides the most powerful functionality for parsing text supported by Bluesky Social.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @myConsciousness.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package bluesky_text is now live.
https://fluttergems.dev/packages/bluesky_text/
