### ISSUE TITLE
[ADD PACKAGE] bluesky_cli

### ISSUE THREAD

**Issue by myConsciousness** [fluttergems/fluttergems#104]
- Name: **bluesky_cli**
- URL: https://pub.dev/packages/bluesky_cli
- Category: Social Media
- Why: This is a CLI tool that allows the Bluesky API to be used from the command line. Install with `dart pub global activate bluesky_cli`.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @myConsciousness.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package bluesky_cli is now live.
https://fluttergems.dev/packages/bluesky_cli/
