### ISSUE TITLE
Minimum Value in Circular Slider

### ISSUE THREAD

**Issue by tahir954** [fluttergems/fluttergems#108]
Please add Minimum value property in CircularSlider Widget

`CircularSlider(
                      // like
                      minValue :50,
                      maxValue: 200,
                      radius: 90,
                      color: Colors.transparent,
                      sliderColor: Colors.deepOrange,
                      unSelectedColor: Colors.transparent,

                    ),`

**Comment by ashitaprasad** [comment]
Please reach out to the package maintainer.
