### ISSUE TITLE
[ADD PACKAGE] docutain_sdk

### ISSUE THREAD

**Issue by MarvinFrankenfeld** [fluttergems/fluttergems#109]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name: docutain_sdk
- URL: https://pub.dev/packages/docutain_sdk
- Category: Document Scanner
- Reason: The Docutain SDK is based on the world famous Docutain document management app. It adds high quality document scanning, text recognition, data extraction and PDF creation features to any flutter app.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MarvinFrankenfeld  .
Will close this issue once it is live on the website after review.

**Comment by MarvinFrankenfeld** [comment]
@ashitaprasad , when will the package be reviewed and published?

**Comment by ashitaprasad** [comment]
Package docutain_sdk is now live.
https://fluttergems.dev/packages/docutain_sdk/
