### ISSUE TITLE
Apptex_Chat

### ISSUE THREAD

**Issue by XeroDays** [fluttergems/fluttergems#11]
- Apptex_Chat
- https://pub.dev/packages/apptex_chat
- Chat
- Firebase-based Chat System in just a few lines with pre-build customizable pages.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @XeroDays. This issue will be closed once it is live on the website after review.

**Comment by XeroDays** [comment]
Thank you @ashitaprasad

**Comment by ashitaprasad** [comment]
Package apptex_chat is now live.
https://fluttergems.dev/packages/apptex_chat/
