### ISSUE TITLE
[ADD PACKAGE] string_validator_plus

### ISSUE THREAD

**Issue by nikunjdev22** [fluttergems/fluttergems#110]
**Details of the package(s) you want to add**

Name :- string_validator_plus
URL :- https://pub.dev/packages/string_validator_plus
Category:-  Autoformat, Masking and Validation packages

Simplify data validation in Flutter apps! Validate emails, passwords, and more. Intuitive interface, accurate validation. Download now!

you can find documentation here [string_validator_plus](https://pub.dev/documentation/string_validator_plus/latest).

**Why Choose string_validator_plus?**
Comprehensive: Covering a wide range of validation types, string_validator_plus serves as an all-in-one solution for your validation needs, reducing the need for multiple packages.

Intuitive Interface: Designed with developers in mind, it offers an easy-to-use interface for seamless integration into your Flutter projects.

Error Reduction: Say goodbye to manual validation errors, as string_validator_plus automates the process with reliability, improving data accuracy.

Regular Updates: We are committed to providing regular updates and improvements to ensure the package stays up-to-date with the latest Flutter trends and best practices.

There are many string functions, the extension is still listed above the description, and all introductions are not written, so please check everything after installing the package.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @nikunjdev22 .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package string_validator_plus is now live.
https://fluttergems.dev/packages/string_validator_plus/
