### ISSUE TITLE
[ADD PACKAGE] flutter_chat_page_design

### ISSUE THREAD

**Issue by harshil023** [fluttergems/fluttergems#112]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package : flutter_chat_page_design
- It's pub URL : https://pub.dev/packages/flutter_chat_page_design
- The category/section where it should be added : Chat
- (Reason) Why is it best suited for this category : It is custom page ui for chat page.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @harshil023 .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package flutter_chat_page_design is now live.
https://fluttergems.dev/packages/flutter_chat_page_design/
