### ISSUE TITLE
[ADD PACKAGE] flutter_flow_chart

### ISSUE THREAD

**Issue by alnitak** [fluttergems/fluttergems#114]
**Draw a flow chart diagram with different kind of customizable elements. Dashboards can be saved for later use.**

- flutter_flow_chart
- [It's pub URL ](https://pub.dev/packages/flutter_flow_chart)
- Shapes & Path
- I am not sure it's the right  category

**Comment by ashitaprasad** [comment]
Hi @alnitak,
This package is already added - https://fluttergems.dev/packages/flutter_flow_chart/

**Comment by alnitak** [comment]
@ashitaprasad  sorry! Same as yoda package :)
