### ISSUE TITLE
[ADD PACKAGE] flutter_opengl

### ISSUE THREAD

**Issue by alnitak** [fluttergems/fluttergems#115]
**Flutter plugin to bind a Texture widget  to an OpenGL ES native context. Many ShaderToy shaders can be used**

- flutter_opengl
- [It's pub URL ](https://pub.dev/packages/flutter_opengl)
- Background Effects, Gradients & Shaders
- This plugin doesn't use Flutter shaders, but a native binding to OpenGL. So it can use native vertex and fragment shaders that doesn't need to be rewritten by SPIRV and its limitations using ES 1.0.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @alnitak .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package flutter_opengl is now live.
https://fluttergems.dev/packages/flutter_opengl/
