### ISSUE TITLE
[ADD PACKAGE] yoda

### ISSUE THREAD

**Issue by alnitak** [fluttergems/fluttergems#116]
**Flutter widget that let you slice any kind of child widget in a matrix of tiles and animate them with different kind of ways. Currently with Explode, Vortex and Flakes.**

- yoda
- [It's pub URL](https://pub.dev/packages/yoda) 
- Background Effects, Gradients & Shaders
- It's mainly an effect to apply to widgets

**Comment by ashitaprasad** [comment]
Hi @alnitak ,
yoda is already available on Flutter Gems - https://fluttergems.dev/packages/yoda/

**Comment by alnitak** [comment]
@ashitaprasad  ooh sorry I searched but I didn't found it before! Same for flutter_flow_chart.
Thanks for your useful work on this project!
