### ISSUE TITLE
[ADD PACKAGE] flutter_soloud

### ISSUE THREAD

**Issue by alnitak** [fluttergems/fluttergems#117]
**Flutter low level audio plugin using SoLoud library and FFI. It provides player, basic capture from microphone, 3D audio and more.**

- flutter_soloud
- [It's pub URL ](https://pub.dev/packages/flutter_soloud)
- Music & Audio
- It's a low level audio plugin that works on all platforms but the web (working on it)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @alnitak .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package flutter_soloud is now live.
https://fluttergems.dev/packages/flutter_soloud/
