### ISSUE TITLE
[ADD PACKAGE] clean_architecture_scaffold

### ISSUE THREAD

**Issue by AnujPandey007** [fluttergems/fluttergems#122]
- clean_architecture_scaffold 
- https://pub.dev/packages/clean_architecture_scaffold
- developer-tools
- As the package, create folders based on clean architecture.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @AnujPandey007
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package clean_architecture_scaffold is now live.
https://fluttergems.dev/packages/clean_architecture_scaffold/
