### ISSUE TITLE
[ADD PACKAGE] persian_input

### ISSUE THREAD

**Issue by hharddy** [fluttergems/fluttergems#125]
In a project, I needed to create a text field that only accepts numbers. The issue was that users couldn't use Persian/Arabic numbers, and another problem was that the Dart language couldn't convert those numbers to integers. So, I created this package, and I hope it's going to be useful.

- persian_input 
- [It's pub URL ](https://pub.dev/packages/persian_input)
- Category: User Input, Form & Settings

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @hharddy .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package persian_input is now live.
https://fluttergems.dev/packages/persian_input/
