### ISSUE TITLE
[ADD PACKAGE] swipe_to

### ISSUE THREAD

**Issue by Purvik** [fluttergems/fluttergems#129]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- SwipeTo
- [It's pub URL ](https://pub.dev/packages/swipe_to)
- Touch and Gesture
- Package can be used to wrap any widget to enable left and right swipe with function callback to perform any action.

**Comment by ashitaprasad** [comment]
Hi @Purvik  ,
swipe_to is already available on Flutter Gems - https://fluttergems.dev/packages/swipe_to/
