### ISSUE TITLE
[ADD PACKAGE] material_symbols_icons  (Material Symbols Icons for Flutter)

### ISSUE THREAD

**Issue by timmaffett** [fluttergems/fluttergems#13]
Package Name: material_symbols_icons

Material Symbols Icons for Flutter

Package URL:   https://pub.dev/packages/material_symbols_icons
Category:   Icons
Details:
- Complete support for Google's replacement for the Material Design Icons with Material Design Symbols Icons.  The Material Symbols icons use variable fonts to support tweaking a variety of variation options (fill,weight, grade and optical size).  The package provides non opinionated options for including the icons within your code.  The standard flutter `Icons` package (the original Material Design Icons) can directly be replaced with Material Symbols Icons by replacing `Icons.` with `MaterialSymbols.`.  It also includes options for users of the previous material design symbols packages to drop in this package directly. 
- This package includes an automatic code regenerating tool that creates the source files from pulls of latest fonts/font codepoint definition files from the official google repository for Material Design Icons ( https://github.com/google/material-design-icons ).
- This package is a better alternative to the previous packages which attempted to support the Material Symbols icons because they did not directly use the google repository as the source for the icons and were often out of date or had many incorrect and missing icon definitions.  The errors and problems with the existing packages motivated the creation of this package.  The automatic code generation also has the additional benefit of allowing the user to regenerate the package if there were ever new icons released by google and this package had not been updated yet.
- Live flutter web example can be found [here](https://timmaffett.github.io/material_symbols_icons/) and all icon variations options can be customized. [https://timmaffett.github.io/material_symbols_icons/](https://timmaffett.github.io/material_symbols_icons/#/)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @timmaffett. This issue will be closed once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package material_symbols_icons is now live.
https://fluttergems.dev/packages/material_symbols_icons/
