### ISSUE TITLE
[ADD PACKAGE] oidc

### ISSUE THREAD

**Issue by ahmednfwela** [fluttergems/fluttergems#131]
**Details of the package(s) you want to add**

- Name of the package: oidc
- It's pub URL: https://pub.dev/packages/oidc
- The category/section where it should be added: [authentication](https://fluttergems.dev/authentication/)
- Why is it best suited for this category: this implements the openid connect specification.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ahmednfwela.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package oidc is now live.
https://fluttergems.dev/packages/oidc/
