### ISSUE TITLE
[ADD PACKAGE] simple_asset_picker

### ISSUE THREAD

**Issue by leegh519** [fluttergems/fluttergems#133]
- simple_asset_picker
- [It's pub URL ](https://pub.dev/packages/simple_asset_picker)
- Multimedia Picker
- This package is image picker from gallery

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @leegh519 .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package simple_asset_picker is now live 🎉.
https://fluttergems.dev/packages/simple_asset_picker/
