### ISSUE TITLE
[ADD PACKAGE] peg

### ISSUE THREAD

**Issue by mezoni** [fluttergems/fluttergems#134]
**A command line tool for generating top-down parsers from a parsing expression grammars (PEG).**

- peg
- https://pub.dev/packages/peg
- Parsing & Other Text Utilities
- It is a command line tool for generating top-down parsers from a parsing expression grammars (PEG).

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @mezoni .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package peg is now live 🎉.
https://fluttergems.dev/packages/peg/
