### ISSUE TITLE
[ADD PACKAGE] root_jailbreak_sniffer

### ISSUE THREAD

**Issue by romikavinda** [fluttergems/fluttergems#135]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package : root_jailbreak_sniffer
- It's pub URL https://pub.dev/packages/root_jailbreak_sniffer
- The category/section where it should be added (Check fluttergems.dev for the categories) : Cryptography, Security and Permissions
- (Reason) Why is it best suited for this category : Uses the latest root detection mechanism in android including detecting magiskhide and jailbreak on ios using IOSSecuritySuite

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @romikavinda.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package root_jailbreak_sniffer is now live 🎉.
https://fluttergems.dev/packages/root_jailbreak_sniffer/
