### ISSUE TITLE
[ADD PACKAGE] social_media_audio_recorder

### ISSUE THREAD

**Issue by fuadmostafij6** [fluttergems/fluttergems#136]
**A flutter package, thats use for voice recording as like as Messenger and WhatsApp**

- social_media_audio_recorder

https://github.com/fluttergems/fluttergems/assets/75131816/1871bc24-5e18-44d0-88fb-8c28a44bc1b2

- https://pub.dev/packages/social_media_audio_recorder
- Social Media, Chat & Communication, Multimedia, Voice recorder
- Its more customisable according to other

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @fuadmostafij6 .
Will close this issue once it is live on the website after review.

**Comment by fuadmostafij6** [comment]
> Thanks for submitting the package @fuadmostafij6 . Will close this issue once it is live on the website after review.

okey, thank you

**Comment by ashitaprasad** [comment]
Package social_media_audio_recorder is now live 🎉.
https://fluttergems.dev/packages/social_media_audio_recorder/
