### ISSUE TITLE
[ADD PACKAGE] Kalender 

### ISSUE THREAD

**Issue by pieter-scholtz** [fluttergems/fluttergems#137]
- kalender
- https://pub.dev/packages/kalender 
- calendar : )
- Well , its a calendar package that is licenced well , its very customisable , and it allows in place editing of events. I think its much nicer than a lot of the other calendar packages out there. 

just try it for yourself : https://werner-scholtz.github.io/kalender/

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @pieter-scholtz .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package kalender is now live 🎉.
https://fluttergems.dev/packages/kalender/
