### ISSUE TITLE
[ADD PACKAGE] another_flutter_splash_screen

### ISSUE THREAD

**Issue by ToyZ-95** [fluttergems/fluttergems#138]
- Another Flutter Splash Screen
- [another_flutter_splash_screen](https://pub.dev/packages/another_flutter_splash_screen)
- Category : Splashscreen
- (Reason) Why is it best suited for this category
- - Easy and Simple to Integrate
- - Supports deciding next screen dynamically. [Example here](https://pub.dev/packages/another_flutter_splash_screen#dynamic_next_screen) [#](https://pub.dev/packages/another_flutter_splash_screen#supports-deciding-next-screen-dynamically-example-heredynamic_next_screen) 
- - Supports Immersive Mode (Hide Status Bar in Splash Screen). [Example here](https://pub.dev/packages/another_flutter_splash_screen#immersive_mode)
- - Provides various curated demos to start with

**Comment by ashitaprasad** [comment]
Hi @ToyZ-95 ,
another_flutter_splash_screen is already available on Flutter Gems - https://fluttergems.dev/packages/another_flutter_splash_screen/

**Comment by ToyZ-95** [comment]
> Hi @ToyZ-95 ,
> another_flutter_splash_screen is already available on Flutter Gems - https://fluttergems.dev/packages/another_flutter_splash_screen/

Ohh ok thanks.
But it is not showing which repos are using the package.
I can see 140+ public repos are using another_flutter_splah_screen.

Can you please help over?

**Comment by ashitaprasad** [comment]
Only open source Flutter apps (not packages) that use another_flutter_splah_screen are mentioned on the page. In case there is an open source app that uses another_flutter_splah_screen, please go ahead and submit it here -https://github.com/fluttergems/fluttergems#how-to-add-a-new-open-source-flutter-appproject-to-flutter-gems
