### ISSUE TITLE
[ADD PACKAGE] live_text

### ISSUE THREAD

**Issue by ToyZ-95** [fluttergems/fluttergems#139]
- [live_text](https://pub.dev/packages/live_text)
- This should be in one of the following category
-- Text, Icons & Keyboard
-- Architecture & Infrastructure
-- Helpers and Utilities
- Usage
-- Updates TextWidget as soon as its text value changes without redrawing any other widgets.
-- No state management technique needed.
-- Updates text without any hassle.
-- Provides call back with old and new value of your text widget.
-- Reset to initial value whenever you want.
-- Best example is updating timer text on the go. (Example is already available in package readme)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ToyZ-95.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package live_text is now live 🎉.
https://fluttergems.dev/packages/live_text/
