### ISSUE TITLE
[ADD PACKAGE] alert_banner

### ISSUE THREAD

**Issue by mattrltrent** [fluttergems/fluttergems#14]
**Details of the package(s) you want to add**

- alert_banner
- https://pub.dev/packages/alert_banner
- Notification & Toast
- Suited for this category because it allows the user to show a notification.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @mattrltrent. This issue will be closed once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package alert_banner is now live.
https://fluttergems.dev/packages/alert_banner/
