### ISSUE TITLE
[ADD PACKAGE] store_locator

### ISSUE THREAD

**Issue by lucaantonelli** [fluttergems/fluttergems#140]
- Store Locator
- https://pub.dev/packages/store_locator
- Category: Geolocation & Maps
- A custom implementation of google_maps_flutter to show POE based on api request that use algorithms like haversine

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @lucaantonelli.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package store_locator is now live 🎉.
https://fluttergems.dev/packages/store_locator/
