### ISSUE TITLE
[ADD PACKAGE] expire_it

### ISSUE THREAD

**Issue by raysummee** [fluttergems/fluttergems#142]
**Details of the package(s) you want to add**

- Expire it
- https://pub.dev/packages/expire_it
- Cryptography, Security and Permissions
- It allows the developers to build an app where the user can use the app upto specific dates. Hence it allows and disallows `permission` to use the app according to date time/ before expiry date

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @raysummee.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package expire_it is now live 🎉.
https://fluttergems.dev/packages/expire_it/
