### ISSUE TITLE
[ADD PACKAGE] flutter_carousel_intro

### ISSUE THREAD

**Issue by eliezerantonio** [fluttergems/fluttergems#143]
![1008](https://github.com/fluttergems/fluttergems/assets/47981638/b5338be0-a2f0-440d-ab0e-651d370c3873)

- flutter_carousel_intro
- https://pub.dev/packages/flutter_carousel_intro
- Category: Onboarding Carousel
- The FlutterCarouselIntro is an amazing package that makes it easy to build and implement animated onboarding screens in Flutter applications.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @eliezerantonio.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package flutter_carousel_intro is now live 🎉.
https://fluttergems.dev/packages/flutter_carousel_intro/
