### ISSUE TITLE
[ADD PACKAGE] localization_plus

### ISSUE THREAD

**Issue by aydinfatih** [fluttergems/fluttergems#144]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package
  -  localization_plus
- It's pub URL 
    - https://pub.dev/packages/localization_plus
- The category/section where it should be added (Check fluttergems.dev for the categories)
  - Localization, Internationalization and Translation packages
- (Reason) Why is it best suited for this category
  -  Because you can do localization through the package.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @aydinfatih.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package localization_plus is now live 🎉.
https://fluttergems.dev/packages/localization_plus/
