### ISSUE TITLE
[ADD PACKAGE] mouse_follower

### ISSUE THREAD

**Issue by mokaily** [fluttergems/fluttergems#146]
The mouse follower package empowers the user to add almost any widgets or styles behind the cursor itself as a mouse follower.
https://github.com/fluttergems/fluttergems/assets/32467495/ab93803b-8b2e-4f4e-a624-f22ec117888b

- Mouse Follower
- [https://pub.dev/packages/mouse_follower](https://pub.dev/packages/mouse_follower)
- UI Components
- The mouse follower basically enables the user to draw any widget behind the cursor

**Comment by ashitaprasad** [comment]
Package mouse_follower is now live 🎉.
https://fluttergems.dev/packages/mouse_follower/
