### ISSUE TITLE
[ADD PACKAGE] flutter_rocket

### ISSUE THREAD

**Issue by M97Chahboun** [fluttergems/fluttergems#149]
- Flutter Rocket
- https://pub.dev/packages/flutter_rocket
- [Architecture & Infrastructure](https://fluttergems.dev/#) As Flutter Framework
- Because this package is collection of sub-packages for state management, request & singleton object

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @M97Chahboun.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package flutter_rocket is now live 🎉.
https://fluttergems.dev/packages/flutter_rocket/
