### ISSUE TITLE
[ADD PACKAGE] QueryStack

### ISSUE THREAD

**Issue by JCKodel** [fluttergems/fluttergems#15]
**Details of the package(s) you want to add**

- Name of the package: query_stack
- It's pub URL: https://pub.dev/packages/query_stack
- The category/section where it should be added: Architecture & Infrastructure
- (Reason) Why is it best suited for this category: It's a state management that promotes the Clean Architecture and SOLID principles.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @JCKodel. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package query_stack is now live.
https://fluttergems.dev/packages/query_stack/
