### ISSUE TITLE
[ADD PACKAGE] github_snitch

### ISSUE THREAD

**Issue by M97Chahboun** [fluttergems/fluttergems#150]
- Github Snitch
- https://pub.dev/packages/github_snitch
- [Functionality](https://fluttergems.dev/#) As Analytics section
- Because this package for report bugs and proposal of users as GitHub issue

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @M97Chahboun.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package github_snitch is now live 🎉.
https://fluttergems.dev/packages/github_snitch/
