### ISSUE TITLE
[ADD PACKAGE] rocket_timer

### ISSUE THREAD

**Issue by M97Chahboun** [fluttergems/fluttergems#151]
- Rocket Timer
- https://pub.dev/packages/rocket_timer
- [Date, Time and Calendar](https://fluttergems.dev/#) as StopWatch, Timer & Countdown
- Because this package for create timer with all functionalities as (start, pause, stop, restart, switch between normal mode and countdown mode...)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @M97Chahboun.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package rocket_timer is now live 🎉.
https://fluttergems.dev/packages/rocket_timer/
