### ISSUE TITLE
[ADD PACKAGE] profile_photo

### ISSUE THREAD

**Issue by bradv123** [fluttergems/fluttergems#153]
- Name: profile_photo
- [https://pub.dev/packages/profile_photo](https://pub.dev/packages/profile_photo)
- Category: Social Media, Chat & Communication -> Avatar, Profile Picture & Chat Heads
- Reason: Its a package to view profile photos and customize how they are displayed on screen

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @bradv123 .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package profile_photo is now live 🎉.
https://fluttergems.dev/packages/profile_photo/
