### ISSUE TITLE
[ADD PACKAGE] color_hex

### ISSUE THREAD

**Issue by abom-me** [fluttergems/fluttergems#154]
Name : color_hex

https://pub.dev/packages/color_hex

category:  Widget Extension & Color Picker and Utilities
the reason: Flutter package to convert hex String to Color() , and Color() to hex String

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @abom-me.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package color_hex is now live 🎉.
https://fluttergems.dev/packages/color_hex/
