### ISSUE TITLE
[ADD PACKAGE] adoptive_calendar

### ISSUE THREAD

**Issue by gm6534** [fluttergems/fluttergems#155]
**A Flutter Package That will provide to you a Date and Time Picker in IOS 14 Calendar view Style. This is an Adoptive Calendar.**

- Adoptive Calendar
- [Go to Pub](https://pub.dev/packages/adoptive_calendar)
- Calendar
- This is a Package that is highly demanded from the the clients. Here is my little contribution for the flutter community.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @gm6534.
Will close this issue once it is live on the website after review.

**Comment by gm6534** [comment]
Hi @ashitaprasad,

i hope you will be fine. can you please share the status about the publishing of Adoptive Calendar package. because my package is still in under review after a long time.

**Comment by ashitaprasad** [comment]
Hi @gm6534,
This package has been approved and will be shipped in the next release of Flutter Gems very soon.

**Comment by gm6534** [comment]
Thank you so much @ashitaprasad

**Comment by ashitaprasad** [comment]
Hi @gm6534,
adoptive_calendar is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/adoptive_calendar/

**Comment by gm6534** [comment]
Thank You So Much @ashitaprasad
