### ISSUE TITLE
[FEATURE REQUEST] Separate code editors from rich text editors

### ISSUE THREAD

**Issue by alexeyinkin** [fluttergems/fluttergems#162]
**Tell us about the problem you are currently facing**
The page 'Editor Syntax Highlighters' includes not only syntax highlighting, but also just rich editors:
https://fluttergems.dev/editor-syntax-highlighter/

The use of rich editors is much wider, while code editors are niche components. For that reason, rich editors dominate this page with the most popular one having 1290 likes, while the most popular code editor comes 7th with 131 likes. This makes code editors harder to find in this category, while the title of the category implies only code editors.

**Describe the solution/feature you'd like us to add**
Move rich text editors to a separate category.

**Comment by ashitaprasad** [comment]
Hi @alexeyinkin,
Thanks for raising this feature request.
Currently, the editor and syntax highlighter category includes rich text editors, code editors and syntax highlighting packages. The category title includes all types of editors, not just code editors as code editors are a subset of editors. At a later date, when we have more packages in this category, we can definitely revisit this issue and look into splitting it.

**Comment by ashitaprasad** [comment]
This issue is open for upvoting.
In case you are a member of the flutter community and feel that we should have a new category for code editors, please go ahead and upvote (👍) the issue.

**Comment by alexeyinkin** [comment]
I still suggest bypassing the vote. We already have low-populated categories:

- 1 package here: https://fluttergems.dev/odt-doc-docx/
- 3 packages here (2 work with Dart 3): https://fluttergems.dev/latex/
- 3 packages here: https://fluttergems.dev/dual-screen-folding-device-ui/
- 4 packages here: https://fluttergems.dev/clock/
- 4 packages here (3 work with Dart 3): https://fluttergems.dev/status-bar/ 

Why DOC is separate from LaTeX? They could have been grouped to 'Other Rich Text'. The reason they are separate is that people have distinct different needs when going there. Grouping them would make it harder to satisfy each of the two needs.

Same is with editors. People either need to:
- Let the user highlight the text as the user wishes, or
- Automatically highlight whatever the user has.

These needs do not overlap.

Also, we will not get low-populated categories, because the packages fall nicely into:
- 20 rich editors: flutter_quill, super_editor, html_editor_enhanced, appflowy_editor, markdown_editable_textinput, zefyrka, quill_html_editor, flutter_summernote, rich_editor, fleather, custom_text, markdown_toolbar, vsc_quill_delta_to_html, text_editor, simple_markdown_editor, markdown_editor_plus, undo, flutter_quill_extensions, zefyr, html_editor.
- 12 code highlighting packages: code_text_field, code_editor, flutter_code_editor, codemirror, json_editor, flutter_highlighter, highlighter, flutter_highlight, flutter_syntax_view, highlight, rich_code_editor, syntax_highlighter.

I think it's OK to group static highlighters and editable highlighters because they serve the same need to highlight what user has. Someone looking for a static highlighter is well served with an editor by making the controller read-only.

I do not think that a group of 12 coherent packages needs to be voted for because it is well in line with the structure of the catalog.

**Comment by alexeyinkin** [comment]
The fact is, I want this for an official use. I am applying for a green card of extraordinary ability and I am close to the completion of my petition. One of the points there is that my team has made the 2nd most popular code editor in Flutter.

The only way to prove this is this category on FlutterGems. But the officer who reviews the petition is not a programmer and is not competent in splitting editors for programmers and non-programmers.

With the current category, I will have to explain the difference in the petition and trust the officer to agree with it. Also, as the package is not in the top 10, the officer will have to track multiple columns that de-synchronize soon after the top (the problem in #163), it gets really bad if split into print pages. It draws attention from main points. It makes proofs shaky as too many things must be assumed. The officer can reject this criterion on the petition and say that an objective proof is required.

If we had a separate category, then a single screenshot would suffice. Can you help me with this @ashitaprasad? And I really do not see how a new category with 12 packages can hurt.

**Comment by ashitaprasad** [comment]
Sure @alexeyinkin
Thanks for segregating the packages into the two categories.
Also, I  do see some votes on the issue which suggests the community would love to see the same.
I will split the category in the next release of Flutter Gems.
Thanks!

**Comment by alexeyinkin** [comment]
Thank you! When is it scheduled?

There's also `easy_debounce_throttle` package there. I believe it is among editors because its example suggests using it to throttle events on an editor, but in that functionality there is nothing specific to editors. That's why I did not put it into any of the two categories. I believe it should go somewhere in 'Date, Time and Calendar', but not sure which category.

**Comment by ashitaprasad** [comment]
The next release is scheduled for Nov end.
Thanks for pointing out. I will also recategorize easy_debounce_throttle.

**Comment by alexeyinkin** [comment]
That's exactly when I am going to apply for the program. Do you need any help with the release so it goes on time or maybe even sooner?

**Comment by ashitaprasad** [comment]
Thanks for the patience @alexeyinkin 
The new category is now live - https://fluttergems.dev/editor-syntax-highlighter/
Thank you for your feedback and all the work!
Cheers 🎉
