### ISSUE TITLE
[ADD PACKAGE] posthog_flutter

### ISSUE THREAD

**Issue by c0bra** [fluttergems/fluttergems#165]
PostHog is a versatile platform for building better products, offering tools like product analytics, feature flags, and A/B testing. It prioritizes data privacy and provides a rich API, allowing businesses to gather insights and improve their offerings.

- **Name of the package:** posthog_flutter
- **Its pub URL:** https://pub.dev/packages/posthog_flutter
- **The category/section where it should be added:** Analytics & Consumer Insights
- **(Reason) Why is it best suited for this category:** Gathering user analytics is one of the main features of Posthog.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @c0bra 
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @c0bra,
posthog_flutter is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/posthog_flutter/
