### ISSUE TITLE
[ADD PACKAGE] number_to_words_english

### ISSUE THREAD

**Issue by kenguyenduc** [fluttergems/fluttergems#166]
If you're seeking a solution to convert numbers into words (in English) using Flutter/Dart, then number_to_words_english is the perfect package. It's a reliable and efficient package designed to assist you in converting numbers into their English word equivalents.

- **Name of the package:** number_to_words_english
- **Its pub URL:** https://pub.dev/packages/number_to_words_english
- **The category/section where it should be added:** Parsing & Other Text Utilities
- **(Reason) Why is it best suited for this category:** number_to_words_english is a Flutter/Dart package designed to transform numerical values into their corresponding English words.

**Comment by ashitaprasad** [comment]
Hi @kenguyenduc,
number_to_words_english is already available on Flutter Gems - https://fluttergems.dev/packages/number_to_words_english/
