### ISSUE TITLE
[ADD PACKAGE] flutter_stepindicator

### ISSUE THREAD

**Issue by PuzzleTakX** [fluttergems/fluttergems#167]
_Note: To add multiple packages, open a separate issue for each package._

**lutterStepIndicator is a versatile Flutter widget designed for creating step indicators to visualize multi-step processes. It offers extensive customization options and features to enhance the user experience.**

- Name of the package: flutter_stepindicator  
- It's pub URL: https://pub.dev/packages/flutter_stepindicator
- The category/section where it should be added: Stepper
- (Reason) Why is it best suited for this category: FlutterStepIndicator is a versatile Flutter widget designed for creating step indicators to visualize multi-step processes. It offers extensive customization options and features to enhance the user experience.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @PuzzleTakX.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @PuzzleTakX,
flutter_stepindicator is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_stepindicator/
