### ISSUE TITLE
[ADD PACKAGE] auto_mappr

### ISSUE THREAD

**Issue by tenhobi** [fluttergems/fluttergems#17]
Code generation for mapping between different objects with ease.

- auto_mappr
- https://pub.dev/packages/auto_mappr
- Developer Tools
- We tried to find an active feature-rich package allowing us to do object-to-object mappings, but with no luck.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @tenhobi. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package auto_mappr is now live.
https://fluttergems.dev/packages/auto_mappr/
