### ISSUE TITLE
[ADD PACKAGE] navigation_view

### ISSUE THREAD

**Issue by PuzzleTakX** [fluttergems/fluttergems#170]
_Note: To add multiple packages, open a separate issue for each package._

**NavigationView is a Flutter package that provides a navigation component with customizable colors and icons. It allows you to easily create a navigation bar with animated transitions between different pages. by most animation flutter**

- Name of the package: navigation_view
- It's pub URL: https://pub.dev/packages/navigation_view
- The category/section where it should be added: Bottom Navigation Bar
- (Reason) Why is it best suited for this category: this a widget bottom navigation

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @PuzzleTakX.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @PuzzleTakX,
navigation_view is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/navigation_view/
