### ISSUE TITLE
[ADD PACKAGE] appsflyer_sdk

### ISSUE THREAD

**Issue by plxndevops** [fluttergems/fluttergems#172]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package : appsflyer_sdk
- It's pub URL : https://pub.dev/packages/appsflyer_sdk
- The category/section where it should be added : Deep Linking
- (Reason) Why is it best suited for this category :  this is the best alternative for firebase deep linking , as firebase deep linking is going to be depreciated soon

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @plxndevops .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @plxndevops,
appsflyer_sdk is now available on Flutter Gems  under Deep Linking 🎉
https://fluttergems.dev/packages/appsflyer_sdk/
