### ISSUE TITLE
[ADD PACKAGE] coinlib_flutter

### ISSUE THREAD

**Issue by peerchemist** [fluttergems/fluttergems#173]
**Details of the package(s) you want to add**

- Name of the package: coinlib_flutter
- It's pub URL: https://pub.dev/packages/coinlib_flutter
- The category/section where it should be added: web3-crypto-blockchain
- (Reason) Why is it best suited for this category: This a feature-complete flutter library for Peercoin and other Satoshi-based UTXO blockchains.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @peerchemist .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @peerchemist,
coinlib_flutter is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/coinlib_flutter/
