### ISSUE TITLE
[ADD PACKAGE]floating_frosted_bottom_bar package

### ISSUE THREAD

**Issue by hiakintho** [fluttergems/fluttergems#176]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package 
- It's pub URL 
- The category/section where it should be added (Check fluttergems.dev for the categories)
- (Reason) Why is it best suited for this category

**Comment by ashitaprasad** [comment]
floating_frosted_bottom_bar is already available on Flutter Gems - https://fluttergems.dev/packages/floating_frosted_bottom_bar/
