### ISSUE TITLE
[ADD PACKAGE] simcards

### ISSUE THREAD

**Issue by drexhacker** [fluttergems/fluttergems#177]
**Details of the package(s) you want to add**

- simcards
- https://pub.dev/packages/simcards
- The category/section where it should be added: android-ios
- (Reason) Why is it best suited for this category: Simcards Flutter Plugin is a new package for querying available simcards on Android Featuring support for even the latest Android Versions which are not supported by the outdated available packages.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @drexhacker.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @drexhacker,
simcards is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/simcards/
