### ISSUE TITLE
[ADD PACKAGE] flutter_native_contact_picker

### ISSUE THREAD

**Issue by jayeshpansheriya** [fluttergems/fluttergems#179]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package  : flutter_native_contact_picker
- It's pub URL : https://pub.dev/packages/flutter_native_contact_picker
- The category/section where it should be added (Check fluttergems.dev for the categories) : contact-picker
- (Reason) Why is it best suited for this category : 
With this plugin a Flutter app can ask its user to select a contact or contacts from his/her address book. The information associated with the contacts is returned to the app.
This plugin uses the operating system's native UI for selecting contacts and does not require any special permissions from the user.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @jayeshpansheriya.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @jayeshpansheriya,
flutter_native_contact_picker is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_native_contact_picker/
