### ISSUE TITLE
[ADD PACKAGE] dart_amqp_client

### ISSUE THREAD

**Issue by Akhil-James** [fluttergems/fluttergems#180]
Name of the package: dart_amqp_client
It's pub URL: https://pub.dev/packages/dart_amqp_client
The category/section where it should be added: Chat, Live Streaming and Real-time Communication
(Reason) Why is it best suited for this category: Dart package that simplifies the handling of AMQP (Advanced Message Queuing Protocol) connections, channels, and associated callbacks.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Akhil-James.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @Akhil-James,
dart_amqp_client is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/dart_amqp_client/
