### ISSUE TITLE
[ADD PACKAGE] ai_commit

### ISSUE THREAD

**Issue by thitlwincoder** [fluttergems/fluttergems#181]
Dart CLI for generate git commit messages with OpenAI.

- ai_commit
- https://pub.dev/packages/ai_commit
- cli

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @thitlwincoder.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @thitlwincoder,
ai_commit is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/ai_commit/
