### ISSUE TITLE
[ADD PACKAGE] pyramid_lint

### ISSUE THREAD

**Issue by charlescyt** [fluttergems/fluttergems#182]
Hello! Thanks for creating flutter gems.

- pyramid_lint
- https://pub.dev/packages/pyramid_lint
- Linter
- Cos it is a linting tool.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @charlescyt .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @charlescyt,
pyramid_lint is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/pyramid_lint/
