### ISSUE TITLE
[ADD PACKAGE] simple_architecture

### ISSUE THREAD

**Issue by JCKodel** [fluttergems/fluttergems#183]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- simple_architecture
- [It's pub URL ](https://pub.dev/packages/simple_architecture)
- Dependency Injection & State Management
- (Reason) simple_architecture is a mediator, state management and dependency injection package.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @JCKodel .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @JCKodel,
simple_architecture is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/simple_architecture/
