### ISSUE TITLE
[ADD PACKAGE] flutter_3d_controller

### ISSUE THREAD

**Issue by m-r-davari** [fluttergems/fluttergems#189]
**A Flutter package for rendering interactive 3D models in different formats (glb, gltf, fbx, obj) with ability to control animations and camera.**

- flutter_3d_controller
- https://pub.dev/packages/flutter_3d_controller
- [3D](https://fluttergems.dev/3d/) , [Animation & Transition](https://fluttergems.dev/animation-transition/)
- flutter_3d_controller package can render 3d models in Flutter and give you a full control of the 3d models animations and camera.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @m-r-davari.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @m-r-davari,
flutter_3d_controller is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_3d_controller/
