### ISSUE TITLE
[ADD PACKAGE] dropdown_plus_plus

### ISSUE THREAD

**Issue by mdmohsin7** [fluttergems/fluttergems#19]
- dropdown_plus_plus
- https://pub.dev/packages/dropdown_plus_plus
- User Input, Form & Settings (Dropdown)
- Searchable dropdown with many customisations
- Maintained fork of dropdown_plus

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @mdmohsin7. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package dropdown_plus_plus is now live.
https://fluttergems.dev/packages/dropdown_plus_plus/
