### ISSUE TITLE
[ADD PACKAGE] common_utilities

### ISSUE THREAD

**Issue by m-r-davari** [fluttergems/fluttergems#190]
**A Dart language Common Utility package, that makes your code faster,easier and cleaner. contains lots of useful functions for Dart primitive types (support all Flutter platforms)**

- common_utilities
- https://pub.dev/packages/common_utilities
- [Parsing & Other Text Utilities](https://fluttergems.dev/parsing-other-utilities/)
- common_utilities package is equivalent of Common Utils library in Java, by this package there is no more need to write utils functions, just add it to makes your code faster,easier and cleaner

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @m-r-davari.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @m-r-davari,
common_utilities is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/common_utilities/
