### ISSUE TITLE
[ADD PACKAGE] quickcapture

### ISSUE THREAD

**Issue by Amalkarunakaran** [fluttergems/fluttergems#191]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- quickcapture 
- [It's pub URL ](https://pub.dev/packages/quickcapture)
- document-scanner
- Flutter plugin QuickCapture makes it possible to scan documents using mobile devices.
With the simple integration of this plugin, mobile applications can reliably scan documents using the camera on a user's mobile device. High-quality documents are captured with optimised focus control.
It's not "just" a scanning SDK. It's a "document" scanning/capture SDK evolved with Best Quality, Highest Possible Compression, Image Optimisation, of output document in mind.
Control DPI,Layout & Size of output images, PDF & TIFF
Developer-friendly & Easy to integration SDK.
Documents can be compressed,optimised & converted to make them smaller, which speeds up uploads and uses less infrastructure.
Also can build PDF and TIFF output from the captured images or even convert images to PDF and TIFF.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Amalkarunakaran .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @Amalkarunakaran,
quickcapture is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/quickcapture/
