### ISSUE TITLE
[ADD PACKAGE] draggable_menu

### ISSUE THREAD

**Issue by emresoysuren** [fluttergems/fluttergems#192]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- draggable_menu
- https://pub.dev/packages/draggable_menu
- Components/Bottom Panels & Bottomsheets
- It allows you to create customizable draggable menus (sheets).

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @emresoysuren 
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @emresoysuren,
draggable_menu is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/draggable_menu/
