### ISSUE TITLE
[ADD PACKAGE] export_generator 

### ISSUE THREAD

**Issue by ameur24** [fluttergems/fluttergems#195]
**Details of the package(s) you want to add**

- export_generator 
- https://pub.dev/packages/export_generator
- Code Generator and Serialization
- The export_generator package streamlines the task of exporting all files in a directory hierarchy by automating the creation of an export configuration file. Its main function is to recognize and eliminate individual imports, generating a singular configuration file that exports all contents within the specified directory.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ameur24  
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ameur24 
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @ameur24,
export_generator is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/export_generator/
