### ISSUE TITLE
[ADD PACKAGE] flutter_media_downloader

### ISSUE THREAD

**Issue by ParthSheth021299** [fluttergems/fluttergems#196]
This plugin helps user to download medias for example pdf files, image files etc. A plugin for creating and managing download tasks. Supports iOS and Android.

This plugin is using native methods for push notifications for both platforms (Android & iOS). This is easy to use plugin.

- flutter_media_downloader 
- https://pub.dev/packages/flutter_media_downloader 
- Multimedia
- This plugins is useful for the download of the media files.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ParthSheth021299  
Will close this issue once it is live on the website after review.

**Comment by ParthSheth021299** [comment]
Hello Fluttergems/Fluttergems,
I have solved the error now you can check and review it.

**Comment by ashitaprasad** [comment]
Hi @ParthSheth021299,
flutter_media_downloader is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_media_downloader/

**Comment by ParthSheth021299** [comment]
Awesome, thank you so much!
