### ISSUE TITLE
[BUG] git_hooks doesn't belong to the hooks package list

### ISSUE THREAD

**Issue by dhafinrayhan** [fluttergems/fluttergems#197]
**Describe the bug/problem**
The [git_hooks] package should not be included in the [hooks](https://fluttergems.dev/hooks/) section, since that section is described as "a concept introduced in React framework that lets you use state and other React features without writing a class". Git hooks are totally different [concepts](https://git-scm.com/docs/githooks) from React hooks.

**Screenshot/image(s) to help explain the bug/problem (if applicable)**
Description is sufficient.

**Desktop details where you encountered the problem/bug (if applicable):**
Irrelevant.

**Smartphone details where you encountered the problem/bug (if applicable):**
Irrelevant.

  [git_hooks]: https://fluttergems.dev/packages/git_hooks/

**Comment by ashitaprasad** [comment]
Thanks for pointing out @dhafinrayhan, we will re-categorize git_hooks.

**Comment by ashitaprasad** [comment]
Thanks @dhafinrayhan 
The issue has now been fixed.
