### ISSUE TITLE
[ADD PACKAGE] focus_on_it

### ISSUE THREAD

**Issue by luanemanuel** [fluttergems/fluttergems#199]
Focus on It is a Dart library that allows you to get notified when a Flutter widget is focused or unfocused and react to it.

- focus_on_it
- https://pub.dev/packages/focus_on_it
- Widget Extension
- "Focus on It" package can be considered a "widget extension" because it provides additional functionalities related to the management of widget focus in Flutter. It provides an efficient mechanism for handling focus events and allows significant customization in the application's behavior in response to these events.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @luanemanuel 
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @luanemanuel,
focus_on_it is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/focus_on_it/
