### ISSUE TITLE
[ADD PACKAGE] flutter_pannable_rating_bar

### ISSUE THREAD

**Issue by SilentCatD** [fluttergems/fluttergems#2]
[flutter_pannable_rating_bar
](https://pub.dev/packages/flutter_pannable_rating_bar)
- The category/section where it should be added: Feedback
- Rating bar widget should belong in this category.

### PannableRatingBar 
Introducing a new and improved rating bar for Flutter, offering versatility and full customization. Unlike other rating bars, this one allows for any value to be selected, not just full or half ratings when interacted. Tap, drag and hover gestures are seamlessly supported, providing a smooth user experience.

### Features 
- Offers fractional values for rating
- High degree of customization for the rating widgets, which can be of different sizes, shapes, and colors.
- Precise hit testing, as the child widget's render object is utilized to determine the results.
- Allows for filtering gestures with either tapOnly, dragOnly or tapAndDrag options.
- Rating reports on cursor hovering supported.
- Built on Flutter's Wrap widget, offering a variety of supported layouts, including consideration of Wrap properties such as textDirection and verticalDirection when painting the indicators.

- Till now, I believe this is the first rating bar implementation that support fractional interactive rating, with the approach using Render Object

**Comment by ashitaprasad** [comment]
Hi @SilentCatD, Thanks for submitting the package. This issue will be closed once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @SilentCatD 
flutter_pannable_rating_bar is now available on Flutter Gems
Link - https://fluttergems.dev/feedback/
