### ISSUE TITLE
[ADD PACKAGE] flexiflow

### ISSUE THREAD

**Issue by luanemanuel** [fluttergems/fluttergems#200]
Flexiflow is a library that enables the creation of responsive flows in your application, providing adaptable variations for various types of devices and screens.

- Flexiflow
- https://pub.dev/packages/flexiflow
- Responsive UI
- Flexiflow is based on the idea of employing a foundational design as a reference point for creating responsive flows. From this fundamental design, the library enables the generation of adaptable variations for different devices such as mobile phones, tablets, and desktops. Otherwise, Flexiflow can adjusts the size of widgets according to various screen sizes, maintaining a constant proportion to the original design.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @luanemanuel 
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @luanemanuel,
flexiflow is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flexiflow/
