### ISSUE TITLE
[ADD PACKAGE] flutter_material_design_icons

### ISSUE THREAD

**Issue by FaFre** [fluttergems/fluttergems#202]
_Note: To add multiple packages, open a separate issue for each package._

This package provides over 7000+ material icons from the [Material Design Icons](https://materialdesignicons.com/) project.

- flutter_material_design_icons 
- https://pub.dev/packages/flutter_material_design_icons
- Icons

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @FaFre.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @FaFre,
flutter_material_design_icons is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_material_design_icons/
