### ISSUE TITLE
[ADD PACKAGE] connectivity_watcher

### ISSUE THREAD

**Issue by Oauth-Celestial** [fluttergems/fluttergems#203]
The package allow the user to add reactive internet check throught there flutter app with just one wrapper class

- connectivity_watcher
- https://pub.dev/packages/connectivity_watcher
- WiFi and Network packages
-  Effortlessly adapt to changing network conditions with a single wrapper that seamlessly detects online/offline status. 🌐📲

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Oauth-Celestial 
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @Oauth-Celestial,
connectivity_watcher is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/connectivity_watcher/
