### ISSUE TITLE
[ADD PACKAGE] date_util_plus

### ISSUE THREAD

**Issue by Oauth-Celestial** [fluttergems/fluttergems#204]
- date_util_plus 
- https://pub.dev/packages/date_util_plus
-  Date and Time Utilities packages
- Provide date and time formatting with auto detect format feature like never before

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Oauth-Celestial 
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @Oauth-Celestial,
date_util_plus is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/date_util_plus/
