### ISSUE TITLE
[ADD PACKAGE] aub_ai

### ISSUE THREAD

**Issue by BrutalCoding** [fluttergems/fluttergems#205]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- aub_ai
- https://pub.dev/packages/aub_ai
- ChatGPT, LLM & Generative AI
- Because it's open-source, on-device (100% local / 100% offline) and enables all Flutter apps to...
> ...harness the power of cutting-edge language models with AubAI for smooth text generation, elevating the user experience through advanced natural language processing. Effortlessly download and try out any GGUF model from sources such as [HuggingFace](https://huggingface.co/models?library=gguf), bringing top-tier AI functionality into your app with ease.

**Comment by ashitaprasad** [comment]
Hi @BrutalCoding,
aub_ai is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/aub_ai/
