### ISSUE TITLE
[ADD PACKAGE] flutter_upgrade_version

### ISSUE THREAD

**Issue by TrangLeQuynh** [fluttergems/fluttergems#206]
_Note: To add multiple packages, open a separate issue for each package._

**Support to get Package Information(app name, package name, version, build number), get information of version on store(Apple Store) and Support In-app Update (Android).**

- flutter_upgrade_version
- [flutter_upgrade_version](https://pub.dev/packages/flutter_upgrade_version)
- App Update
- Package supports getting basic information of the app(app name, package name, version, build number). But the most important thing I pay attention to is being able to receive information when the application has a new version on the store. For Android, Support In-App Update. For iOS, I get the app information on Apple Store throught the package_name and regionCode. Note: I only support the logic part, Dev need to add UI/UX to suit each APPLICATION.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @TrangLeQuynh 
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @TrangLeQuynh,
flutter_upgrade_version is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_upgrade_version/
