### ISSUE TITLE
[ADD PACKAGE] easy_radio

### ISSUE THREAD

**Issue by FadyFayezYounan** [fluttergems/fluttergems#207]
EasyRadio is a customizable radio button widget for Flutter that offers consistent animation, easy customization of sizes, shape, inner dot shape.

- easy_radio
- https://pub.dev/packages/easy_radio
- Checkbox & Radio Button
- because the package is a custom radio

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @FadyFayezYounan.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @FadyFayezYounan,
easy_radio is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/easy_radio/
