### ISSUE TITLE
[ADD PACKAGE] notice

### ISSUE THREAD

**Issue by LowLevelSubmarine** [fluttergems/fluttergems#209]
**Details of the package(s) you want to add**
An extensible logger with an intuitive tree-like structure. Notice excels in seamless cross-package logging while offering a simple yet robust API for developers.

- Name of the package\
  Notice
- It's pub URL 
  https://pub.dev/packages/notice
- The category/section where it should be added (Check fluttergems.dev for the categories\
  Debugging & Logging
- (Reason) Why is it best suited for this category
  Notice is a logging package

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @LowLevelSubmarine.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @LowLevelSubmarine,
notice is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/notice/
