### ISSUE TITLE
[ADD PACKAGE] expansion_tile_group

### ISSUE THREAD

**Issue by congthanhng** [fluttergems/fluttergems#21]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- expansion_tile_group
- https://pub.dev/packages/expansion_tile_group
- Card and Expansion Tile
- Enhance ExpansionTile widget
Thanks

**Comment by ashitaprasad** [comment]
Hi @congthanhng,
The package is already added on the website in the Card & Expansion Tile Category.
Link for the package - https://fluttergems.dev/packages/expansion_tile_group/

Since it is already added, I am closing this issue.
