### ISSUE TITLE
[ADD PACKAGE] state_extended

### ISSUE THREAD

**Issue by Andrious** [fluttergems/fluttergems#210]
- state_extended
- [It's pub URL ](https://pub.dev/packages/state_extended)
- State Management packages

This package extends the capabilities of Flutter's State class. This fundamental component of Flutter's state management had room for improvement. The capabilities of Flutter's State class now includes a 'State Object Controller' and some 22 'lifecycle events.'

StateX should not be confused with GetX. Both do involve 'controllers' that generally contain the 'business logic' involved in an app. GetX has its GetxController class while StateX has its StateXController class, but the similarities stops there.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Andrious .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @Andrious,
state_extended is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/state_extended/
