### ISSUE TITLE
[ADD PACKAGE] tencent_cloud_chat_sdk

### ISSUE THREAD

**Issue by RoleWong** [fluttergems/fluttergems#211]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- tencent_cloud_chat_sdk
- [It's pub URL ](https://pub.dev/packages/tencent_cloud_chat_sdk)
- Chat
- The most popular Chat SDK in China, and expand it's business worldwide. Includes all chat-based feature. Also [showcase on Flutter official website](https://flutter.dev/showcase).
<img width="2537" alt="image" src="https://github.com/fluttergems/fluttergems/assets/24520036/682da219-6847-49b1-adb0-ec30f9b0e3f2">

Compared with the [third-party package](https://fluttergems.dev/packages/tencent_im_plugin/), this is the official package from Tencent Cloud Chat team.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @RoleWong.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @RoleWong,
tencent_cloud_chat_sdk is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/tencent_cloud_chat_sdk/
