### ISSUE TITLE
[ADD PACKAGE] tencent_cloud_chat_uikit

### ISSUE THREAD

**Issue by RoleWong** [fluttergems/fluttergems#212]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- tencent_cloud_chat_uikit
- https://pub.dev/packages/tencent_cloud_chat_uikit
- Chat
- The most popular Chat SDK in China, and expand it's business worldwide. Includes all chat-based feature and better designed UI components interface works on both Mobile and Desktop. Also [showcase on Flutter official website](https://flutter.dev/showcase).
![image](https://github.com/fluttergems/fluttergems/assets/24520036/f130c6e1-38c9-415f-9f6b-c1427dc3eec3)
Compared with the [third-party package](https://fluttergems.dev/packages/tencent_im_plugin/), this is the official package from Tencent Cloud Chat team.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @RoleWong.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @RoleWong,
tencent_cloud_chat_uikit is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/tencent_cloud_chat_uikit/
