### ISSUE TITLE
[ADD PACKAGE] flutter_pay_upi

### ISSUE THREAD

**Issue by abhishekbardolia** [fluttergems/fluttergems#213]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- [flutter_pay_upi] 
- [It's pub URL](https://pub.dev/packages/flutter_pay_upi) 
- Category/Section: Payment Processing
- flutter_pay_upi simplifies UPI integration for Android and iOS in Flutter, making it a go-to choice for secure payment functionality. Notably, it supports iOS—a feature lacking in many alternatives. Ideal for Payment Processing in Flutter. 

<img src="https://github.com/abhishekbardolia/flutter_pay_upi/assets/21007272/1f444519-6aa1-4b85-b835-05cc1bb61ac4" width="200" />

<img src="https://github.com/abhishekbardolia/flutter_pay_upi/assets/21007272/bc0be994-9c65-46d5-9e67-16e122c6be61" width="200" />

<img src="https://github.com/abhishekbardolia/flutter_pay_upi/assets/21007272/cfc7cbd8-aed3-4526-8e12-102cdf854d6e" width="200" />

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @abhishekbardolia.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @abhishekbardolia,
flutter_pay_upi is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_pay_upi/
