### ISSUE TITLE
[ADD PACKAGE] tailwind_cli

### ISSUE THREAD

**Issue by thedevsbuddy** [fluttergems/fluttergems#217]
- [tailwind_cli]
- [It's pub URL ](https://pub.dev/packages/tailwind_cli)
- Category/Section: [Widget Library and UI Framework](https://fluttergems.dev/widget-library-ui-framework/)
- As this package provides a way to generate & use Tailwind CSS like styles for the Flutter apps this is mainly a UI package.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @thedevsbuddy.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @thedevsbuddy,
tailwind_cli is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/tailwind_cli/
