### ISSUE TITLE
[ADD PACKAGE] state_beacon

### ISSUE THREAD

**Issue by jinyus** [fluttergems/fluttergems#219]
**Details of the package(s) you want to add**

- state_beacon
- https://pub.dev/packages/state_beacon
- Dependency Injection & State Management

This is an implementation of signals from SolidJs that's simpler, faster and more feature rich compared to similar packages.

### Faster:
Rain benchmark: https://github.com/jinyus/rainbench
Context Watch benchmark: https://github.com/s0nerik/context_watch/pull/2#issuecomment-1852277280

### Simpler:

Getting started is as simple as it gets.

##### Create a beacon:
```dart
final name = Beacon.writable("Bob");
```

##### Watch it from a widget:
```dart
@override
  Widget build(BuildContext context) {
    // any update to the beacon will trigger a rebuild.
    final nameText = name.watch(context);
    return Text('Hello $nameText');
  }
```

### More feature-rich:

`state_beacon` has the built in ability to buffer, throttle, undo/redo, filter, debounce updates as well as facilities that makes working with async data more seamless.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @jinyus.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @jinyus,
state_beacon is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/state_beacon/
