### ISSUE TITLE
[ADD PACKAGE] google_maps_directions

### ISSUE THREAD

**Issue by bienvenuelisis** [fluttergems/fluttergems#22]
**Details of the package(s) you want to add**

- google_maps_directions
- [It's pub URL ](https://pub.dev/packages/google_maps_directions)
- Geolocation Utilities
- (Reason) Offer utilities methods that helps Get directions between two points & Calculate distance or duration (corresponding to shortest route distance /duration evaluation) between two points. More geolocations features coming.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @bienvenuelisis. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package google_maps_directions is now live.
https://fluttergems.dev/packages/google_maps_directions/
