### ISSUE TITLE
[ADD PACKAGE] dynamic_tabbar

### ISSUE THREAD

**Issue by alihaider78222** [fluttergems/fluttergems#221]
**Details of the package need to add**

- Name of the package: **dynamic_tabbar**
- It's pub URL: [https://pub.dev/packages/dynamic_tabbar](https://pub.dev/packages/dynamic_tabbar)
- The category/section where it should be added: **Tab**
- (Reason) Why is it best suited for this category: This is an extension of TabBar to add/remove them dynamically after initialization.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @alihaider78222.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @alihaider78222,
dynamic_tabbar is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/dynamic_tabbar/
