### ISSUE TITLE
[ADD PACKAGE] rubber_app_bar

### ISSUE THREAD

**Issue by alwatheq** [fluttergems/fluttergems#222]
Details of the package need to add

Name of the package: rubber_app_bar
It's pub URL: https://pub.dev/packages/rubber_app_bar
The category/section where it should be added: App Bar and Action Bar
(Reason) Why is it best suited for this category: This package provide a unique/animated app bar.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @alwatheq.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @alwatheq,
rubber_app_bar is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/rubber_app_bar/
