### ISSUE TITLE
[ADD PACKAGE] otp_pin_field

### ISSUE THREAD

**Issue by shivbo96** [fluttergems/fluttergems#225]
**Details of the package(s) you want to add**

- otp_pin_field
- [Pub.dev URL ](https://pub.dev/packages/otp_pin_field)
- PIN, OTP & Password Field
- A flutter package which will help you to generate pin code fields with beautiful design and animations. It's a beautiful and highly customizable Flutter widget for entering pin code. Can be useful for OTP or pin code inputs and also has ability to autofill the OTP.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @shivbo96.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @shivbo96,
otp_pin_field is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/otp_pin_field/
