### ISSUE TITLE
[ADD PACKAGE] morphy

### ISSUE THREAD

**Issue by atreeon** [fluttergems/fluttergems#226]
**Details of the package(s) you want to add**

- name: morphy 
- pub url: https://pub.dev/packages/morphy
- category: code-generator-serialization
- reason for category: It's a code generation tool, a bit like Freezed

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @atreeon.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @atreeon ,
morphy is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/morphy
