### ISSUE TITLE
[ADD PACKAGE] smooth_sheets

### ISSUE THREAD

**Issue by fujidaiti** [fluttergems/fluttergems#229]
**Details of the package(s) you want to add**

- Name of the package
  - smooth_sheets
- It's pub URL
  - https://pub.dev/packages/smooth_sheets
- The category/section where it should be added
  - Bottom Panels & Bottomsheets
- (Reason) Why is it best suited for this category
  - Because it provides several bottom sheet widgets.

---

**A brief description of smooth_sheets**

smooth_sheets is a Flutter UI package that provides sheet widgets with smooth motion and great flexibility. 

Here are the key features:
- Supports nested navigation within a sheet with graceful motion animation for page transitions.
- It can be integrated with both of the imperative and declarative Navigator API such as `Navigator.push` or `context.go` from go_router.
- Supports both of the persistent and modal sheets.

And some showcases:

![smoothsheets](https://github.com/fluttergems/fluttergems/assets/68946713/2c96d745-8f37-4f31-9c98-c16f0b570d62)

Thanks.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @fujidaiti.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @fujidaiti,
smooth_sheets is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/smooth_sheets/

**Comment by fujidaiti** [comment]
@ashitaprasad 

Thank you for taking the time to review my library!
