### ISSUE TITLE
[ADD PACKAGE] mit_x

### ISSUE THREAD

**Issue by the-best-is-best** [fluttergems/fluttergems#23]
_Note: To add multiple packages, open a separate issue for each package._

**Open screens/snackbars/dialogs/drawer without context /open and close drawer or end drawer/check form is valid or save it, with MitX. 
this package like GitX but removed State Management and upgrade to support flutter 3 and will support fluent ui and native ui in next release
**

- mit_x
- https://pub.dev/packages/mit_x
- Ecosystem

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @the-best-is-best. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package mit_x is now live.
https://fluttergems.dev/packages/mit_x/
