### ISSUE TITLE
[ADD PACKAGE] whitecodel_auto_link

### ISSUE THREAD

**Issue by whitecodel** [fluttergems/fluttergems#230]
**This script automates the process of building and uploading Flutter APK and IPA files to Diawi.**

- whitecodel_auto_link
- https://pub.dev/packages/whitecodel_auto_link 
- Platform Specific Tools & Utilities CLI or Developer Tools (App packaging & Publishing)
- The script focuses on automating the process of building Flutter APK and IPA files, streamlining the development workflow. This is crucial for efficiency, especially in larger projects or when dealing with frequent updates.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @whitecodel .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @whitecodel,
whitecodel_auto_link is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/whitecodel_auto_link/
