### ISSUE TITLE
[ADD PACKAGE] app_upgrader_flutter 

### ISSUE THREAD

**Issue by Eleganceinfolab** [fluttergems/fluttergems#233]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- app_upgrader_flutter 
- [It's pub URL ](https://pub.dev/packages/app_upgrader_flutter)
- fluttergems.dev
- (Reason) Why is it best suited for this category

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Eleganceinfolab.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @Eleganceinfolab,
app_upgrader_flutter is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/app_upgrader_flutter/
