### ISSUE TITLE
[ADD PACKAGE] compassx

### ISSUE THREAD

**Issue by natsuk4ze** [fluttergems/fluttergems#236]
![compassx](https://github.com/natsuk4ze/compassx/raw/main/assets/logo.png)
- Name of the package: compassx 
- It's pub URL: https://pub.dev/packages/compassx
- The category/section where it should be added: Sensors, Geolocation and Maps, Geolocation Utilities
- Why is it best suited for this category: compassx is a plugin to utilize the device's compass sensor, and a common use case for compasses is maps and navigation (geolocation).

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @natsuk4ze.
Will close this issue once it is live on the website after review.

**Comment by natsuk4ze** [comment]
> Thanks for submitting the package @natsuk4ze.
> 
> Will close this issue once it is live on the website after review.

Thanks😌

**Comment by ashitaprasad** [comment]
Hi @natsuk4ze,
compassx is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/compassx/
