### ISSUE TITLE
[ADD PACKAGE] dogs_core

### ISSUE THREAD

**Issue by helightdev** [fluttergems/fluttergems#239]
**Details of the package(s) you want to add**

Name: dogs_core (Dart Object Graphs)
Pub: https://pub.dev/packages/dogs_core
Categories:
- **Code Generator & Serialization (JSON)**
Reason: Provides dataclass and serialization capabilities
- **File Formats/Json**
Reason: Provides json serialization by default
- **File Formats/Top Flutter XML, YAML and Interchange Formats**
Reason: Has support for cbor, toml, yaml (support packages)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @helightdev.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @helightdev,
dogs_core is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/dogs_core/
