### ISSUE TITLE
[ADD PACKAGE] EventFlux

### ISSUE THREAD

**Issue by Imgkl** [fluttergems/fluttergems#241]
**Details of the package**

- EventFlux
- https://pub.dev/packages/eventflux
- http-client-utilities
- It's allows the users to create and manage SSE effortlessly. Since this is a Http Client to manage SSE, I feel this could be the reason why this can be added to http-client-utilities

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Imgkl .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @Imgkl,
eventflux is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/eventflux/
