### ISSUE TITLE
[ADD PACKAGE] appearance

### ISSUE THREAD

**Issue by alihaider78222** [fluttergems/fluttergems#242]
**Details of the package**

- Name of the package : **appearance**
- It's pub URL : [https://pub.dev/packages/appearance](https://pub.dev/packages/appearance)
- The category/section where it should be added : **Light Mode, Dark Mode and Themes packages**
- (Reason) Why is it best suited for this category: This package is used to implement and persist Light, Dark and System theme mode.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @alihaider78222  .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @alihaider78222,
appearance is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/appearance/
