### ISSUE TITLE
[ADD PACKAGE] simple_update_dialog

### ISSUE THREAD

**Issue by SoSerious194** [fluttergems/fluttergems#248]
Details of the package

- Name of the package: simple_update_dialog
- Pub URL: https://pub.dev/packages/simple_update_dialog
- The category/section where it should be added: App Update

- (Reason) Why is it best suited for this category: This package provides a simple way to implement an update feature to the app. Most packages I tried involved a lot of code and hassle to set-up a basic update dialog. If you just want to show a simple update dialog, then this package will help you do that.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SoSerious194.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @SoSerious194,
simple_update_dialog is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/simple_update_dialog/
