### ISSUE TITLE
Interactive pdf 

### ISSUE THREAD

**Issue by Roko2021** [fluttergems/fluttergems#250]
**Tell us about the problem you are currently facing**
_Your response here_
I want you create code in flutter to my system to make interactive pdf with audio, video,image , hyperlink...

**Describe the solution/feature you'd like us to add**
_Your response here_

**Any other feedback you would like to provide regarding the site**
_Your response here_

**Comment by Roko2021** [comment]
Can you help me

**Comment by ashitaprasad** [comment]
@Roko2021 For help please ask in the Discord channel - https://discord.gg/bBeSdtJ6Ue
Closing this issue.
