### ISSUE TITLE
[ADD PACKAGE] simple_form_validations

### ISSUE THREAD

**Issue by Hozefa04** [fluttergems/fluttergems#251]
Details of the package:

- Name of the package: simple_form_validations
- Pub URL: https://pub.dev/packages/simple_form_validations#simple_form_validations
- The category/section where it should be added: Autoformat, Masking & Validation
- (Reason) Why is it best suited for this category: My package provides over 40 different validators for form (still adding more). It's a simple lightweight package for adding validations to a form without you needing to write complex Regex and validations yourself

**Comment by ashitaprasad** [comment]
Hi @Hozefa04,
simple_form_validations is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/simple_form_validations/
