### ISSUE TITLE
[ADD PACKAGE] notebook_paper

### ISSUE THREAD

**Issue by Dionkaps** [fluttergems/fluttergems#253]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- notebook_paper
- https://pub.dev/packages/notebook_paper
- [UI, Theme & Color]/[Responsive UI]
- (Reason) The reason is simple. I haven't found nowhere a responsive notebook like widget for flutter(and that's why i made it)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Dionkaps.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @Dionkaps,
notebook_paper is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/notebook_paper/
