### ISSUE TITLE
[ADD PACKAGE] image_blur

### ISSUE THREAD

**Issue by SwanFlutter** [fluttergems/fluttergems#255]
**Details of the package(s) you want to add**

- image_blur
- [It's pub URL](https://pub.dev/packages/image_blur) 
- [Multimedia][image]
- With this package, you can download and display images as a blur, as well as a hash blur, which is considered a suitable package for 
displaying images.

![blur](https://github.com/fluttergems/fluttergems/assets/151648897/ba930b96-ef89-4a5c-b243-5a2a9133f5c5)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SwanFlutter.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
image_blur is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/image_blur/
