### ISSUE TITLE
[ADD PACKAGE] zoom_hover_pinch_image

### ISSUE THREAD

**Issue by SwanFlutter** [fluttergems/fluttergems#256]
- zoom_hover_pinch_image
- [It's pub URL](https://pub.dev/packages/zoom_hover_pinch_image) 
- The category/section [Multimedia] be added (image)
- It offers a wide range of zoom functions. Zoom- Zoom Hover- Hover -Mouse-Region-Paich

![zoom1](https://github.com/fluttergems/fluttergems/assets/151648897/7081f6a2-bb7a-4b98-9285-126b48ccf89d)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SwanFlutter.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
zoom_hover_pinch_image is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/zoom_hover_pinch_image/
