### ISSUE TITLE
[ADD PACKAGE] avatar_better

### ISSUE THREAD

**Issue by SwanFlutter** [fluttergems/fluttergems#257]
- avatar_better
- [It's pub URL ](https://pub.dev/packages/avatar_better)
- The category/section [Social Media, Chat & Communication] add (Avatar, Profile Picture & Chat Heads)
- (Features:
✔️ Initial Text: Displaying initial text for avatars or placeholders.
✔️ Random Colors: Generating random colors for various elements.
✔️ Random Linear Gradient: Generating random linear gradient colors.
 ✔️ Avatar Profile: Creating avatars for profiles or user representation.
 ✔️ Border Avatar: create a border around the avatar .
 ✔️ gradient Width Border: Create a gradient color for the borders .
 ✔️ Use ImageAssets .
 ✔️ Use ImageNetwork .

![Capture3](https://github.com/fluttergems/fluttergems/assets/151648897/f5423071-36c4-4bb8-94eb-199547ec5d64)

![Capture2](https://github.com/fluttergems/fluttergems/assets/151648897/0f0e4f14-a038-4ca7-8e54-46656e1f6a57)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SwanFlutter.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
avatar_better is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/avatar_better/
