### ISSUE TITLE
[ADD PACKAGE] brightness_pro

### ISSUE THREAD

**Issue by SwanFlutter** [fluttergems/fluttergems#258]
- brightness_pro 
- [It's pub URL ](https://pub.dev/packages/brightness_pro)
- I could not find a category. But it should be in the screen-brightness section.
- Very easy to use.This package allows you to adjust the screen brightness using drag and slider functionalities. It provides precise control over the screen brightness, allowing you to tailor it to your specific needs and preferences. With this package, you can set the screen brightness to a maximum of 100 units. This capability enables you to finely adjust the screen brightness and make the most of it according to your requirements

![brithness](https://github.com/fluttergems/fluttergems/assets/151648897/60c07360-cd0e-4fed-8f3f-dd08dca72859)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SwanFlutter.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
brightness_pro is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/brightness_pro/
