### ISSUE TITLE
[ADD PACKAGE] date_cupertino_bottom_sheet_picker

### ISSUE THREAD

**Issue by SwanFlutter** [fluttergems/fluttergems#259]
- date_cupertino_bottom_sheet_picker 
- [It's pub URL ](https://pub.dev/packages/date_cupertino_bottom_sheet_picker)
- The category/section [User Input, Form & Settings] add (Date & Time Picker)
- beautiful ui، This is a date package in the form of Cupertino and you can set the age limit of your users

![SheetPicker](https://github.com/fluttergems/fluttergems/assets/151648897/d1c3ee9a-f05b-4f55-8dd2-8721efe5d466)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SwanFlutter.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
date_cupertino_bottom_sheet_picker is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/date_cupertino_bottom_sheet_picker/
