### ISSUE TITLE
[ADD PACKAGE] flutter_cupernino_bottom_sheet

### ISSUE THREAD

**Issue by caseyryan** [fluttergems/fluttergems#26]
**The package allows to easily mimic the cupertino bottomsheet behavior without a long setup. And it can be used from any place in the app. No need for a scaffold or a context. Maybe the most developer-friendly package of this kind**

- flutter_cupernino_bottom_sheet
- https://pub.dev/packages/flutter_cupernino_bottom_sheet
- https://fluttergems.dev/bottom-panels-bottomsheets/
- It exactly fits this category even by name :)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @caseyryan. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package flutter_cupernino_bottom_sheet is now live.
https://fluttergems.dev/packages/flutter_cupernino_bottom_sheet/
