### ISSUE TITLE
[ADD PACKAGE] june

### ISSUE THREAD

**Issue by melodysdreamj** [fluttergems/fluttergems#260]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- june
- https://pub.dev/packages/june
- Dependency Injection & State Management
- (Reason) This is a simple and easy, yet flexible state management library that satisfies 100% of the features needed for app development.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @melodysdreamj.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
june is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/june/
