### ISSUE TITLE
[ADD PACKAGE] mistralai_client_dart

### ISSUE THREAD

**Issue by MarcinGruchala** [fluttergems/fluttergems#262]
- mistralai_client_dart
- [It's pub URL](https://pub.dev/packages/mistralai_client_dart) 
- ChatGPT, AI, ML & Game Development -> ChatGPT, LLM & Generative AI
- It is a client for Mistral AI API which is cloud LLM

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MarcinGruchala.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
mistralai_client_dart is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/mistralai_client_dart/
