### ISSUE TITLE
[ADD PACKAGE] flutter_supabase_chat_core

### ISSUE THREAD

**Issue by rickypid** [fluttergems/fluttergems#265]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package : flutter_supabase_chat_core
- It's pub URL : https://pub.dev/packages/flutter_supabase_chat_core
- The category/section where it should be added (Check fluttergems.dev for the categories): Chat

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @rickypid.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
flutter_supabase_chat_core is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_supabase_chat_core/
