### ISSUE TITLE
[ADD PACKAGE] web_color_picker

### ISSUE THREAD

**Issue by victoreronmosele** [fluttergems/fluttergems#268]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- `web_color_picker`
- https://pub.dev/packages/web_color_picker
- `UI, Theme & Color` > `Color Picker & Utilities`
- This package provides a customizable widget that allows using a web browser's color picker in a Flutter Web app.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @victoreronmosele.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
web_color_picker is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/web_color_picker/
