### ISSUE TITLE
[ADD PACKAGE] flutter_paymob 

### ISSUE THREAD

**Issue by ahmednemr3620** [fluttergems/fluttergems#269]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- flutter_paymob 
- [It's pub URL ](https://pub.dev/packages/flutter_paymob)
- payment
- Ana Package is a new package that facilitates the payment and linking process with Paymob

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ahmednemr3620.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
flutter_paymob is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_paymob/
