### ISSUE TITLE
[ADD PACKAGE] flutter_lite_state

### ISSUE THREAD

**Issue by caseyryan** [fluttergems/fluttergems#27]
**Very simple an easy to use state manager. Does not require a context or lots of boilerplate code to setup. Ideal for small and medium size project. Allows for very fast initial app deployment. Basically requires just a few lines of code to set up**

- flutter_lite_state
- https://github.com/caseyryan/flutter_lite_state
- https://fluttergems.dev/state-management/
- It fits the category because it's meant to manage app states

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @caseyryan. Will close this issue once it is live on the website after review.
