### ISSUE TITLE
[ADD PACKAGE] ad_gridview

### ISSUE THREAD

**Issue by RajNarola29** [fluttergems/fluttergems#271]
_Note: To add multiple packages, open a separate issue for each package._

- ad_gridview
- It's pub URL(https://pub.dev/packages/ad_gridview)
- category [Ads,grid]
- Many developer want to show a Native Ad in between a gridview but it hard to show and manage so i made a package where they can do same thing in easy way

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @RajNarola29.
Will close this issue once it is live on the website after review.

**Comment by darshan773** [comment]
approx how many days it take to review?

**Comment by ashitaprasad** [comment]
ad_gridview is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/ad_gridview/
