### ISSUE TITLE
[ADD PACKAGE] sidebar

### ISSUE THREAD

**Issue by jagatheesan2002** [fluttergems/fluttergems#273]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package 
- It's pub URL 
- The category/section where it should be added (Check fluttergems.dev for the categories)
- (Reason) Why is it best suited for this category

**Comment by ashitaprasad** [comment]
The details are incomplete, so please raise a new issue and fill in all the details.
