### ISSUE TITLE
[ADD PACKAGE] stylish_text

### ISSUE THREAD

**Issue by dv-mahbub** [fluttergems/fluttergems#274]
- stylish_text 
- https://pub.dev/packages/stylish_text
- UI - Text - Animation
- Multiple animated text style 
![All](https://github.com/fluttergems/fluttergems/assets/39749028/dc7b65f8-81cd-48ac-a228-f9f7c8e800a2)

![Typewriter](https://github.com/fluttergems/fluttergems/assets/39749028/0405b2d8-212b-4c1d-920f-f4a91dbfa8a5)
![Linear](https://github.com/fluttergems/fluttergems/assets/39749028/b339411b-43a7-4ccf-88df-2bea1c4883db)
![Bounce](https://github.com/fluttergems/fluttergems/assets/39749028/b934572a-921e-4cb4-95e8-8358dc459ac2)
![Oscillate](https://github.com/fluttergems/fluttergems/assets/39749028/a1637109-bfb3-41c5-ab94-353219f366f7)
![Fade](https://github.com/fluttergems/fluttergems/assets/39749028/5bb32810-b660-4640-9973-a20589a862ea)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @dv-mahbub.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
stylish_text is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/stylish_text/
