### ISSUE TITLE
[ADD PACKAGE] positioned_scroll_observer

### ISSUE THREAD

**Issue by SimonWang9610** [fluttergems/fluttergems#275]
**Details of the package(s) you want to add**

- positioned_scroll_observer
- It's pub URL(https://pub.dev/packages/positioned_scroll_observer)
- category: [Scrollable, ScrollView & Scrollbar]
- Support observing any ScrollView and jumping/animating to a specific index/offset.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SimonWang9610.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
positioned_scroll_observer is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/positioned_scroll_observer/
