### ISSUE TITLE
[ADD PACKAGE] flutter_slidable_panel

### ISSUE THREAD

**Issue by SimonWang9610** [fluttergems/fluttergems#276]
**Details of the package(s) you want to add**

- flutter_slidable_panel
- It's pub URL(https://pub.dev/packages/flutter_slidable_panel)
- category: [Slider], [Touch & Gesture], 
- Listen user's gesture to show the slidable action widgets under the slidable panel.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SimonWang9610.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
flutter_slidable_panel is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_slidable_panel/
