### ISSUE TITLE
[ADD PACKAGE] dropdown_overlay

### ISSUE THREAD

**Issue by SimonWang9610** [fluttergems/fluttergems#277]
**Details of the package(s) you want to add**

- dropdown_overlay
- It's pub URL(https://pub.dev/packages/dropdown_overlay)
- category: [Dropdown], [Menu],[Search Bar, Search APIs & Utilities]
- It supports regular Dropdown features and also supports implementing searchable dropdowns as search bars. Besides, users can also specify how to customize and position the dropdown menu.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SimonWang9610.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
dropdown_overlay is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/dropdown_overlay/
