### ISSUE TITLE
[ADD PACKAGE] lite_ref

### ISSUE THREAD

**Issue by jinyus** [fluttergems/fluttergems#278]
_Note: To add multiple packages, open a separate issue for each package._

Lite Ref is a lightweight dependency injection library for Dart and Flutter.

- Name of the package: lite_ref
- It's pub URL: https://pub.dev/packages/lite_ref
- The category/section where it should be added: [Dependency Injection](https://fluttergems.dev/state-management/)
- (Reason) Why is it best suited for this category: lite_ref is lightweight,fast and safe way to provide your Controllers/Blocs down the widget tree with a simple API. It also autodisposes the instance when all widgets using it has been unmounted.

-   Wrap your app or a subtree with a `LiteRefScope`:

    ```dart
    runApp(
      LiteRefScope(
        child: MyApp(),
      ),
    );
    ```

-   Create a `ScopedRef`.

    ```dart
    final settingsServiceRef = Ref.scoped((ctx) => SettingsService());
    ```

-   Access the instance in the current scope:

    This can be done in a widget by using `settingsServiceRef.of(context)` or `settingsServiceRef(context)`.

    ```dart
    class SettingsPage extends StatelessWidget {
      const SettingsPage({super.key});

      @override
      Widget build(BuildContext context) {
        final settingsService = settingsServiceRef.of(context);
        return Text(settingsService.getThemeMode());
      }
    }
    ```

-   Override it for a subtree:

    You can override the instance for a subtree by using `overrideWith`. This is useful for testing.
    In the example below, all calls to `settingsServiceRef.of(context)` will return `MockSettingsService`.

    ```dart
    LiteRefScope(
        overrides: [
            settingsServiceRef.overrideWith((ctx) => MockSettingsService()),
        ]
        child: MyApp(),
        ),
    ```

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @jinyus.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
lite_ref is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/lite_ref/
