### ISSUE TITLE
[ADD PACKAGE] flutter_instagram_storyboard

### ISSUE THREAD

**Issue by caseyryan** [fluttergems/fluttergems#28]
**A package that allow to build Instagram-like stories**

- flutter_instagram_storyboard
- https://pub.dev/packages/flutter_instagram_storyboard
- I don't know. User Journey maybe?
- I didn't find the exact category it would fit in :)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @caseyryan. It will fall under [Story View](https://fluttergems.dev/story-view/) category. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package flutter_instagram_storyboard is now live.
https://fluttergems.dev/packages/flutter_instagram_storyboard/
