### ISSUE TITLE
[ADD PACKAGE] tweener

### ISSUE THREAD

**Issue by drawcall** [fluttergems/fluttergems#282]
**Details of the package(s) you want to add**

- tweener
- It's pub URL (https://github.com/flutterkit/tweener)
- category: [Animation],
- (Reason) Tweener is a simple and lightweight flutter animation tool. Anyone can easily learn to use it.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @drawcall.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
tweener is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/tweener/
