### ISSUE TITLE
[FEATURE REQUEST] Incorrect categorization of a package

### ISSUE THREAD

**Issue by drawcall** [fluttergems/fluttergems#283]
**Tell us about the problem you are currently facing**

Hello, the zerker library (https://fluttergems.dev/packages/zerker/) is currently categorized as "animation & transition". However, this library is more suitable for the "game development" category. Thank you.

**Comment by ashitaprasad** [comment]
It can be used for both so we will also add it to the Game Development category.

**Comment by ashitaprasad** [comment]
Done.
