### ISSUE TITLE
[ADD PACKAGE] crisp_chat

### ISSUE THREAD

**Issue by alamin-karno** [fluttergems/fluttergems#284]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**
A flutter plugin package for using crisp chat natively on Android & iOS.

<img src="https://github.com/alamin-karno/flutter-crisp-chat/blob/main/example/screenshots/image-1.png?raw=true">

<p align="center">
  <a href="https://pub.dev/packages/crisp_chat"><img alt="pub version" src="https://img.shields.io/pub/v/crisp_chat?color=%2300b0ff&label=crisp_chat&style=flat-square"></a>
  <img alt="last commit" src="https://img.shields.io/github/last-commit/alamin-karno/flutter-crisp-chat?color=%23ffa000&style=flat-square"/>
  <img alt="license" src="https://img.shields.io/github/license/alamin-karno/flutter-crisp-chat?style=flat-square"/>
  <img alt="stars" src="https://img.shields.io/github/stars/alamin-karno/flutter-crisp-chat?style=social"/>
</p>

Chat with website visitors, integrate your favorite tools, and deliver a great customer experience. - Crisp. The `Crisp Chat` is a package that provides a simple way to open chat window using native channel. Connect with Crisp Chat, register a user to chat (or not) and render a chat widget. Tested on Android and iOS. 

## Features

- [x] Null-safety enable
- [x] Easy to use
- [x] Customizable
- [x] User configuration with company and geoLocation
- [x] Supports for iOS & Android

## Installation

First, add `crisp_chat` as a [dependency in your pubspec.yaml file](https://flutter.dev/using-packages/).

To use the Flutter Crisp Chat, simply import the `crisp_chat` package:

Run this on your project terminal:

```yaml
flutter pub add crisp_chat
```

or manually configure pubspec.yml file

```yaml
dependencies:
  flutter:
    sdk: flutter
  crisp_chat: ^2.0.0
```

### iOS

Add two rows to the `ios/Runner/Info.plist`:

* key `Privacy - Camera Usage Description` and a usage description.
* key `Privacy - Photo Library Additions Usage Description` and a usage description.
* key `Privacy - Microphone Usage Description` and a usage description.

If editing `Info.plist` as text, add:

```xml
<key>NSCameraUsageDescription</key>
<string>your usage description here</string>
<key>NSPhotoLibraryAddUsageDescription</key>
<string>your usage description here</string>
<key>NSMicrophoneUsageDescription</key>
<string>your usage description here</string>
```

### Android

Add Internet permission on `AndroidManifest.xml` in your `android/app/src/main/AndroidManifest.xml` file.

```groovy
<uses-permission android:name="android.permission.INTERNET"/>
```

Change the minimum Compile SDK version to 34 (or higher) in your `android/app/build.gradle` file.

```groovy
compileSdkVersion 34
```

Change the minimum Android SDK version to 21 (or higher) in your `android/app/build.gradle` file.

```groovy
minSdkVersion 21
```

## Usage
To open ChatView for crisp, use the `openCrispChat` method of the `FlutterCrispChat` class:

##### First Imported Package:

```dart
import 'package:crisp_chat/crisp_chat.dart';
```

##### Then:

```dart
 final String websiteID = 'YOUR_WEBSITE_KEY';
 late CrispConfig config;

   @override
  void initState() {
    super.initState();
    config = CrispConfig(
      websiteID: websiteID,
    );
  }
```

 ```dart 
 @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Crisp Chat'),
        ),
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              await FlutterCrispChat.openCrispChat(
                config: config,
              );
            },
            child: const Text('Open Crisp Chat'),
          ),
        ),
      ),
    );
  } 
  ```

This is a simple Flutter app that demonstrates how to use the `FlutterCrispChat` plugin to open a chat window using the Crisp chat service. The app has a single button that, when pressed, will launch the chat window.

The main function runs the app, which consists of a single MyApp widget. This widget is stateful and creates an instance of the `FlutterCrispChat` plugin.

The build function creates a MaterialApp with a Scaffold that contains an AppBar and an `ElevatedButton`. The button's onPressed method calls the `openCrispChat` method of the `FlutterCrispChat` plugin with the website ID passed as a parameter.

To use this code, you will need to provide your own Crisp website ID. You can do this by replacing `YOUR_WEBSITE_KEY` with your own website ID. Once you have done this, you can run the app and press the `"Open Crisp Chat"` button to launch the chat window.

### Get your Website ID:
Go to your [Crisp Dashboard](https://app.crisp.chat/), and copy your Website ID:

<img src="https://github.com/alamin-karno/flutter-crisp-chat/blob/main/example/screenshots/image.png?raw=true">

## Screenshot (GIF)

|             Android  (GIF)            |              iOS    (GIF)          |
|:---------------------------------------------------:|:---------------------------------------------------:|
| <img src="https://github.com/alamin-karno/flutter-crisp-chat/blob/main/example/screenshots/crisp_android.gif?raw=true" width = "250"> | <img src="https://github.com/alamin-karno/flutter-crisp-chat/blob/main/example/screenshots/crisp_ios.gif?raw=true" width = "250"> |
|             Android  (Image)            |              iOS    (Image)          |
| <img src="https://github.com/alamin-karno/flutter-crisp-chat/blob/main/example/screenshots/crisp_android.png?raw=true" width = "250"> | <img src="https://github.com/alamin-karno/flutter-crisp-chat/blob/main/example/screenshots/crisp_ios.png?raw=true" width = "250"> |

- Crisp Chat
- https://pub.dev/packages/crisp_chat
- Chat
- This package is mainly used for chatting with customers.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @alamin-karno.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
crisp_chat is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/crisp_chat/
