### ISSUE TITLE
[ADD PACKAGE] node_editor

### ISSUE THREAD

**Issue by alexst07** [fluttergems/fluttergems#287]
**A highly customizable node editor for Flutter**
![midia/nodes.png](https://raw.githubusercontent.com/alexst07/flutter_node_editor/master/midia/nodes.png)

- node_editor
- [It's pub URL](https://pub.dev/packages/node_editor)
- UI, Theme & Color/Widget Library & UI Framework
- Because node editor is a UI Framework to create and connect nodes in the style of unreal blueprints and blender nodes editor.

**Comment by ashitaprasad** [comment]
node_editor is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/node_editor/
