### ISSUE TITLE
[ADD PACKAGE] crcAnimation Package

### ISSUE THREAD

**Issue by RanaSharjeelShji** [fluttergems/fluttergems#293]
_Note: To add multiple packages, open a separate issue for each package._

A Flutter package for implementing animation. Just wrap any widget with it and get animated. 10+ easy to handle animations for every widget

- crcanimation
- [It's pub URL ](https://pub.dev/packages/crcanimation)
- Animation & Transition
- It contain modern animations with easy handling. more over it is extremely light weighted package.

https://github.com/fluttergems/fluttergems/assets/89970169/69703f5f-11df-4ee3-8d82-a287ae3ec0b6

**Comment by ashitaprasad** [comment]
crcanimation is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/crcanimation/
