### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by Mahmoud-Abdelaty** [fluttergems/fluttergems#295]
The problem shadow show on not center item i can't edit it.

![image](https://github.com/fluttergems/fluttergems/assets/126201317/7d516b08-45c1-45a4-8f67-e52a23e632f9)

![image](https://github.com/fluttergems/fluttergems/assets/126201317/f1918242-840c-4deb-9a07-e104a8cf692d)

i need do it i need edit opacity color or change color to another 

![image](https://github.com/fluttergems/fluttergems/assets/126201317/10a20e48-1c60-4ab8-ba2e-3c3535c86d3b)

 i need make it Like it

**Comment by ashitaprasad** [comment]
Please post your doubt in the discord channel - https://discord.gg/bBeSdtJ6Ue
