### ISSUE TITLE
[ADD PACKAGE] refreshed

### ISSUE THREAD

**Issue by Aniketkhote** [fluttergems/fluttergems#296]
- Refreshed
- https://pub.dev/packages?q=refreshed
- Flutter Framework
- It is fork package of getx and it is complete package to handle routing, state and dependency.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Aniketkhote.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
refreshed is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/refreshed/
