### ISSUE TITLE
[ADD PACKAGE] KFX Dependency Injection

### ISSUE THREAD

**Issue by JCKodel** [fluttergems/fluttergems#3]
KFX Dependency Injection
https://pub.dev/packages/kfx_dependency_injection

A simple dependency injection and service locator inspired by .net service provider.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @JCKodel . This issue will be closed once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @JCKodel 
kfx_dependency_injection is now available on Flutter Gems.
Link - https://fluttergems.dev/state-management/
