### ISSUE TITLE
[ADD PACKAGE] flutter_storage_info

### ISSUE THREAD

**Issue by JaberQayad** [fluttergems/fluttergems#302]
**Flutter Storage Info is a handy Flutter plugin designed to retrieve information about device storage. With this plugin, developers can effortlessly obtain details about both internal and external storage space on Android devices. Whether you need to determine available space, total capacity, or used space, this plugin offers a comprehensive suite of methods to facilitate storage management within your Flutter applications.**

- flutter_storage_info
- https://pub.dev/packages/flutter_storage_info
- Flutter Multimedia Utilities packages
- Developers can utilize the package to calculate directory sizes, determine storage types, and assess storage usage values, facilitating effective file handling and organization.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @JaberQayad.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
flutter_storage_info is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_storage_info/
