### ISSUE TITLE
[ADD PACKAGE] gone_board

### ISSUE THREAD

**Issue by ratulhasanruhan** [fluttergems/fluttergems#303]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- gone_board
- [It's pub URL ](https://pub.dev/packages/gone_board)
- Onboarding Carousel
- (Reason) This is a easy and simple animated Onboarding carousel

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ratulhasanruhan.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
gone_board is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/gone_board/

**Comment by ratulhasanruhan** [comment]
Thanks 😊
