### ISSUE TITLE
[ADD PACKAGE] easy_event_bus

### ISSUE THREAD

**Issue by melodysdreamj** [fluttergems/fluttergems#305]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

easy_event_bus
https://pub.dev/packages/easy_event_bus
Dependency Injection & State Management
This is the easiest, simplest, and most intuitive library for using the observer pattern.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @melodysdreamj.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
easy_event_bus is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/easy_event_bus/
