### ISSUE TITLE
[ADD PACKAGE] Casbin

### ISSUE THREAD

**Issue by Eradparvar** [fluttergems/fluttergems#306]
Thank you for a great site! We use it all the time!

**Details of the package(s) you want to add**

- Casbin 
- https://pub.dev/packages/casbin 
- The category/section where it should be added (Check fluttergems.dev for the categories) 
Not sure maybe authorization

**Comment by ashitaprasad** [comment]
Thank you for your kind words 🙂
I have added the package to the review pipeline and will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
casbin is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/casbin/
