### ISSUE TITLE
[ADD PACKAGE] glossy

### ISSUE THREAD

**Issue by joysarkar18** [fluttergems/fluttergems#309]
**Details of the package(s) you want to add**

- glossy 
- https://pub.dev/packages/glossy 
- /glassmorphic-ui
- I have tried most of the package listed in on /glassmorphic-ui section but none of them can achive what I want to build. Like some packages do not support defferent borderRadious some of are really complex to use. Glossy is really simple to use. It has one one widget GlossyContainer that's all and many many properties like regular container. That's why I think It's need to be on the list.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @joysarkar18.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
glossy is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/glossy/
