### ISSUE TITLE
[ADD PACKAGE] keyboard_emoji_picker

### ISSUE THREAD

**Issue by f-person** [fluttergems/fluttergems#31]
- keyboard_emoji_picker
- https://pub.dev/packages/keyboard_emoji_picker
- Emoji & Rich Text
- It's an emoji picker, essentially :)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @f-person. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package keyboard_emoji_picker is now available on Flutter Gems.
https://fluttergems.dev/packages/keyboard_emoji_picker/
