### ISSUE TITLE
[ADD PACKAGE] static_map

### ISSUE THREAD

**Issue by jointhejourney** [fluttergems/fluttergems#311]
Hey there,

We've recently released `static_map`, a client for Journey's static API platform that enables you to generate static maps in Flutter with a simple, declarative syntax. 

- static_map
- https://pub.dev/packages/static_map
- Geolocation & Maps
- This category is best given we're generating static maps.

Our documentation can be found at https://docs.journey.tech/.

Thank you, we love Flutter Gems!
Journey Team

<img src="https://github.com/fluttergems/fluttergems/assets/122474535/331aa84f-5b53-4aa7-bb9c-9eaa1e341f02" width="300" />

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @jointhejourney.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
static_map is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/static_map/
