### ISSUE TITLE
[ADD PACKAGE] flutter_debug_overlay

### ISSUE THREAD

**Issue by Bungeefan** [fluttergems/fluttergems#312]
**Details of the package you want to add**

- Name of the package: `flutter_debug_overlay`
- It's pub URL: https://pub.dev/packages/flutter_debug_overlay 
- The category: `debugging-logging`, `developer-tools`, `performance-crash-insights`, `http-client-utilities`, `dio`
- Reason: Provides a debug overlay with a log viewer, HTTP requests inspector (including `http`/`dio` interceptor), and customizable status widgets for easy debugging and local inspection.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Bungeefan.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
flutter_debug_overlay is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_debug_overlay/
