### ISSUE TITLE
[ADD PACKAGE] admob_easy

### ISSUE THREAD

**Issue by matifdeveloper** [fluttergems/fluttergems#313]
**Details of the package(s) you want to add**

- Name of the package: `admob_easy`
- It's pub URL: https://pub.dev/packages/admob_easy
- The category/section `Ads Serving`
- Reason:  AdMob Easy provides Google mobile ads integration easily to use. Users can call only simple methods. AdMob Easy automatically handles the User Messaging Platform (UMP). Admob Easy automatically checks if the device is connected to mobile data or Wi-Fi before loading ads. Additionally, users can check their internet connectivity status using `admob_easy`.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @matifdeveloper.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/admob_easy/
