### ISSUE TITLE
[ADD PACKAGE] getx_translator

### ISSUE THREAD

**Issue by Bikram40** [fluttergems/fluttergems#314]
**Details of the package(s) you want to add**

- Name of the package: `getx_translator`
- It's pub URL : [https://pub.dev/packages/getx_translator](https://pub.dev/packages/getx_translator)
- The category/section `Localization, Internationalization & Translation`
- (Reason) For generating language strings files for Getx Flutter. Easy translation with Google Sheets: The user does not have to manually get all the text; it will automatically get all the text that includes `.tr ` and can upload it to Google Sheets, where they can translate and re-import it to the Flutter app.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Bikram40.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/getx_translator/
