### ISSUE TITLE
[ADD PACKAGE] formstack

### ISSUE THREAD

**Issue by sudhi001** [fluttergems/fluttergems#315]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- formstack
-[ It's pub URL ](https://pub.dev/packages/formstack)
- Components
- FormStack is a library designed to help developers create dynamic user interfaces in Flutter. Specifically, the library is focused on creating forms and surveys using a JSON or Dart language model.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/formstack/
