### ISSUE TITLE
[ADD PACKAGE] toml_viewer

### ISSUE THREAD

**Issue by sudhi001** [fluttergems/fluttergems#316]
**Details of the package(s) you want to add**

- toml_viewer
- https://pub.dev/packages/toml_viewer
- Components
- A TOML viewer in Flutter is a user interface component that displays the contents of a TOML (Tom's Obvious, Minimal Language) file in a structured and readable format. This viewer typically parses the TOML file and presents its key-value pairs, tables, arrays, and nested structures in a visually appealing manner.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @sudhi001.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/toml_viewer/
