### ISSUE TITLE
[ADD PACKAGE] riff_switch

### ISSUE THREAD

**Issue by kenresoft** [fluttergems/fluttergems#317]
**Name of the package**: riff_switch

**Pub URL**: [riff_switch package on pub.dev](https://pub.dev/packages/riff_switch)

**Category/Section**: UI, Themes and Color

**Reason**: This package provides customizable switch widgets for Flutter applications, making it a suitable fit for the "UI, Themes and Color" category on Flutter Gems. Developers looking for versatile and visually appealing switch widgets with nice animations can easily discover and utilize riff_switch in their projects from this category.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @kenresoft.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/riff_switch/
