### ISSUE TITLE
[ADD PACKAGE] audio_metadata_reader

### ISSUE THREAD

**Issue by ClementBeal** [fluttergems/fluttergems#318]
**Details of the package(s) you want to add**

- `audio_metadata_reader` 

- [https://pub.dev/packages/audio_metadata_reader](https://pub.dev/packages/audio_metadata_reader)

- `Multimedia Utilities`
 
- This package can extract the metadata of audio files.  So it's a multimedia utility

Thank you :)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ClementBeal.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/audio_metadata_reader/
