### ISSUE TITLE
[ADD PACKAGE] integration_test_preview

### ISSUE THREAD

**Issue by cdm2012** [fluttergems/fluttergems#319]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- integration_test_preview
- https://pub.dev/packages/integration_test_preview
- Debugging & Logging, Developer Tools, Device Preview, Screen Capture & Screenshot, Testing
- When trying to find the correct layout/widget based on screen size and orientation, this tool allows for easy and quick demonstrations/tests of these visual changes and provides persistent screenshots to review after execution.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @cdm2012.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/integration_test_preview/
