### ISSUE TITLE
[ADD PACKAGE] jt_preferences

### ISSUE THREAD

**Issue by xaldarof** [fluttergems/fluttergems#32]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- jt_preferences 
- https://pub.dev/packages/jt_preferences
- NoSQL Datastore
- This is key - value storage

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @xaldarof. Will close this issue once it is live on the website after review.
