### ISSUE TITLE
[ADD PACKAGE] public_ip_address

### ISSUE THREAD

**Issue by sumanrajpathak** [fluttergems/fluttergems#320]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- public_ip_address
- https://pub.dev/packages/public_ip_address
- WiFi and Network
- Easier to get Public IP address and its details, could not get any reliable packages around to retrieve the data.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @sumanrajpathak.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/public_ip_address/
