### ISSUE TITLE
[ADD PACKAGE] astronomical_measurements

### ISSUE THREAD

**Issue by signmotion** [fluttergems/fluttergems#321]
- astronomical_measurements
- https://pub.dev/packages/astronomical_measurements
- Helpers and Utilies / Math Utilities
- Keeping and converting astronomical measurements.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @signmotion.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/astronomical_measurements/
