### ISSUE TITLE
[ADD PACKAGE] flutter_image_converter

### ISSUE THREAD

**Issue by signmotion** [fluttergems/fluttergems#323]
- flutter_image_converter
- https://pub.dev/packages/flutter_image_converter
- [Multimedia / Image](https://fluttergems.dev/image)
- Dart & Flutter image transformer package: ui, widgets, image, ImageProvider, bytes, and base64 string. Works in any direction as an extension. You no longer have to worry about writing code to convert images in different formats.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @signmotion.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_image_converter/
