### ISSUE TITLE
[ADD PACKAGE] events_emitter2

### ISSUE THREAD

**Issue by moham96** [fluttergems/fluttergems#324]
**Details of the package(s) you want to add**

- events_emitter2
- https://pub.dev/packages/events_emitter2
- [Dependency Injection & State Management](https://fluttergems.dev/state-management/)
- Simple, Type safe, maintained, uses streams which provides performance gains

**Comment by moham96** [comment]
Why is it invalid?

**Comment by ashitaprasad** [comment]
Because the project lacks documentation.
