### ISSUE TITLE
[ADD PACKAGE] dtorrent_task

### ISSUE THREAD

**Issue by moham96** [fluttergems/fluttergems#325]
**Details of the package(s) you want to add**

- dtorrent_task
- https://pub.dev/packages/dtorrent_task
- [video](https://fluttergems.dev/video/)
- written purely in dart, minimum dependencies, maintained, supports most of the main Bittorrent specifications, supports streaming videos

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @moham96.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/dtorrent_task/
