### ISSUE TITLE
[ADD PACKAGE] ispect

### ISSUE THREAD

**Issue by yelmuratoff** [fluttergems/fluttergems#326]
- ispect
- https://pub.dev/packages/ispect
- Developer tools / Debugging & Logging
- Wrapper around Inspector, Talker and etc.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @K1yoshiSho.
Will close this issue once it is live on the website after review.

**Comment by K1yoshiSho** [comment]
@ashitaprasad hello, sorry, any updates?

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/ispect/
