### ISSUE TITLE
[ADD PACKAGE] draggable_carousel_slider

### ISSUE THREAD

**Issue by MohammadJamali** [fluttergems/fluttergems#327]
- Draggable Carousel Slider
- https://pub.dev/packages/draggable_carousel_slider
- Carousel or Cover Flow

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MohammadJamali.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
 https://fluttergems.dev/packages/draggable_carousel_slider/
