### ISSUE TITLE
[ADD PACKAGE] capture_box

### ISSUE THREAD

**Issue by gus-caribe** [fluttergems/fluttergems#328]
CaptureBox is a package that turns your custom widgets into an image or a document file. It does this by wrapping your custom widget with a RepaintBoundary and converting the byte list obtained from its rendering into certain file types (currently PNG, JPG and PDF).

- capture_box 
- [It's pub URL](https://pub.dev/packages/capture_box)
- **Category:** Device Preview, Screen Capture & Screenshot
- **Reason:** It's a utility that allows developers to generate image and document files from Widget renderings. It's really similar to the "screenshot" package, which is included into this category (but it will have several other features as the roadmap evolves). That's why I think it is better suited for this category.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @gus-caribe.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/capture_box/
