### ISSUE TITLE
[ADD PACKAGE] replace_palette

### ISSUE THREAD

**Issue by signmotion** [fluttergems/fluttergems#329]
- replace_palette
- https://pub.dev/packages/replace_palette
- [Multimedia / Image](https://fluttergems.dev/image)
- Dresses the image with a new palette of colors.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @signmotion.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/replace_palette/
