### ISSUE TITLE
[ADD PACKAGE] encrypted-shared-preferences

### ISSUE THREAD

**Issue by xaldarof** [fluttergems/fluttergems#33]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- encrypted-shared-preferences 
- https://pub.dev/packages/encrypt_shared_preferences
- NoSql DataStore
- This is key-value storage based shared-preferences with several features

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @xaldarof. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package encrypt_shared_preferences is now live.
https://fluttergems.dev/packages/encrypt_shared_preferences/
