### ISSUE TITLE
[ADD PACKAGE] fire_flutter_db

### ISSUE THREAD

**Issue by vikram-vikky2002** [fluttergems/fluttergems#330]
- fire_flutter_db
- https://pub.dev/packages/fire_flutter_db
- Architecture & Infrastructure
- FireFlutter provides an effortless bridge between Flutter apps and Firebase, offering simplified authentication and Firestore database operations through a clean and intuitive API.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @vikram-vikky2002.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/fire_flutter_db/
