### ISSUE TITLE
[ADD PACKAGE] windows_toast

### ISSUE THREAD

**Issue by i-aiymen** [fluttergems/fluttergems#331]
- windows_toast
- https://pub.dev/packages/windows_toast
- Platform Specific Tools & Utilities/Desktop/Windows
- A simple flutter package designed to display toast notifications in Windows applications. This package is similar to fluttertoast package, but it is designed to work with Windows applications also.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @i-aiymen.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/windows_toast/
