### ISSUE TITLE
[ADD PACKAGE] webview_location

### ISSUE THREAD

**Issue by i-aiymen** [fluttergems/fluttergems#332]
- webview_location 
- https://pub.dev/packages/webview_location
- Platform Specific Tools & Utilities/android-ios
- A Flutter package designed to display Google Maps locations by place name in a WebView for both Android and iOS platforms. Ideal for applications that require location-based features without leaving the app interface. Easy to integrate and highly customizable, it provides a seamless user experience across different operating systems.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @i-aiymen.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/webview_location/
