### ISSUE TITLE
[ADD PACKAGE] debt_simplification

### ISSUE THREAD

**Issue by i-aiymen** [fluttergems/fluttergems#333]
- debt_simplification
- https://pub.dev/packages/debt_simplification
- Helpers and Utilities/Math Utilities
- A Dart function that simplifies debt settlements among a group, similar to 'Quick Split' app. Takes a list of debts and returns a simplified list.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @i-aiymen.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/debt_simplification/
