### ISSUE TITLE
[ADD PACKAGE] windows_ime_manager

### ISSUE THREAD

**Issue by i-aiymen** [fluttergems/fluttergems#334]
- windows_ime_manager
- https://pub.dev/packages/windows_ime_manager
- Platform Specific Tools & Utilities/windows
- The windows_ime_manager package enables easy management of Input Method Editors (IME) for Windows applications developed with Flutter. It supports different languages, allowing for straightforward IME setup and switching. This package is designed to enhance multilingual input in desktop applications, providing a reliable and simple solution for developers looking to incorporate diverse language support.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @i-aiymen.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/windows_ime_manager/
