### ISSUE TITLE
[ADD PACKAGE] weather_pack - OpenWeatherMap API package

### ISSUE THREAD

**Issue by PackRuble** [fluttergems/fluttergems#335]
Hi, there is a great package (under my authorship) for getting weather conditions and then managing/displaying them. The project is being developed and maintained.

Details:
- **weather_pack** - The project is designed to obtain weather via the OpenWeatherMap API. With geocoding and units measure. :)
- pub.dev: [weather_pack](https://pub.dev/packages/weather_pack)
- "Top Flutter API packages" category
- Reason: The package provides endpoints for the OpenWeatherMap API weather service.

Thank you!

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @PackRuble.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/weather_pack/
