### ISSUE TITLE
[ADD PACKAGE] wfile

### ISSUE THREAD

**Issue by signmotion** [fluttergems/fluttergems#336]
- wfile
- https://pub.dev/packages/wfile
- [File, Folder and Path Utilities](https://fluttergems.dev/file-folder-path-util)
- The well-tested package for reading and writing JSON, image, text, binary, and XML files across multiple platforms. Independent of the various system delimiters. Can detect MIME types.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @signmotion.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/wfile/
