### ISSUE TITLE
[ADD PACKAGE] id_gen

### ISSUE THREAD

**Issue by signmotion** [fluttergems/fluttergems#337]
- id_gen
- https://pub.dev/packages/id_gen
- [Cryptography, Security and Permissions](https://fluttergems.dev/cryptography-security-permissions)
- The standardized, easy-to-use, and well-tested set for generating identifiers: globally unique, readable, time-dependency, transitive, incremental, and decremental IDs.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @signmotion.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/id_gen/
