### ISSUE TITLE
[ADD PACKAGE] iconsax_plus

### ISSUE THREAD

**Issue by moha-b** [fluttergems/fluttergems#338]
i know that the package iconsax exists, but the owner does not respond to issues on the package. Therefore, I have solved the issues and created a new package called `iconsax_plus`.

- iconsax_plus
- [pub.dev](https://pub.dev/packages/iconsax_plus) 
- Text, Icons & Keyboard
- This package is based on the Iconsax package, which falls under the icons category.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/iconsax_plus/
