### ISSUE TITLE
[ADD PACKAGE] auth0_web_flutter

### ISSUE THREAD

**Issue by saitejavankayalatudip** [fluttergems/fluttergems#339]
i know that the package auth0 flutter exists, but in this package, it supports both the registration and login for auth0.  Max of the package, does not have the registration for the auth0 package

auth0_web_flutter
[pub.dev](https://pub.dev/packages/auth0_web_flutter)
In this package, 
This package is based on the auth0 futter, its used for both login, logout, and registration

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @saitejavankayalatudip.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/auth0_web_flutter/
