### ISSUE TITLE
[ADD PACKAGE] flutter_telegram_crashlytics

### ISSUE THREAD

**Issue by xaldarof** [fluttergems/fluttergems#34]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- flutter_telegram_crashlytics
- https://pub.dev/packages/flutter_telegram_crashlytics
- Performance and Crash Insights
- Your can send crash reports via telegram

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @xaldarof. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package flutter_telegram_crashlytics is now live.
https://fluttergems.dev/packages/flutter_telegram_crashlytics/
