### ISSUE TITLE
[ADD PACKAGE] flutter_circular_progress_indicator

### ISSUE THREAD

**Issue by edris-mazhari** [fluttergems/fluttergems#341]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- flutter_circular_progress_indicator
- [It's pub URL ](https://pub.dev/packages/flutter_circular_progress_indicator)
- Design System
- Better Looking

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @edris-mazhari.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_circular_progress_indicator/
