### ISSUE TITLE
[ADD PACKAGE] easy_infinite_pagination

### ISSUE THREAD

**Issue by FadyFayezYounan** [fluttergems/fluttergems#342]
**Details of the package(s) you want to add**

- easy_infinite_pagination
- [It's pub URL](https://pub.dev/packages/easy_infinite_pagination) 
- Scrollables/Pagination & Lazy Loading
- The Easy Infinite Pagination package provides a simple and customizable way to implement infinite pagination in your Flutter applications.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @FadyFayezYounan.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/easy_infinite_pagination/
