### ISSUE TITLE
[ADD PACKAGE] flutter_network_image

### ISSUE THREAD

**Issue by GeekAbdelouahed** [fluttergems/fluttergems#343]
**Details of the package(s) you want to add**

- flutter_network_image
- https://pub.dev/packages/flutter_network_image
- Multimedia/Image
- flutter_network_image is a flutter package that provides an ImageProvider that automatically retries failed network image loads, ensuring smooth image loading on mobile and web platforms.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @GeekAbdelouahed.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_network_image/
