### ISSUE TITLE
[ADD PACKAGE] geobase

### ISSUE THREAD

**Issue by navispatial** [fluttergems/fluttergems#344]
**Details of the package(s) you want to add**

- geobase
- https://pub.dev/packages/geobase
- The category/section: Helpers and Utilities / Geolocation utilities
- Reason: The package provides utilities and tools for "geospatial data, spherical geodesy, projections, tiling schemes, and vector formats (GeoJSON, WKT, WKB)" that can be used by flutter or dart apps (front-end or back-end), however the package do not provide any UI or widgets, so "utilities" sounds best.

_Note: A separate issue is added for "geodata" that is a related package (implemented by the same GitHub mono repo https://github.com/navibyte/geospatial).

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @navispatial.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/geobase/
