### ISSUE TITLE
[ADD PACKAGE] geodata

### ISSUE THREAD

**Issue by navispatial** [fluttergems/fluttergems#345]
**Details of the package(s) you want to add**

- geodata
- https://pub.dev/packages/geodata
- The category/section: Helpers and Utilities / Geolocation utilities
- Reason: The package provides "a geospatial client to read GeoJSON and OGC API Features data sources" that can be used by flutter or dart apps (front-end or back-end), however the package do not provide any UI or widgets, so "utilities" sounds best. Another choice could be "Networking .. / API" however this package is not generic API package, rather tools for geospatial data sources (and geospatial APIs).

_Note: A separate issues is added for "geobase" that is a related package (implemented by the same GitHub mono repo https://github.com/navibyte/geospatial).

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @navispatial.
Will close this issue once it is live on the website after review.
