### ISSUE TITLE
[ADD PACKAGE] cometchat_sdk

### ISSUE THREAD

**Issue by darshanvachhani08** [fluttergems/fluttergems#349]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- cometchat_sdk
- https://pub.dev/packages/cometchat_sdk
- Live Streaming & Real-time Communication
- It is video calling and screen sharing functionality provider

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @darshanvachhani08.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/cometchat_sdk/
