### ISSUE TITLE
[ADD PACKAGE]  assets-generator

### ISSUE THREAD

**Issue by xaldarof** [fluttergems/fluttergems#35]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- assets-generator
- https://pub.dev/packages/simple_assets_generator
- Code Generator and Serialization (JSON)
- You can easily generate class for your assets folder

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @xaldarof. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package simple_assets_generator is now live.
https://fluttergems.dev/packages/simple_assets_generator/
