### ISSUE TITLE
[ADD PACKAGE] fresher

### ISSUE THREAD

**Issue by signmotion** [fluttergems/fluttergems#350]
- fresher
- https://pub.dev/packages/fresher
- [Package Utilities](https://fluttergems.dev/package-utilities)
- An invisible (means that maintenance packages are not aware of this tool) tool to help keep your multiple projects in multiple repositories up to date: automated upgrade dependencies, update links and sections in README, CONTRIBUTING, STYLEGUIDE, wiki, etc. The easy-to-use and well-tested Dart CLI.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @signmotion.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/fresher/
