### ISSUE TITLE
[ADD PACKAGE] lemon_squeezy

### ISSUE THREAD

**Issue by UntitledApps** [fluttergems/fluttergems#351]
- Lemon Squezzy
- https://pub.dev/packages/lemon_squeezy
-  Payment API/SDK
- It offers a dart implemenation of the Lemon Squezzy API Endpoints.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @UntitledApps.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/lemon_squeezy/
