### ISSUE TITLE
[UPDATE PACKAGE] blurrycontainer

### ISSUE THREAD

**Issue by kishan-dhankecha** [fluttergems/fluttergems#352]
- Name: blurrycontainer
- Pub link: https://pub.dev/packages/blurrycontainer
- FlutterGems Link: https://fluttergems.dev/packages/blurrycontainer/

Thanks.

**Comment by ashitaprasad** [comment]
Sure .. will close this issue once it is updated on the website.

**Comment by kishan-dhankecha** [comment]
Hello @ashitaprasad,

You are manually managing these package updates and new packages. I want to help you manage this website. Let me know if that is possible and fine by you.

Thanks for this great website. ☺️

**Comment by ashitaprasad** [comment]
The update is live.
