### ISSUE TITLE
[ADD PACKAGE] Together AI SDK

### ISSUE THREAD

**Issue by ilovekimchi6** [fluttergems/fluttergems#353]
- Together AI SDK
- https://pub.dev/packages/together_ai_sdk
- ChatGPT, LLM & Generative AI
- Together AI offers a wide range of AI tools, from LLMs to image generation all neatly packed into a single SDK.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ilovekimchi6.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/together_ai_sdk
