### ISSUE TITLE
[ADD PACKAGE] orange

### ISSUE THREAD

**Issue by melodysdreamj** [fluttergems/fluttergems#354]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- orange
- https://pub.dev/packages/orange 
- Top Flutter Persistent NoSQL Database packages
- super fast x super easy x work everywhere

- code_timer
- https://pub.dev/packages/code_timer
- Top Flutter Stopwatch, Timer and Countdown packages
- easy use for code excute timer

- ready_view
- https://pub.dev/packages/ready_view 
- Top Flutter Hooks packages
- easy handle async code

- easy_event_bus
- https://pub.dev/packages/easy_event_bus 
- Top Flutter Dependency Injection and State Management packages
- easy handle event bus

**Comment by ashitaprasad** [comment]
Thanks for submitting the packages @melodysdreamj.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The packages are now available on Flutter Gems 🎉
https://fluttergems.dev/packages/orange/
https://fluttergems.dev/packages/code_timer/
https://fluttergems.dev/packages/ready_view/
https://fluttergems.dev/packages/easy_event_bus/
