### ISSUE TITLE
[ADD PACKAGE] approval_tests

### ISSUE THREAD

**Issue by yelmuratoff** [fluttergems/fluttergems#355]
- approval_tests
- https://pub.dev/packages/approval_tests
- Testing
- This is the first and official Approval Tests implementation in Dart. More info: https://approvaltests.com/

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @yelmuratoff.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/approval_tests
