### ISSUE TITLE
[ADD PACKAGE] dotted_line_flutter

### ISSUE THREAD

**Issue by Puneetsharma5525** [fluttergems/fluttergems#356]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- dotted_line_flutter 
- https://pub.dev/packages/dotted_line_flutter
- [Clipper & Decoration](https://fluttergems.dev/clipper-decoration/)
- becasue dotted_line_flutter providing developer deigning.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Puneetsharma5525.
Will close this issue once it is live on the website after review.

**Comment by Puneetsharma5525** [comment]
@ashitaprasad Any Update

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/dotted_line_flutter
