### ISSUE TITLE
[ADD PACKAGE] flutter_moving_background

### ISSUE THREAD

**Issue by IldySilva** [fluttergems/fluttergems#357]
- flutter moving background
- [It's pub URL ](https://pub.dev/packages/flutter_moving_background)
- Background Effects, Gradients and Shaders packages
- people found it interesting and currently use it in their apps, as well as looking great on any screen and being customizable.
-

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_moving_background/
