### ISSUE TITLE
[ADD PACKAGE] open_meteo

### ISSUE THREAD

**Issue by neursh** [fluttergems/fluttergems#358]
- open_meteo
- https://pub.dev/packages/open_meteo
- API
- This package introduces [Open Meteo API](https://open-meteo.com/), the open source weather API to Dart/Flutter.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @neursh.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/open_meteo/
