### ISSUE TITLE
[ADD PACKAGE] carousel_custom_slider

### ISSUE THREAD

**Issue by SwanFlutter** [fluttergems/fluttergems#359]
This is a simple slider package, you can put the position of the indicator and text on it and personalize it.

- Name of the package = carousel_custom_slider
- It's pub URL = https://pub.dev/packages/carousel_custom_slider
- The category/ (Multimedia  the Top Flutter Carousel or Cover Flow 
![20240512_074358](https://github.com/fluttergems/fluttergems/assets/151648897/e6890a85-74cd-4659-8b7b-e545e887b2d4)
)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SwanFlutter.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/carousel_custom_slider/

**Comment by SwanFlutter** [comment]
Thanks♥️🙏

‫‪Ashita Prasad‬‏ ***@***.***‬‏> در تاریخ جمعه ۷ ژوئن ۲۰۲۴
ساعت ۲۰:۵۱ نوشت:‬
