### ISSUE TITLE
[ADD PACKAGE] carousel_slider_plus

### ISSUE THREAD

**Issue by kishan-dhankecha** [fluttergems/fluttergems#360]
- carousel_slider_plus
- https://pub.dev/packages/carousel_slider_plus
- Onboarding Carousel, Carousel or Cover Flow
- Fork of [carousel_slider](https://pub.dev/packages/carousel_slider) which is not maintained anymore

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @kishan-dhankecha.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/carousel_slider_plus/
