### ISSUE TITLE
[ADD PACKAGE] cloud_text_to_speech

### ISSUE THREAD

**Issue by markokosticdev** [fluttergems/fluttergems#361]
- Name: Cloud Text-To-Speech (cloud_text_to_speech)
- Pub Link: https://pub.dev/packages/cloud_text_to_speech
- Git Link: https://github.com/markokosticdev/cloud_text_to_speech_flutter
- Category: Voice Assistant, ASR, TTS and STT packages
- Reason: It is a TTS package that is "Single interface to Google, Microsoft, and Amazon Text-To-Speech"

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @markokosticdev.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/cloud_text_to_speech/
