### ISSUE TITLE
[ADD PACKAGE] any_image_view

### ISSUE THREAD

**Issue by farhansadikgalib** [fluttergems/fluttergems#362]
- Name: any_image_view
- Pub Link: https://pub.dev/packages/any_image_view
- Git Link: https://github.com/farhansadikgalib/any_image_view
- Category: Image, Responsive UI
- Reason: It supports multiple image formats including JPG, PNG, SVG, Lottie, and XFile, with network image caching. With numerous customization options for image properties and interactions to view.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @farhansadikgalib.
Will close this issue once it is live on the website after review.

**Comment by farhansadikgalib** [comment]
is there any update?

**Comment by farhansadikgalib** [comment]
is there any update?

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/any_image_view/

**Comment by farhansadikgalib** [comment]
**Thank you for your support.**
