### ISSUE TITLE
[ADD PACKAGE] progress_bar_chart

### ISSUE THREAD

**Issue by LukasKompatscher** [fluttergems/fluttergems#363]
**A package to display multipe values on a vertical chart using progess indicators and animation. Each value can has a color .**

- progress_bar_chart
- [progess_bar_chart](https://pub.dev/packages/progress_bar_chart)
- Plots & Visualization
- It displays data in a vertical chart.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @LukasKompatscher.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/progress_bar_chart/
