### ISSUE TITLE
[ADD PACKAGE] liquid_container

### ISSUE THREAD

**Issue by Okladnoj** [fluttergems/fluttergems#364]
**Details of the package**

- Liquid Button
- [It's pub URL](https://pub.dev/packages/liquid_container) 
- liquid-squishy-ui
- (Reason) Because the button implements the liquid/hover effect

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Okladnoj.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/liquid_container/

**Comment by Okladnoj** [comment]
Thank you for organizing and structuring the pub.dev site
