### ISSUE TITLE
[ADD PACKAGE] whitecodel_reels

### ISSUE THREAD

**Issue by whitecodel** [fluttergems/fluttergems#366]
**A Flutter package to easily integrate instagram like reels in your app**

- WhiteCodel Reels 
- https://pub.dev/packages/whitecodel_reels
- Social Media
- Because this package is for social media things

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @whitecodel.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/whitecodel_reels/
