### ISSUE TITLE
[ADD PACKAGE] Icon Craft

### ISSUE THREAD

**Issue by vicenterusso** [fluttergems/fluttergems#367]
- icon_craft
- https://pub.dev/packages/icon_craft
- Icons
- This package opens many possibilities to "craft" icons on demand, by mixing 2 icons to give users a better context of specific task/area/button

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @vicenterusso.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/icon_craft/
