### ISSUE TITLE
[ADD PACKAGE] sliver_snap

### ISSUE THREAD

**Issue by Mohanedy98** [fluttergems/fluttergems#37]
Sliver Snap is a Flutter package that simplifies the process of adding collapsible and expandable app bars to your app. It offers smooth transitions that respond seamlessly to user scrolling and snaps to the appropriate mode when the user stops scrolling midway. It's highly customizable and provides a user-friendly experience.

- Sliver Snap
- [SliverSnap](https://pub.dev/packages/sliver_snap)
- Widget Library & UI Framework
- The package includes several widgets that are specifically designed for scrolling and snapping behavior, such as SliverAppBar and SliverList, making it an ideal choice for this category. Additionally, the package offers a range of customization options, including scroll physics, snap behavior, and animation settings, allowing developers to create unique and engaging UI experiences.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Mohanedy98. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package sliver_snap is now live.
https://fluttergems.dev/packages/sliver_snap/
