### ISSUE TITLE
[ADD PACKAGE] fui_kit

### ISSUE THREAD

**Issue by baldomerocho** [fluttergems/fluttergems#370]
- FUI kit
- [It's pub URL ](https://pub.dev/packages/fui_kit)
- Icons
- There are 498 open source icons, designed to improve UI

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @baldomerocho.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/fui_kit/
