### ISSUE TITLE
[ADD PACKAGE] animated_analog_clock

### ISSUE THREAD

**Issue by MuhammadHasan-Git** [fluttergems/fluttergems#371]
- animated_analog_clock
- https://pub.dev/packages/animated_analog_clock
- Clock
- (Reason) This package provides an animated analog clock, making it ideal for the Clock category.
![animated_analog_clock_dark](https://github.com/fluttergems/fluttergems/assets/104097985/727a423f-464a-410c-a386-00e3a2ceb3cb)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MuhammadHasan-Git.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/animated_analog_clock/
