### ISSUE TITLE
[ADD PACKAGE] Cosmos Epub

### ISSUE THREAD

**Issue by Mamasodikov** [fluttergems/fluttergems#372]
**Details of the package(s) you want to add**

- Cosmos Epub
- [It's pub URL ](https://pub.dev/packages/cosmos_epub)
- Top Flutter EPUB packages
- (Reason) CosmosEpub is a Flutter package that allows users to open and read EPUB files easily.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Mamasodikov.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/cosmos_epub/
