### ISSUE TITLE
[ADD PACKAGE] zkfinger10

### ISSUE THREAD

**Issue by Mamasodikov** [fluttergems/fluttergems#373]
**Details of the package(s) you want to add**

- zkfinger10
- [It's pub URL ](https://pub.dev/packages/zkfinger10)
- Top Flutter Biometric and Local Authentication packages
- (Reason) This package can provide support for ZKTeco fingerprint scanners. Its compatible devices are SLK20R and ZK series fingerprint scanners, including ZK9500, ZK6500, ZK8500R. The package could be work on Android OS. (It's not official package)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Mamasodikov.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/zkfinger10/
