### ISSUE TITLE
[ADD PACKAGE] uzpay

### ISSUE THREAD

**Issue by Mamasodikov** [fluttergems/fluttergems#374]
**Details of the package(s) you want to add**

- uzpay
- [It's pub URL ](https://pub.dev/packages/uzpay)
- Top Flutter Payment API/SDK packages
- (Reason) UzPay is a Flutter package that allows you to make EASY payments through payment systems operating in Uzbekistan.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Mamasodikov.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/uzpay/
