### ISSUE TITLE
[ADD PACKAGE] flutter_rearch

### ISSUE THREAD

**Issue by busslina** [fluttergems/fluttergems#377]
**Details of the package(s) you want to add**

- flutter_rearch
- [pub URL](https://pub.dev/packages/flutter_rearch)
- Dependency Injection and State Management
- (Reason) Top notch in its category

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @busslina.
Will close this issue once it is live on the website after review.

**Comment by busslina** [comment]
Cool, thanks

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_rearch/
