### ISSUE TITLE
[ADD PACKAGE] extensionresoft

### ISSUE THREAD

**Issue by kenresoft** [fluttergems/fluttergems#380]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package: extensionresoft 
- It's pub URL: https://pub.dev/packages/extensionresoft
- The category/section where it should be added: helpers/utilites/extensions
- (Reason) Why is it best suited for this category: 
It contains a collection of useful Dart/Flutter extension functions and helper functions for faster development. This was developed to help developers write minimized but powerful code. This makes for code reusability and easy coding reading. It's aimed at enhancing productivity and improving code readability.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @kenresoft.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/extensionresoft/
