### ISSUE TITLE
[ADD PACKAGE] k_chart_plus

### ISSUE THREAD

**Issue by TrangLeQuynh** [fluttergems/fluttergems#381]
_Note: Maybe this is the best k chart, depth chart in Flutter.Support drag, scale, long press, fling. And easy to use._

**Maybe this is the best k chart, depth chart in Flutter.Support drag, scale, long press, fling. And easy to use. Furthermore, `ChartColor` helped to set the color for the chart. You need to flexibly change according to your theme configuration to ensure UI. [Dark | Light theme]**

- k_chart_plus
- [k_chart_plus](https://pub.dev/packages/k_chart_plus) 
- Plots & Visualization
- Easy to use, flexible color change, flexible height for the chart.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @TrangLeQuynh.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/k_chart_plus/
