### ISSUE TITLE
[ADD PACKAGE] github_signin_aksoyhlc

### ISSUE THREAD

**Issue by Aksoyhlc** [fluttergems/fluttergems#382]
**Details of the package(s) you want to add**

- github_signin_aksoyhlc 
- https://pub.dev/packages/github_signin_aksoyhlc
- Authentication Providers & UI
- It supports login with Github.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Aksoyhlc.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/github_signin_aksoyhlc/
