### ISSUE TITLE
[ADD PACKAGE] api_bloc

### ISSUE THREAD

**Issue by Nialixus** [fluttergems/fluttergems#383]
**Flutter widgets designed to simplify the implementation of the BLoC pattern for REST APIs within an MVC architecture. Significantly reduces boilerplate code by automating BLoC pattern and test generation for handling REST API interactions.**

- Api Bloc
- https://pub.dev/packages/api_bloc
- Dependency Injection/State Managements 
- It manages state and helps separate logic from its components

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Nialixus.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/api_bloc/
