### ISSUE TITLE
[ADD PACKAGE] nenuphar_cli

### ISSUE THREAD

**Issue by Eradparvar** [fluttergems/fluttergems#384]
- nenuphar_cli
- https://pub.dev/packages/nenuphar_cli
- OpenAPI and Swagger or the HTTP Client and Utilities
- the package generates open api schema from dart_frog code

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Eradparvar.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/nenuphar_cli/
