### ISSUE TITLE
[ADD PACKAGE] fontresoft

### ISSUE THREAD

**Issue by kenresoft** [fluttergems/fluttergems#385]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package : fontresoft
- It's pub URL: https://pub.dev/packages/fontresoft
- The category/section where it should be added : fonts
- (Reason) Why is it best suited for this category : FontResoft is a comprehensive Flutter font package curated to provide developers with a diverse selection of beautiful fonts for building visually appealing and engaging Flutter applications. With a wide range of font families and weights readily available, FontResoft simplifies the process of integrating custom typography into Flutter projects.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/fontresoft/
