### ISSUE TITLE
[ADD PACKAGE] payment_card

### ISSUE THREAD

**Issue by kenresoft** [fluttergems/fluttergems#386]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package : payment_card
- It's pub URL : https://pub.dev/packages/payment_card
- The category/section where it should be added: Credit Card UI & Scanner
- (Reason) Why is it best suited for this category : The PaymentCard widget is a flexible Flutter widget designed to display payment card information with customizable properties. It enables developers to showcase payment card details such as the card number, card type, cardholder name, and background image in a visually appealing manner.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @kenresoft.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/payment_card/
