### ISSUE TITLE
[ADD PACKAGE] flutter_icp_auth

### ISSUE THREAD

**Issue by SomyaRanjanSahu** [fluttergems/fluttergems#387]
## **Details of the package(s) you want to add**

- package name: *flutter_icp_auth*
- Pub.dev URL: https://pub.dev/packages/flutter_icp_auth 
- Category: Web3, Crypto and Blockchain
- There is no other package that automates the flutter integration with Internet Identity.

## Description:

It is a package that automates Internet Identity authentication with Flutter. All the delegation and the complex steps are handled inside the package. The user only has to call the login and the logout function. 

Please refer to the package *README.md* for better understanding.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_icp_auth/
