### ISSUE TITLE
[ADD PACKAGE] image_loader_flutter

### ISSUE THREAD

**Issue by ravims07** [fluttergems/fluttergems#388]
Load image from internet / assets or from file in few line of code

**Comment by ashitaprasad** [comment]
Adding the pub.dev link - https://pub.dev/packages/image_loader_flutter
Thanks for submitting the package @ravims07.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/image_loader_flutter/
