### ISSUE TITLE
[ADD PACKAGE] media_query_preview

### ISSUE THREAD

**Issue by KoheiKanagu** [fluttergems/fluttergems#389]
- Name: media_query_preview
- URL: https://pub.dev/packages/media_query_preview
- Category: Device Preview, Screen Capture & Screenshot
- Reason: This package enables UI preview across various devices and conditions, supporting custom devices, brightness, and text scales.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @KoheiKanagu.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/media_query_preview/
