### ISSUE TITLE
[ADD PACKAGE] equal_space

### ISSUE THREAD

**Issue by RanaSharjeelShji** [fluttergems/fluttergems#392]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package : equal_space
- It's pub URL : https://pub.dev/packages/equal_space
- The category/section where it should be added (Widget Library & UI Framework, Responsive UI packages)

- - Customizable Spacing: Easily adjust the space between child widgets.
- Flexible Alignment: Support for main axis and cross axis alignment.
- Simplified Code: Reduces boilerplate code for spacing in rows and columns.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @RanaSharjeelShji.
Will close this issue once it is live on the website after review.
