### ISSUE TITLE
[UPDATE PACKAGE] uni_payments

### ISSUE THREAD

**Issue by NehilKoshiya** [fluttergems/fluttergems#394]
**Update the existing package details**

- Name of the package: uni_payments
- It's pub URL: https://pub.dev/packages/uni_payments
- Flutter Gem URL: https://fluttergems.dev/packages/uni_payments/
- The category/section where it should be added **Payment API/SDK**
- **I recently updated my Flutter package on Flutter Pub Dev, but I noticed that the version displayed on Flutter Gems is still the old one. Could you please update the listing to reflect the latest version?**

**Comment by ashitaprasad** [comment]
Sure .. will close this issue once it is updated on the website.

**Comment by ashitaprasad** [comment]
Updated.
