### ISSUE TITLE
[ADD PACKAGE] posix_tz

### ISSUE THREAD

**Issue by MattiaPispisa** [fluttergems/fluttergems#395]
- Name: posix_tz 
- Link: https://pub.dev/packages/posix_tz
- Category: date-time-utilities
- Reason: This library provides timezones in the standard Posix format. I couldn't find a library that already had this use case, so I created one myself.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MattiaPispisa.
Will close this issue once it is live on the website after review.
