### ISSUE TITLE
[ADD PACKAGE] stylish_pull_to_refresh

### ISSUE THREAD

**Issue by dv-mahbub** [fluttergems/fluttergems#396]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- stylish_pull_to_refresh  
- [It's pub URL ](https://pub.dev/packages/stylish_pull_to_refresh)
- Ui/Animation
- (Reason) Some awesome animation.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @dv-mahbub.
Will close this issue once it is live on the website after review.
