### ISSUE TITLE
[ADD PACKAGE] islamic_hijri_calendar

### ISSUE THREAD

**Issue by DevCodeSpace** [fluttergems/fluttergems#401]
package details :  Islamic Hijri Calendar widget displays dates in Arabic and English numerals, shows Hijri month names and years, and allows effortless month navigation.

- package name :  islamic_hijri_calendar
- pub :  https://pub.dev/packages/islamic_hijri_calendar
- Category :  Date, Time and Calendar/Calendar
- (Reason) Why is it best suited for this category :  Provides an intuitive Hijri Calendar with dual numerals, month names, and easy navigation

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @DevCodeSpace.
Will close this issue once it is live on the website after review.
