### ISSUE TITLE
[ADD PACKAGE] json_gen_form

### ISSUE THREAD

**Issue by maxmeng93** [fluttergems/fluttergems#402]
- package name : json_gen_form
- pub : https://pub.dev/packages/json_gen_form
- Category : Form
- (Reason) Why is it best suited for this category : This package helps users generate Flutter forms
- It supports:
  - Generate forms from JSON
  - Custom styles and layouts
  - Support for form validation
  - Support for form submission
  - Forms can be grouped with unlimited nesting

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @maxmeng93.
Will close this issue once it is live on the website after review.
