### ISSUE TITLE
[ADD PACKAGE] flutter_cell_info

### ISSUE THREAD

**Issue by darixsamani** [fluttergems/fluttergems#405]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- flutter_cell_info
- https://pub.dev/packages/flutter_cell_info 
- Sensors
- Flutter Cell Info Plugin

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @darixsamani.
Will close this issue once it is live on the website after review.
