### ISSUE TITLE
[ADD PACKAGE] chrome_ai

### ISSUE THREAD

**Issue by melodysdreamj** [fluttergems/fluttergems#406]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- chrome_ai
- https://pub.dev/packages/chrome_ai 
- Top Flutter ChatGPT, LLM and Generative AI packages

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @melodysdreamj.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/chrome_ai/
