### ISSUE TITLE
[ADD PACKAGE] rating_and_feedback_collector

### ISSUE THREAD

**Issue by DevCodeSpace** [fluttergems/fluttergems#407]
package details : Customizable rating bars with emojis, icons, custom images with half/full ratings and dynamic feedback alerts for low ratings & redirect to store for high ratings.

package name : rating_and_feedback_collector
pub : https://pub.dev/packages/rating_and_feedback_collector
Category : User Journey, Feedback
(Reason) Why is it best suited for this category : Provides an intuitive rating bar with emojis, icons, and custom images with feedback alerts.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @DevCodeSpace.
Will close this issue once it is live on the website after review.
