### ISSUE TITLE
[ADD PACKAGE] flutter_3d_objects

### ISSUE THREAD

**Issue by abdulsamad110** [fluttergems/fluttergems#408]
A Flutter package project that renders Wavefront's 3D object files.

- flutter_3d_objects
- [It's pub URL ](https://pub.dev/packages/flutter_3d_objects)
- 3D
- Displays a 3D model, .obj files

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @abdulsamad110.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_3d_objects/
