### ISSUE TITLE
[ADD PACKAGE] fulde_keyboard

### ISSUE THREAD

**Issue by al-mohad** [fluttergems/fluttergems#409]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- fulde_keyboard
- [It's pub URL ](https://pub.dev/packages/fulde_keyboard)
- localization-internationalization
- (Reason) It deals with language

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @al-mohad.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/fulde_keyboard/
