### ISSUE TITLE
[ADD APPLICATION]

### ISSUE THREAD

**Issue by ThomasVuNguyen** [fluttergems/fluttergems#41]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- comfySSH
- https://github.com/ThomasVuNguyen/ComfySSH_flutter
- The category/section where it should be added: networking & hobbyiest
- Using flashy_tab_bar2

**Comment by ashitaprasad** [comment]
Hi @ThomasVuNguyen, 
This issue template is used to only add package so I am closing this issue as this project is not a Dart/Flutter package.
