### ISSUE TITLE
[ADD PACKAGE] ve_sdk_flutter

### ISSUE THREAD

**Issue by GlebPBanuba** [fluttergems/fluttergems#410]
A Flutter package project that allows users to edit video

**Add cutting-edge video editing functionality to your Flutter app in minutes. This is the official plugin for Banuba Video Editor SDK.**

- ve_sdk_flutter 
- [It's pub URL](https://pub.dev/packages/ve_sdk_flutter) 
- Media. Video, Video Editing
- dd cutting-edge video editing functionality to your Flutter app in minutes

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/ve_sdk_flutter/
