### ISSUE TITLE
[ADD PACKAGE] en_logger

### ISSUE THREAD

**Issue by MattiaPispisa** [fluttergems/fluttergems#412]
- Name of the package: en_logger
- It's pub URL: https://pub.dev/packages/en_logger
- The category/section where it should be added: Debugging and Logging
- (Reason) Why is it best suited for this category: EnLogger is an abstraction for logging, so you don’t have to rely on a specific implementation to write messages. EnLogger accepts a list of handlers, with each handler determining how and where to log messages, such as to a file or to the developer console, etc. There is already a built-in handler for logging messages to the developer console.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MattiaPispisa.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/en_logger/
