### ISSUE TITLE
[ADD PACKAGE] flexi_bottom_nav

### ISSUE THREAD

**Issue by harshilchovatiya** [fluttergems/fluttergems#416]
Name of the package: FlexiBottomNavigation

It's pub URL: https://pub.dev/packages/flexi_bottom_nav

The category/section where it should be added: Navigation, Bottom Navigation bar

Reason: This package is ideal for the Navigation category as it provides a highly customizable bottom navigation bar, allowing developers to easily configure icons, labels, and colors, enhancing the navigation experience in Flutter apps.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @harshilchovatiya.
Will close this issue once it is live on the website after review.
