### ISSUE TITLE
[ADD PACKAGE] image_to_clipboard

### ISSUE THREAD

**Issue by harshilchovatiya** [fluttergems/fluttergems#418]
Details of the package

Name of the package: ImageToClipboard
It's pub URL: https://pub.dev/packages/image_to_clipboard
The category/section where it should be added: device-utilities
(Reason) Why is it best suited for this category:
ImageToClipboard is a specialized Flutter plugin designed for copying images to the clipboard on Android. It simplifies the process of handling image files and clipboard operations, making it a perfect fit for the Clipboard category. By providing a seamless API for copying images directly from file paths, it enhances the capabilities of Flutter applications that require image handling and clipboard interactions. This plugin is especially useful for developers looking to implement image-sharing features, making it an ideal addition to the Clipboard category on fluttergems.dev.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @harshilchovatiya.
Will close this issue once it is live on the website after review.
