### ISSUE TITLE
[ADD PACKAGE] navigation_utils

### ISSUE THREAD

**Issue by rayliverified** [fluttergems/fluttergems#419]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- navigation_utils
- https://pub.dev/packages/navigation_utils
- https://fluttergems.dev/routing/
- Navigation library that uses the Navigator 2 API the most closely.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @rayliverified.
Will close this issue once it is live on the website after review.
