### ISSUE TITLE
[ADD PACKAGE] snug_logger

### ISSUE THREAD

**Issue by wmt-mobile** [fluttergems/fluttergems#420]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- snug_logger
- https://pub.dev/packages/snug_logger
- Debugging & Logging
- A logging package for Flutter that's as comfy as your favorite hoodie and as efficient as a well-oiled machine.
- Say goodbye to boring logs and hello to vibrant, colorful messages! Snug Logger makes logging a joyful dance of information. Let it add a touch of fun to your code canvas and make your development journey a lively celebration! 🌟💻🎉

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/snug_logger/
