### ISSUE TITLE
[ADD PACKAGE] horizontal_week_calendar

### ISSUE THREAD

**Issue by ChandAbdullah** [fluttergems/fluttergems#43]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- horizontal_week_calendar
- https://pub.dev/packages/horizontal_week_calendar
- Calendar
- It contains **Horizontal Calendar View**.
A horizontal week calendar with a change week and on-date selected function.

**Comment by ashitaprasad** [comment]
Package horizontal_week_calendar is now live.
https://fluttergems.dev/packages/horizontal_week_calendar/
