### ISSUE TITLE
[ADD PACKAGE] deepar_flutter

### ISSUE THREAD

**Issue by mohamedsalah414** [fluttergems/fluttergems#44]
- deepar_flutter
- [deepar_flutter](https://pub.dev/packages/deepar_flutter)
- AR & VR
- A Flutter plugin for Camera video and Photo Augmented reality recording.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @mohamedsalah414. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package deepar_flutter is now live.
https://fluttergems.dev/packages/deepar_flutter/
