### ISSUE TITLE
[ADD PACKAGE] animated_reorderable_list

### ISSUE THREAD

**Issue by cp-sneha-s** [fluttergems/fluttergems#449]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- animated_reorderable_list
- https://pub.dev/packages/animated_reorderable_list
- The category/section where it should be added - List, Grid, Animation & Transition
- (Reason) This library is a powerful and easy-to-use solution for implementing animated list and grid with drag-and-drop functionality in Flutter.

**Comment by ashitaprasad** [comment]
The package is available here - https://fluttergems.dev/packages/animated_reorderable_list/
