### ISSUE TITLE
[ADD PACKAGE] gantt_chart

### ISSUE THREAD

**Issue by ahmednfwela** [fluttergems/fluttergems#45]
**Details of the package(s) you want to add**

- gantt_chart
- https://pub.dev/packages/gantt_chart
- Plots and Visualization
- It displays gantt charts

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ahmednfwela. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package gantt_chart is now live.
https://fluttergems.dev/packages/gantt_chart/
