### ISSUE TITLE
[ADD PACKAGE] apple_sign_in_plugin

### ISSUE THREAD

**Issue by Digvijaysinh2204** [fluttergems/fluttergems#454]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- apple_sign_in_plugin
- [It's pub URL ](https://pub.dev/packages/apple_sign_in_plugin)
- Authentication Providers & UI
- The apple_sign_in_plugin package provides robust support for integrating Apple Sign-In in Flutter applications while ensuring seamless management of access tokens and consistent availability of user data. By automating token revocation and regeneration, it helps maintain a smooth user experience without compromising on security or data integrity. The plugin automatically generates the client secret, so you don't need to handle this manually.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Digvijaysinh2204.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/apple_sign_in_plugin/
