### ISSUE TITLE
[ADD PACKAGE] dropdown_month_year_selector

### ISSUE THREAD

**Issue by prdalai** [fluttergems/fluttergems#455]
dropdown_month_year_selector 
A Flutter package that provides a customizable month and year dropdown calendar.

Installation 
Install my-project with yaml

dependencies:
  dropdown_month_year_selector: ^1.0.4
![RPReplay_Final1723118198 (1) (1)](https://github.com/prdalai/dropdown_month_year_selector/blob/main/assets/images/RPReplay_Final1723118198.gif?raw=true)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @prdalai.
Will close this issue once it is live on the website after review.

Adding the pub.dev link - https://pub.dev/packages/dropdown_month_year_selector

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/dropdown_month_year_selector/
