### ISSUE TITLE
[ADD PACKAGE] ZoomLens

### ISSUE THREAD

**Issue by Seshubhai96** [fluttergems/fluttergems#456]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- ZoomLens
-[ It's pub URL ](https://pub.dev/packages/zoom_lens)
- Multimedia
- (Reason) Why is it best suited for this category

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Seshubhai96.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/zoom_lens/
