### ISSUE TITLE
[ADD PACKAGE] calendar_awesome

### ISSUE THREAD

**Issue by mahdi-sharifii** [fluttergems/fluttergems#457]
_Note: To add multiple packages, open a separate issue for each package._

**A customizable calendar widget (Jalali & Gregorian) for Flutter**

- calendar_awesome 
- [It's pub URL](https://pub.dev/packages/calendar_awesome) 
- The category/Date, Time and Calendar
- There are very few libraries that support both Jalali and Gregorian dates, and those that do often lack customization options. This library, however, offers extensive personalization features for users

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @mahdi-sharifii.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/calendar_awesome/
