### ISSUE TITLE
animated_botton_navigation

### ISSUE THREAD

**Issue by AmirmahdiNourkazemi** [fluttergems/fluttergems#458]
An animated bottom navigation bar for Flutter, designed to provide a smooth and visually appealing transition between tabs.
![3](https://github.com/user-attachments/assets/30c468b6-242e-48d9-af60-d072f90fd8b7)

- animated_botton_navigation
- [It's pub URL ](https://pub.dev/packages/animated_botton_navigation)
- in categoty of Navigation,search & sharing inside Bottom navigation bar here: https://fluttergems.dev/bottom-navigation-bar/
- because this package related to Bottom navigation bar and also it is animated

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/animated_botton_navigation/

**Comment by AmirmahdiNourkazemi** [comment]
Thanks for your support 🙏
