### ISSUE TITLE
[ADD PACKAGE] iconify_design

### ISSUE THREAD

**Issue by ThisIsMonta** [fluttergems/fluttergems#459]
A Flutter package that allows you to use icons from the [Iconify.design](https://iconify.design/) API with ease. This package provides a widget called **IconifyIcon** that takes an icon string and optionally allows you to specify the size and color of the icon.

- iconify_design
- https://pub.dev/packages/iconify_design
- Server Driven UI & Widget Generation
- The main idea behind this package is to get icons from the server by storing the icon name only, which gives full control over the app without the need of compilation and updates.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ThisIsMonta.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/iconify_design/
