### ISSUE TITLE
[ADD PACKAGE] aptabase_flutter

### ISSUE THREAD

**Issue by goenning** [fluttergems/fluttergems#46]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package: aptabase_flutter
- https://pub.dev/packages/aptabase_flutter
- Analytics and Consumer Insights
- It's a privacy-first analytics package for flutter

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @goenning. We will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package aptabase_flutter is now live.
https://fluttergems.dev/packages/aptabase_flutter/
