### ISSUE TITLE
[ADD PACKAGE] avatar_plus

### ISSUE THREAD

**Issue by YudizAndroidNareshP** [fluttergems/fluttergems#460]
This package is perfect for creating profile pictures, gaming logos, or adding personalized touches to your design projects.

- avatar_plus
- https://pub.dev/packages/avatar_plus
- The category/avatar
- Avatar Plus is a Flutter package that allows you to generate and customize unique avatars easily. With up to 12 billion unique avatars possible, this package is perfect for creating profile pictures, gaming logos, or adding personalized touches to your design projects.

![](https://raw.githubusercontent.com/YudizAndroidNareshP/Avatar-Plus/main/screenshots/banner.png)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @YudizAndroidNareshP.
Will close this issue once it is live on the website after review.
