### ISSUE TITLE
[ADD PACKAGE] data_migration

### ISSUE THREAD

**Issue by MattiaPispisa** [fluttergems/fluttergems#461]
- Name of the package: **data_migration** 
- It's pub URL: https://pub.dev/packages/data_migration
- The category/section where it should be added: Database Adapters and Connectors packages
- (Reason) Why is it best suited for this category: A library for applying a series of migrations to update old versions of data structures to the most recent one. 100% documentation, coverage 100%.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MattiaPispisa.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/avatar_plus/
