### ISSUE TITLE
[ADD PACKAGE] http_file_uploader

### ISSUE THREAD

**Issue by MattiaPispisa** [fluttergems/fluttergems#462]
- Name of the package: http_file_uploader
- It's pub URL: https://pub.dev/packages/http_file_uploader
- The category/section where it should be added: ["HTTP Client and Utilities", "File, Folder and Path Utilities"]
- (Reason) Why is it best suited for this category: A [en_file_uploader](https://pub.dev/packages/en_file_uploader) plugin to handle the file upload using [http](https://pub.dev/packages/http) package.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MattiaPispisa.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/http_file_uploader/
