### ISSUE TITLE
[ADD PACKAGE] form_model

### ISSUE THREAD

**Issue by sukhrob-djumaev** [fluttergems/fluttergems#464]
**A powerful and flexible form validation package for Flutter applications.**

- form_model
- https://pub.dev/packages/form_model
- form

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @sukhrob-djumaev.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/form_model/
