### ISSUE TITLE
[ADD PACKAGE] flutter_file_uploader

### ISSUE THREAD

**Issue by MattiaPispisa** [fluttergems/fluttergems#465]
- Name of the package: flutter_file_uploader
- It's pub URL: https://pub.dev/packages/flutter_file_uploader
- The category/section where it should be added: ["File, Folder and Path Utilities", "Widget Library and UI Framework", "HTTP Client and Utilities"]
- (Reason) Why is it best suited for this category: This package use [en_file_uploader](https://pub.dev/packages/en_file_uploader) and provides widgets and business logics for displaying and managing file uploads.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MattiaPispisa.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_file_uploader/
