### ISSUE TITLE
[ADD PACKAGE] StateX

### ISSUE THREAD

**Issue by Andrious** [fluttergems/fluttergems#466]
_Note: To add multiple packages, open a separate issue for each package._

**The State class is Flutter’s main player in State Management. The StateX class then extends those capabilities to a separate controller class called, StateXController. This arrangement encourages a clean architecture separating all the mutable properties and business logic from the State object and its interface and supplying state management from outside the State class itself! Not only can the controller class call the State object's setState() function, it will give you access to the State object itself, its functions, and its many properties (e.g. widget, mounted, context, etc.).**

- state_extended 
- [StateX](https://github.com/AndriousSolutions/state_extended)
- Flutter Framework
- This serves as the bedrock, the foundation, of your next Flutter app. 
   Like any Framework, it provides sound and tested functions and features for a production-ready app.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/state_extended/
