### ISSUE TITLE
[ADD PACKAGE] image_loader_flutter

### ISSUE THREAD

**Issue by codeislife07** [fluttergems/fluttergems#467]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- image_loader_flutter 
- [It's pub URL ](https://pub.dev/packages/image_loader_flutter)
- Image
- my package is for show image on ui with same widget and pass url (assets/local/internet) of image

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @codeislife07.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package is available here - https://fluttergems.dev/packages/image_loader_flutter/
