### ISSUE TITLE
[ADD PACKAGE] flutter_social_share_plugin

### ISSUE THREAD

**Issue by KhilanVitthani** [fluttergems/fluttergems#469]
_Note: To add multiple packages, open a separate issue for each package._

**You can use it share to Facebook , Instagram , WhatsApp(WhatsAppBusiness) , Twitter, telegram And System Share UI. Support Url and Text.**

- flutter_social_share_plugin
- [It's pub URL](https://pub.dev/packages/flutter_social_share_plugin) 
- Sharing & Intent
- My package hase the latest code the old package named [flutter_share_me](https://pub.dev/packages/flutter_share_me) have some issue with tweeter sdk [issue](https://github.com/OpenFlutter/flutter_share_me/issues/123) and my package work properly

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @KhilanVitthani.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_social_share_plugin/
