### ISSUE TITLE
[ADD PACKAGE] - deeplink_rpc

### ISSUE THREAD

**Issue by redDwarf03** [fluttergems/fluttergems#47]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- deeplink_rpc
- https://pub.dev/packages/deeplink_rpc
- HTTP Client and Utilities packages
- The RPC-via-deeplink communication protocol doesn't exist before this lib :)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @redDwarf03 . Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package deeplink_rpc is now live.
https://fluttergems.dev/packages/deeplink_rpc/
