### ISSUE TITLE
[ADD PACKAGE] flutter_mediator

### ISSUE THREAD

**Issue by farajshuaib** [fluttergems/fluttergems#470]
_Note: To add multiple packages, open a separate issue for each package._

The Dart Mediator package provides an implementation of the Mediator pattern for Dart inspired by MediatR ASP.net Core, including dynamic handler registration via code generation. This pattern is useful for organizing your application's commands and queries by centralizing their processing through a mediator.

- Dart Mediator Package
- https://pub.dev/packages/dart_mediatr
- Flutter Framework
- In the world of software design patterns, the Mediator Pattern and CQRS (Command Query Responsibility Segregation) are powerful tools that help manage complex interactions and improve the scalability of applications. This article will explore these concepts and how they are implemented in Flutter using the dart_mediatR package.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @farajshuaib.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/dart_mediatr/
