### ISSUE TITLE
[ADD PACKAGE] multiselect_field

### ISSUE THREAD

**Issue by JhonaCodes** [fluttergems/fluttergems#471]
_Note: To add multiple packages, open a separate issue for each package._

**Subject:** Request to add package - multiselect_field

**Details of the package I would like to add:**

- **Package name:** multiselect_field
- [https://pub.dev/packages/multiselect_field](https://pub.dev/packages/multiselect_field)
- Dropdown
- The multiselect_field package makes it easy to implement multi-selection functionality in Flutter forms with a clean and highly customizable UI, Customizable layouts, Simple integration, Customizable title & footer, Customizable multi-selection widget, Single selection option, Search functionality, Default data loading, Padding customization, etc.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @JhonaCodes.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/multiselect_field/

**Comment by JhonaCodes** [comment]
> The package is now available on Flutter Gems 🎉 https://fluttergems.dev/packages/multiselect_field/

Thank you so much.
