### ISSUE TITLE
[ADD PACKAGE] nation_code_picker

### ISSUE THREAD

**Issue by enescerrahoglu** [fluttergems/fluttergems#472]
_Note: To add multiple packages, open a separate issue for each package._

**This package provides a widget that allows you to select country dialing codes in your applications.**

- nation_code_picker
- https://pub.dev/packages/nation_code_picker
- Country Picker & Country Code Picker
- It contains quality country flag images, is easy to use and offers a compatible structure for every UI.

![363489803-9879684e-b9a1-46f3-a203-088fd3f0b768](https://github.com/user-attachments/assets/e923f9a6-0a61-4ec8-9d8d-9447d38f6f93)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @enescerrahoglu.
Will close this issue once it is live on the website after review.
