### ISSUE TITLE
[ADD PACKAGE] login_client_flutter

### ISSUE THREAD

**Issue by eraps7** [fluttergems/fluttergems#473]
Thank you

- login_client_flutter
- https://pub.dev/packages/login_client_flutter
- Authentication Providers & UI

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @eraps7.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/login_client_flutter/
