### ISSUE TITLE
[ADD PACKAGE] flutter_sales_graph

### ISSUE THREAD

**Issue by AsherAyub80** [fluttergems/fluttergems#475]
# flutter_sales_graph

A Flutter package for displaying customizable bar charts for sales data.

## Features

- Displays a bar chart with customizable bar appearance and layout.
- Supports different time ranges (e.g., Last 7 Days, Last 30 Days, Last 12 Months).
- Customizable parameters for bar height, width, colors, and labels.

- flutter_sales_graph
-  **Pub.dev URL:** [flutter_sales_graph](https://pub.dev/packages/flutter_sales_graph)

## Screenshot

![Sales Graph Screenshot](https://raw.githubusercontent.com/AsherAyub80/flutter_sales_graph/main/assets/Screenshot%202024-09-10%20103435.png)

- Plots and Visualization
- A straightforward sales and data visualization package that allows users to easily add sales data, labels, set bar height and width, and customize bar colors.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @AsherAyub80.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_sales_graph/
