### ISSUE TITLE
[ADD PACKAGE] google_places_api_flutter

### ISSUE THREAD

**Issue by mhdaslam790** [fluttergems/fluttergems#476]
- Name of the package : google_places_api_flutter
- I pub URL : https://pub.dev/packages/google_places_api_flutter
- category: geolocation-maps and autocomplete
- Reason: the package compiles in two different category , It is auto complete textfield which provide list of location data based on google places and autoComplete api which user can select from the list .the selected data contains complete address and address latitude and longitude.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @mhdaslam790.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/google_places_api_flutter/
