### ISSUE TITLE
[ADD PACKAGE] better_commit

### ISSUE THREAD

**Issue by hosseinshaya** [fluttergems/fluttergems#477]
- better_commit 
- [pub.dev/packages/better_commit](https://pub.dev/packages/better_commit)
- Command Line (CLI) or Console
- Better Commit is a Dart package that uses AI to generate meaningful commit messages based on your code changes.
- This package write commit based on your staged changes (with git diff --staged output)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @hosseinshaya.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/better_commit/
