### ISSUE TITLE
[ADD PACKAGE] git_stamp

### ISSUE THREAD

**Issue by arononak** [fluttergems/fluttergems#478]
Advanced await-less information provider. From simple information such as build-branch to a screen with Flutter code with commits and change history.

- git_stamp
- https://pub.dev/packages/git_stamp 
- Developer Tools
- Releases new versions once a week

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @arononak.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
@arononak As the package is already added. Can you let me know exactly what info do you want to get refreshed? 
Description? Image? etc?

**Comment by arononak** [comment]
Refresh descriptions and images

**Comment by ashitaprasad** [comment]
sure @arononak .. Will close this issue once the info is updated.

**Comment by arononak** [comment]
My information?

**Comment by ashitaprasad** [comment]
The package information has now been updated on Flutter Gems 🎉
