### ISSUE TITLE
[ADD PACKAGE] multi_value_listenable

### ISSUE THREAD

**Issue by AlexHCJP** [fluttergems/fluttergems#481]
MultiValueListenableBuilder is a Flutter widget that listens to multiple ValueNotifiers and rebuilds its UI when any of them change. This is useful when you need to react to changes from multiple value notifiers and update the UI accordingly.

- multi_value_listenable
- [It's pub URL ](https://pub.dev/packages/multi_value_listenable)
- language-extension-enhancement
- It seems to me that this is ideal only for this category, but not dart, namely Flutter

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @AlexHCJP.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/multi_value_listenable/
