### ISSUE TITLE
[ADD PACKAGE] multi_bloc_builder

### ISSUE THREAD

**Issue by AlexHCJP** [fluttergems/fluttergems#482]
multi_bloc_builder is a Flutter package that provides widgets to manage multiple Bloc or Cubit state streams simultaneously. It simplifies the process of building UI or reacting to state changes when multiple state management objects are involved.

- multi_bloc_builder
- [It's pub URL ](https://pub.dev/packages/multi_bloc_builder)
- I don't know which category to put it in this package.This is a complementary package to an already prepared package.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @AlexHCJP.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/multi_bloc_builder/
