### ISSUE TITLE
[ADD PACKAGE] socket_io_adapter

### ISSUE THREAD

**Issue by AlexHCJP** [fluttergems/fluttergems#483]
This package is a wrapper for socket_io_client, simplifying connection to a socket.io server, event listening, and event emission to the server.

- socket_io_adapter
- [It's pub URL ](https://pub.dev/packages/socket_io_adapter)
- websocket
- Just this is packet working with websocket

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @AlexHCJP.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/socket_io_adapter/
