### ISSUE TITLE
[ADD PACKAGE] timelines_plus

### ISSUE THREAD

**Issue by ashworklord** [fluttergems/fluttergems#485]
Name of the package: timelines_plus
It's pub URL: https://pub.dev/packages/timelines_plus
The category/section where it should be added : Timeline
(Reason) Why is it best suited for this category: because this is timeline package

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ashworklord.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/timelines_plus/
