### ISSUE TITLE
[ADD PACKAGE] smart_countdown

### ISSUE THREAD

**Issue by hameezk** [fluttergems/fluttergems#486]
- smart_countdown 
- [It's pub URL ](https://pub.dev/packages/smart_countdown)
- [Stopwatch, Timer & Countdown](https://fluttergems.dev/stopwatch-timer-countdown/))
- (Reason) An easy-to-use, plug-n-play package to show customisable countdown timer with streams refreshing every second.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @hameezk .
Will close this issue once it is live on the website after review.
