### ISSUE TITLE
[ADD PACKAGE] phone_state_handler

### ISSUE THREAD

**Issue by ravianimize** [fluttergems/fluttergems#487]
- phone_state_handler
- [It's pub URL ](https://pub.dev/packages/phone_state_handler)
- Android/iOS Device Software and Hardware
- This plugin allows you to know quickly and easily if your Android or iOS device is receiving a call and to know the status of the call.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ravianimize.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/phone_state_handler/
