### ISSUE TITLE
[ADD PACKAGE] teeth_anatomy

### ISSUE THREAD

**Issue by mohammadprgrm20123** [fluttergems/fluttergems#488]
**teeth_anatomy shows the anatomy of the tooth and is a good package for use in medical software**

- teeth_anatomy 
- It's pub [URL](https://pub.dev/packages/teeth_anatomy)
- Shapes & Path
- teeth_anatomy shows the anatomy of the tooth and is a good package for use in medical software

**Comment by mohammadprgrm20123** [comment]
@ashitaprasad

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @mohammadprgrm20123.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/teeth_anatomy/
