### ISSUE TITLE
[ADD PACKAGE] pdf_gemini

### ISSUE THREAD

**Issue by JosephGakah** [fluttergems/fluttergems#489]
**Details of the package(s) you want to add**

- Name of the package: pdf_gemini
- It's pub URL: https://pub.dev/packages/pdf_gemini
- The category/section where it should be added: ChatGPT, LLM & Generative AI. pdf
- (Reason) Why is it best suited for this category: This package provides a simple way to interact, chat with pdf files using google gemini and managing uploaded files.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @JosephGakah.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/pdf_gemini/
