### ISSUE TITLE
[ADD PACKAGE] - archethic_lib_dart

### ISSUE THREAD

**Issue by redDwarf03** [fluttergems/fluttergems#49]
- archethic_lib_dart
- https://pub.dev/packages/archethic_lib_dart
- web3-crypto-blockchain
- This SDK is dedicated to communicate with the Layer 1 Archethic Blockchain

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @redDwarf03. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package archethic_lib_dart is now live.
https://fluttergems.dev/packages/archethic_lib_dart/
