### ISSUE TITLE
[ADD PACKAGE] sync_sphere

### ISSUE THREAD

**Issue by DarkNinja15** [fluttergems/fluttergems#490]
This Flutter package provides constant internet connectivity monitoring throughout the app, ensuring that the user's connection is always checked. It features real-time internet connectivity status updates and automatically displays a user-friendly screen when there is no internet connection. Additionally, the package offers customizable options for the appearance and behavior of the internet connectivity screen, allowing developers to tailor the experience to suit the app’s design and functionality.

- Name of the package: sync_sphere
- It's pub url: https://pub.dev/packages/sync_sphere
- Category: Networking, Sensors, Communication & APIs
- (Reason) It deals with internet connectivity, which is a key aspect of networking and communication within the app.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @DarkNinja15.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/sync_sphere/
