### ISSUE TITLE
[ADD PACKAGE] rail_navigator

### ISSUE THREAD

**Issue by TheNullSeeker** [fluttergems/fluttergems#491]
- rail_navigator
- https://pub.dev/packages/rail_navigator
- Drawer & Navigation Rail
- Package is a rail navigator thus falling directly satisfying all criteria for this category

![rail navigator](https://github.com/user-attachments/assets/56379510-a6f2-4be9-8e2e-c98849c7f558)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @TheNullSeeker.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/rail_navigator/
