### ISSUE TITLE
[ADD PACKAGE] y_player

### ISSUE THREAD

**Issue by ijashuzain** [fluttergems/fluttergems#492]
- YPlayer 
- https://pub.dev/packages/y_player
- Video
- YPlayer is a Flutter package that provides an easy-to-use YouTube video player widget without YouTube branding

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ijashuzain.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/y_player/
