### ISSUE TITLE
[ADD PACKAGE] the_responsive_builder

### ISSUE THREAD

**Issue by ijashuzain** [fluttergems/fluttergems#493]
- The Responsive Builder 
- https://pub.dev/packages/the_responsive_builder
- Responsive UI
- This flutter package provides a set of utilities to aid in building responsive Flutter applications.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ijashuzain.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/the_responsive_builder/
