### ISSUE TITLE
[ADD PACKAGE] pwa_info

### ISSUE THREAD

**Issue by edris-mazhari** [fluttergems/fluttergems#494]
- pwa_info
- https://pub.dev/packages/pwa_info/
- WebView
- get user os and all info in pwa

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @edris-mazhari.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/pwa_info/
