### ISSUE TITLE
[ADD PACKAGE] flutter_saver

### ISSUE THREAD

**Issue by SwanFlutter** [fluttergems/fluttergems#495]
This Flutter package provides a powerful and versatile solution for saving camera images and downloadable links across all platforms. With support for various formats, it allows developers to store images and files efficiently in device memory.

Name of the package: flutter_saver
Pub URL: [Flutter Saver on pub.dev](https://pub.dev/packages/flutter_saver)
Category: You can suggest placing it in categories like "Top Flutter File, Folder and Path Utilities packages" based on its functionality.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SwanFlutter.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_saver/
