### ISSUE TITLE
external_path_ios_mac

### ISSUE THREAD

**Issue by SwanFlutter** [fluttergems/fluttergems#496]
A Flutter package for restoring directory paths on iOS and macOS devices, ensuring file access and management across platforms.

- Name of the package : external_path_ios_mac
- Pub URL: [External_path_ios_mac on pub.dev](https://pub.dev/packages/external_path_ios_mac)
- Category: You can suggest placing it in categories like "Top Flutter File, Folder and Path Utilities packages" based on its functionality.

![photo_2024-09-12_23-49-20](https://github.com/user-attachments/assets/a095bca1-2fe0-45e5-b489-04e62883d610)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SwanFlutter.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/external_path_ios_mac/
