### ISSUE TITLE
[ADD PACKAGE] Progress Bar Countdown

### ISSUE THREAD

**Issue by matloughnane** [fluttergems/fluttergems#497]
# Package Details

- Name: Progress Bar Countdown
- It's pub URL: [https://pub.dev/packages/progress_bar_countdown](https://pub.dev/packages/progress_bar_countdown)
- The category/section where it should be added: "Flutter Stopwatch, Timer and Countdown"
- Reason: It's a simple countdown timer that can be formatted easily, fills the width of the screen and counts down.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @matloughnane.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/progress_bar_countdown/
