### ISSUE TITLE
[ADD PACKAGE] cardoteka

### ISSUE THREAD

**Issue by PackRuble** [fluttergems/fluttergems#498]
**Cardoteka** - The best type-safe wrapper over SharedPreferences. 
Why so? 
-> strongly typed cards for access to storage 
-> use only get|set 
-> can work with nullable values 
-> callback based updates

- (name) cardoteka
- (pub link) https://pub.dev/packages/cardoteka
- (Section) Persistent NoSQL Database (`nosql-database`)
- (Reason) Is a wrapper over the handy `shared_preferences` with additional features

Thank you!

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @PackRuble.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/cardoteka/
