### ISSUE TITLE
[ADD PACKAGE] - archethic_wallet_client

### ISSUE THREAD

**Issue by redDwarf03** [fluttergems/fluttergems#50]
- archethic_wallet_client 
- https://pub.dev/packages/archethic_wallet_client
- web3-crypto-blockchain
- This lib allows users to create Flutter Decentralized Apps (DApps) on the Layer 1 Archethic Blockchain Ecosystem

**Comment by ashitaprasad** [comment]
Package archethic_wallet_client is now live.
https://fluttergems.dev/packages/archethic_wallet_client/
