### ISSUE TITLE
[ADD PACKAGE] fform_flutter

### ISSUE THREAD

**Issue by AlexHCJP** [fluttergems/fluttergems#500]
- fform_flutter
- It's [pub URL ](https://pub.dev/packages/fform_flutter)
- Forms
- You have fform on your site, but the fform_flutter package, which is implemented into flutter and allows you to use the layout, is not
<img width="1333" alt="image" src="https://github.com/user-attachments/assets/e1539c7c-effb-4ba5-948b-02c527e120a4">

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @AlexHCJP.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/fform_flutter/
