### ISSUE TITLE
[ADD PACKAGE] maplibre

### ISSUE THREAD

**Issue by josxha** [fluttergems/fluttergems#501]
MapLibre is a permissive and open source solution for the MVT (Mapbox Vector Tile) standard. By binding to native SDKs the package accomplishes performant rendering while supporting a lot of complex functionality.

- Name of the package: **maplibre**
- It's pub URL: **https://pub.dev/packages/maplibre**
- The category/section where it should be added: **Geolocation & Maps**
- (Reason) Why is it best suited for this category: **The package adds a map.**

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @josxha.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/maplibre/
