### ISSUE TITLE
[ADD PACKAGE] video_preview_thumbnails 

### ISSUE THREAD

**Issue by mbfakourii** [fluttergems/fluttergems#502]
Generate Video preview thumbnails using VTT files for enhanced video navigation and user experience

**Details of the package(s) you want to add**

- video_preview_thumbnails  
- https://pub.dev/packages/video_preview_thumbnails

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @mbfakourii.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/video_preview_thumbnails/
