### ISSUE TITLE
[ADD PACKAGE] super_profile_picture

### ISSUE THREAD

**Issue by SM-SHIFAT** [fluttergems/fluttergems#506]
**A customizable Flutter widget for displaying profile pictures, supporting both image and text options. It will show label text in case the image is not provided or fails to load. You can use any image provider, such as NetworkImage, AssetImage, and more, to display the image.**

- Super Profile Picture
- https://pub.dev/packages/super_profile_picture
- Should added in **Avatar, Profile Picture & Chat Heads** section
- Its a similar package that already this category contains.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @SM-SHIFAT.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/super_profile_picture/
