### ISSUE TITLE
[ADD PACKAGE] custom_flutter_toast

### ISSUE THREAD

**Issue by aipxperts-developer** [fluttergems/fluttergems#507]
Details of the package(s) you want to add

Name of the package: custom_flutter_toast

It's pub URL: https://pub.dev/packages/custom_flutter_toast

The category/section where it should be added: UI / Notifications

(Reason) Why is it best suited for this category: The custom_flutter_toast package offers a customizable and intuitive way to display temporary notifications or messages to users. A key feature of this package is its flexibility, allowing users to display images (such as the app logo) or any other custom image inside the toast notification, enhancing visual feedback. It’s especially useful for branding, error messages, or status updates, making it a great fit for the UI / Notifications section.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @aipxperts-developer.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/custom_flutter_toast/
