### ISSUE TITLE
[ADD PACKAGE] jh_services

### ISSUE THREAD

**Issue by ALI-tech-tech** [fluttergems/fluttergems#508]
Details of the package(s) you want to add

Name of the package: jh_services 
It's pub URL: https://pub.dev/packages/jh_services
The category/section where it should be added: Helpers and Utilities /Networking, Sensors, Communication & APIs
(Reason) Why is it best suited for this category: A lightweight service package for Flutter to handle network requests, local storage, and connectivity seamlessly with best practices.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/jh_services/
