### ISSUE TITLE
card_animation_hover

### ISSUE THREAD

**Issue by SwanFlutter** [fluttergems/fluttergems#509]
## card_animation_hover

This class is a StatefulWidget that displays a card with a hover animation effect.

[![Pub Version](https://img.shields.io/pub/v/card_animation_hover)](https://pub.dev/packages/card_animation_hover)

[View it on pub.dev](https://pub.dev/packages/card_animation_hover)

### Category:
It's commonly categorized under **Animation**, **User Interface**, or **Widget** libraries on pub.dev.

![card_animation](https://github.com/user-attachments/assets/d7af5666-8472-4cfb-a8f3-d577f92cfbe1)

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/card_animation_hover/

**Comment by SwanFlutter** [comment]
Thanks

‫‪Ashita Prasad‬‏ ***@***.***‬‏> در تاریخ دوشنبه ۲۱ اکتبر
۲۰۲۴ ساعت ۵:۰۷ نوشت:‬
