### ISSUE TITLE
[ADD PACKAGE] `mimir`

### ISSUE THREAD

**Issue by GregoryConrad** [fluttergems/fluttergems#51]
**Details of the package(s) you want to add**
Extremely powerful, reactive NoSQL database with typo-tolerant full-text search and declarative queries.

Info
- `mimir`
- https://pub.dev/packages/mimir
- The category/section where it should be added (Check fluttergems.dev for the categories)
  - https://fluttergems.dev/nosql-database/
- (Reason) Why is it best suited for this category
  - It's a NoSQL database

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @GregoryConrad. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package mimir is now live.
https://fluttergems.dev/packages/mimir/
