### ISSUE TITLE
[ADD PACKAGE] sphinx_verify

### ISSUE THREAD

**Issue by moesaid** [fluttergems/fluttergems#511]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package 
  - SphinxVerify
- It's pub URL 
  - https://pub.dev/packages/sphinx_verify
- The category/section where it should be added (Check fluttergems.dev for the categories)
  - machine-learning
- (Reason) Why is it best suited for this category
  - the package is AI & ML based

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @moesaid.
Will close this issue once it is live on the website after review.
