### ISSUE TITLE
[ADD PACKAGE] flutter_dino

### ISSUE THREAD

**Issue by YudizAndroidKishan** [fluttergems/fluttergems#513]
**Details of the package(s) you want to add**

- Name of the package 
  - flutter_dino
- It's pub URL
  - https://pub.dev/packages/flutter_dino 
- The category/section where it should be added (Check fluttergems.dev for the categories)
  - Network Connectivity Status
- (Reason) Why is it best suited for this category
  - The package is inspired from no internet game of chrome

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @YudizAndroidKishan.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
This package is available on Flutter Gems
https://fluttergems.dev/packages/flutter_dino
