### ISSUE TITLE
[ADD PACKAGE] gdpr_dialog_flutter

### ISSUE THREAD

**Issue by KhilanVitthani** [fluttergems/fluttergems#514]
_Note: To add multiple packages, open a separate issue for each package._

**Library for use GDPR dialog from user for personalized ads and non personalized ads.*

- gdpr_dialog_flutter
- [It's pub URL ](https://pub.dev/packages/gdpr_dialog_flutter)
- Ad Serving
- My package can run on the latest version of Gradle v8 and the other package [gdpr_dialog](https://pub.dev/packages/gdpr_dialog) has issue to run in latest version of Gradle

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @KhilanVitthani.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
This package is available on Flutter Gems
https://fluttergems.dev/packages/gdpr_dialog_flutter/
