### ISSUE TITLE
[ADD PACKAGE] permission_policy

### ISSUE THREAD

**Issue by eraps7** [fluttergems/fluttergems#515]
**Details of the package(s) you want to add**

- permission_policy
- https://pub.dev/packages/permission_policy
- no sure but maybe Authentication Providers & UI or Cryptography, Security & Permissions
- the package casbin which is a similar  package is in both of those sections

Thank you for maintaining this resource!:)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @eraps7.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
This package is available on Flutter Gems
https://fluttergems.dev/packages/permission_policy/
