### ISSUE TITLE
[ADD PACKAGE] simple_date_picker

### ISSUE THREAD

**Issue by hashtag-mood** [fluttergems/fluttergems#516]
- Name of the package : simple_date_picker
- It's pub URL : https://pub.dev/packages/simple_date_picker
- The category/section where it should be added (Check fluttergems.dev for the categories) : Date & Time Picker
- (Reason) Why is it best suited for this category : Provides customizable THREE types of Cupertino styled date pickers

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @hashtag-mood.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
This package is available on Flutter Gems
https://fluttergems.dev/packages/simple_date_picker/
