### ISSUE TITLE
[ADD PACKAGE] wagmi_flutter_web

### ISSUE THREAD

**Issue by redDwarf03** [fluttergems/fluttergems#517]
- wagmi_flutter_web 
- https://pub.dev/packages/wagmi_flutter_web
- web3-crypto-blockchain
- https://medium.com/archethic/an-innovative-sdk-for-flutter-web-introducing-wagmi-flutter-web-by-archethic-39789be2b3dd

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @redDwarf03.
Will close this issue once it is live on the website after review.
