### ISSUE TITLE
[ADD_PACKAGE]material_charts

### ISSUE THREAD

**Issue by vishnudas-bluefox** [fluttergems/fluttergems#518]
Material Charts is a versatile Flutter package that provides customizable charting components for a wide range of use cases. The package supports Line Charts, Pie Charts, Bar Charts, CandleStick Charts, and Gantt Charts, offering rich customization options, smooth animations, and real-time data updates. It’s especially useful for applications requiring diverse chart types and a high degree of customization.

- material_charts
- [It's pub URL ](https://pub.dev/packages/material_charts)
- Category: plots-visualization
- Material Charts is ideally suited for the "Plots-Visualization" category due to its comprehensive chart options and adaptability.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @vishnudas-bluefox.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
This package is available on Flutter Gems
https://fluttergems.dev/packages/material_charts/
