### ISSUE TITLE
[ADD PACKAGE] verification_code_field

### ISSUE THREAD

**Issue by enescerrahoglu** [fluttergems/fluttergems#520]
_Note: To add multiple packages, open a separate issue for each package._

**This package provides an input field that allows you to enter a 4, 5 or 6 digit verification code in your applications.**

- verification_code_field
- https://pub.dev/packages/verification_code_field
- pin-password-field
- Customizable digit count, cursor and focus management, styling options, event listener, built-in input formatting and more.

![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-11 at 11 35 10](https://github.com/user-attachments/assets/e1ef7807-ff1b-42c3-bff8-8d37369de2be)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @enescerrahoglu
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/verification_code_field/
