### ISSUE TITLE
[ADD PACKAGE] datetime_loop

### ISSUE THREAD

**Issue by gnassro** [fluttergems/fluttergems#521]
- datetime_loop
- [It's pub URL](https://pub.dev/packages/datetime_loop) 
- Date & Time Utilities
- There is currently no package that offers a builder to rebuild on system date and time changes

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @gnassro.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/datetime_loop/
