### ISSUE TITLE
[ADD PACKAGE] flutter_upi_india

### ISSUE THREAD

**Issue by princeflutterdev** [fluttergems/fluttergems#522]
- flutter_upi_india
- [Package URL](https://pub.dev/packages/flutter_upi_india)
- Payment API/SDK
- UPI standards and systems are evolving, and accordingly behaviour and functionality of the UPI payment apps are changing. See [Apps](https://github.com/reeteshranjan/flutter_upi_india/blob/master/APPS.md) for details of current functional status of various applications that were verified by us.

Support for merchant and non-merchant payments 
The [UPI Deep Linking And Proximity Integration Specification](https://github.com/reeteshranjan/upi_pay/files/6338127/UPI.Linking.Specs_ver.1.6.pdf) is designed for merchant payments. It includes parameters in payment request that can be provided only if the payment was made to a merchant e.g. the merchant code (mc parameter), and a signature (crypto-hash) of the request created using merchant's private key.

However; various applications have been accepting requests without merchant details and signature and successfully processing payments. Possibly, the dilution could be due to the reason that such a package can only automate filling a payment form, and unless the user verifies the details in the form and enters the UPI pin, no damaging payments can be really made.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @princeflutterdev.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/flutter_upi_india/
