### ISSUE TITLE
[ADD PACKAGE] canopas_country_picker

### ISSUE THREAD

**Issue by cp-pratik-k** [fluttergems/fluttergems#523]
- canopas_country_picker
- [pub.dev URL](https://pub.dev/packages/canopas_country_picker)
- Country Picker & Country Code Picker
- A Simple, Customizable Flutter Country picker for picking a Country or Dialing code with Search functionality.

**Comment by ashitaprasad** [comment]
The package is already available on Flutter Gems
https://fluttergems.dev/packages/canopas_country_picker/
