### ISSUE TITLE
[ADD PACKAGE] calendar_viewer

### ISSUE THREAD

**Issue by mu7mmd** [fluttergems/fluttergems#525]
- Name of the package: calendar_viewer
- It's pub URL: https://pub.dev/packages/calendar_viewer
- The category/section where it should be added (Check fluttergems.dev for the categories): Calendar
- (Reason) Why is it best suited for this category: It is a calendar viewer package

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @mu7mmd.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/calendar_viewer/
