### ISSUE TITLE
[ADD PACKAGE] my_own_mvvm_with_dependency_injection_blackjack_and_hookers

### ISSUE THREAD

**Issue by JCKodel** [fluttergems/fluttergems#526]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Name of the package: my_own_mvvm_with_dependency_injection_blackjack_and_hookers
- It's pub URL: https://pub.dev/packages/my_own_mvvm_with_dependency_injection_blackjack_and_hookers
- The category/section where it should be added (Check fluttergems.dev for the categories): state-management
- (Reason) Why is it best suited for this category: It's a (real) dependency injector with MVVM tooling for testable projects without depending (too much) on a framework and with almost no learning curve.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @JCKodel.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/my_own_mvvm_with_dependency_injection_blackjack_and_hookers/
