### ISSUE TITLE
[ADD PACKAGE] carousel_nerdzlab

### ISSUE THREAD

**Issue by MaxymRadchuk** [fluttergems/fluttergems#527]
- carousel_nerdzlab
- https://pub.dev/packages/carousel_nerdzlab
- Carousel or Cover Flow
- There is currently no package that offers the specific behavior of PageView with `padEnds: false`.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MaxymRadchuk.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/carousel_nerdzlab/
