### ISSUE TITLE
[ADD PACKAGE] mvvm_cli_nerdzlab

### ISSUE THREAD

**Issue by MaxymRadchuk** [fluttergems/fluttergems#528]
- mvvm_cli_nerdzlab
- https://pub.dev/packages/mvvm_cli_nerdzlab
- Command Line (CLI) or Console
- The package is command-line utility designed to streamline the creation of MVVM projects.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MaxymRadchuk.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/mvvm_cli_nerdzlab/
