### ISSUE TITLE
[ADD PACKAGE] mvvm_linter

### ISSUE THREAD

**Issue by MaxymRadchuk** [fluttergems/fluttergems#529]
- mvvm_linter
- https://pub.dev/packages/mvvm_linter
- Linter
- Linter designed to enforce best practices and coding standards in MVVM.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @MaxymRadchuk.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/mvvm_linter/
