### ISSUE TITLE
[ADD PACKAGE] text_link

### ISSUE THREAD

**Issue by safeenkurd** [fluttergems/fluttergems#53]
**The LinkText package is a powerful Flutter utility designed to transform URLs embedded in text strings into tappable inline links, bringing in enhanced interactivity to your text content. Alongside this, it also offers a unique 'Read More/Less' feature for handling long texts.**

- text_link
-[ It's pub URL ](https://pub.dev/packages/text_link)
- Social Media

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @safeenkurd. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package text_link is now live.
https://fluttergems.dev/packages/text_link/
