### ISSUE TITLE
[ADD PACKAGE] extensions_pro

### ISSUE THREAD

**Issue by sanjaysharmajw** [fluttergems/fluttergems#530]
- Name of the package: extensions_pro
- https://pub.dev/packages/extensions_pro
- Categories/Sections: Dart Extension & Enhancement
- Developer can integrate many features in one line. For example: Date picker can be integrated in one line.
![extension_pro_banner](https://github.com/user-attachments/assets/d1ea384d-0357-4245-b8b7-dff1b581796c)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @sanjaysharmajw.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/extensions_pro/
