### ISSUE TITLE
[ADD PACKAGE] QuickText 

### ISSUE THREAD

**Issue by Anees7757** [fluttergems/fluttergems#531]
- quick_text
- https://pub.dev/packages/quick_text
- Text Utilities, Text Styling, Text Manipulation
- **QuickText** is a simple and efficient Flutter package for text formatting using markdown-like syntax. It helps developers apply styles such as bold, italic, underline, strikethrough, color and link directly within strings. This simplicity and ease of use make it a great fit for the Text Styling category as it simplifies text styling without requiring complex code.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Anees7757.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/quick_text/
