### ISSUE TITLE
[ADD PACKAGE] expansion_tile_list

### ISSUE THREAD

**Issue by seun-ogunjimi** [fluttergems/fluttergems#532]
**The `expansion_tile_list` package provides a highly customisable list of expansion tiles, offering extensive options for appearance, animations, and control over expansion behaviour, while also simplifying the implementation of common features.*

- expansion_tile_list
- [It's pub URL ](https://pub.dev/packages/expansion_tile_list)
- card-expansion-tile
- The ExpansionTileList widget is a container for the ExpansionTile widget that allows you to create a list of tiles.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/expansion_tile_list/
