### ISSUE TITLE
[ADD PACKAGE] smart_stepper

### ISSUE THREAD

**Issue by mofizur11** [fluttergems/fluttergems#533]
This package help you to make nice custom stepper.

[smart_stepper]
[- It's pub URL ](https://pub.dev/packages/smart_stepper)
Stepper
This is a stepper

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @mofizur11.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/smart_stepper/
