### ISSUE TITLE
[ADD PACKAGE] libanime

### ISSUE THREAD

**Issue by nyakokitsu** [fluttergems/fluttergems#534]
+ libanime
+ https://pub.dev/packages/libanime
+ Networking, Sensors, Communication & APIs
+ This is a wrapper/parser for anime players

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @mofizur11.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
The package is now available on Flutter Gems 🎉
https://fluttergems.dev/packages/libanime/
