### ISSUE TITLE
[ADD PACKAGE] - flutter_scalable_ocr

### ISSUE THREAD

**Issue by vbalagovic** [fluttergems/fluttergems#55]
- flutter_scalable_ocr
- [It's pub URL ](https://pub.dev/packages/flutter_scalable_ocr)
- document-scanner/machine-learning
- This package is a wrapper around ML kit text recognition, it allows you to use a partial part of the camera viewport easily and gives multiple options for callback data

**Comment by ashitaprasad** [comment]
Package flutter_scalable_ocr is now live.
https://fluttergems.dev/packages/flutter_scalable_ocr/
