### ISSUE TITLE
[ADD PACKAGE] - flutter_simple_multiselect

### ISSUE THREAD

**Issue by vbalagovic** [fluttergems/fluttergems#56]
- flutter_simple_multiselect 
- [It's pub URL ](https://pub.dev/packages/flutter_simple_multiselect)
- dropdown
- Fetch and search async data directly from the server or from static data. Use it for multi-select and single, and use it somehow naturally (inspired by vue-multiselect)

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @vbalagovic. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package flutter_simple_multiselect is now live.
https://fluttergems.dev/packages/flutter_simple_multiselect/
