### ISSUE TITLE
[ADD PACKAGE] flexiges

### ISSUE THREAD

**Issue by farahfarah1** [fluttergems/fluttergems#57]
**Flexi is a Flutter package that provides a flexible widget for zooming, panning, and rotating child widgets.**

- flexiges
- [It's pub URL](https://pub.dev/packages/flexiges) 
- [Canvas, Visualization & Animation](https://fluttergems.dev/sharing-intent/#)
- This comprehensive toolkit is specifically designed to provide developers with a whole new level of interaction with widgets.      Whether you want to drag, zoom, rotate, or scale, flexiges has got you covered

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @farahfarah1. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package flexiges is now live.
https://fluttergems.dev/packages/flexiges/
