### ISSUE TITLE
[ADD PACKAGE] name_plus

### ISSUE THREAD

**Issue by thitlwincoder** [fluttergems/fluttergems#6]
Automatically increment File & Directory name and create.

- name_plus 
- https://pub.dev/packages/name_plus
- file-folder-path-util

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @thitlwincoder . This issue will be closed once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Hi @thitlwincoder 
name_plus is now available on Flutter Gems.
Link - https://fluttergems.dev/file-folder-path-util/
