### ISSUE TITLE
[ADD PACKAGE] easy_date_timeline

### ISSUE THREAD

**Issue by FadyFayezYounan** [fluttergems/fluttergems#64]
- easy_date_timeline
- [It's pub URL ](https://pub.dev/packages/easy_date_timeline)
- Top Flutter Calendar packages
- Dynamic Text Color : The "easy_date_timeline" package automatically adjusts the text color of the active day based on the active color. If the active color is a dark color, the text color will be light, and if the active color is a light color, the text color will be dark. This ensures that the text is always easy to read and contrasts well with the background color.
Customizable Item Builder : The "easy_date_timeline" package provides an item builder that allows for full customization of the timeline items. With the item builder, developers can customize the appearance and behavior of each date item in the timeline, including the text, background color,etc..
Locale Support : The "easy_date_timeline" package supports locale, allowing developers to display the timeline in different languages and formats based on the user's device settings. This feature ensures that the package can be used in a variety of international contexts and provides a seamless user experience for users around the world.

**Comment by ashitaprasad** [comment]
Package easy_date_timeline is now live.
https://fluttergems.dev/packages/easy_date_timeline/
