### ISSUE TITLE
[ADD PACKAGE] floating_snackbar

### ISSUE THREAD

**Issue by muhd-ameen** [fluttergems/fluttergems#66]
_Note: To add multiple packages, open a separate issue for each package._

**Can Provide a custom floating snackbar for a minimalistic toast. Parse the required 'message' and 'context' to the FloatingSnackBar widget for using your custom toast.**

- floating_snackbar
- https://pub.dev/packages/floating_snackbar
- notification-toast
- A package that provides a custom floating snackbar for your project.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @muhd-ameen. Will close this issue once it is live on the website after review.

**Comment by muhd-ameen** [comment]
whroom whroom 🎮🚀🏎️

**Comment by ashitaprasad** [comment]
Package floating_snackbar is now live.
https://fluttergems.dev/packages/floating_snackbar/
