### ISSUE TITLE
[ADD PACKAGE] gal

### ISSUE THREAD

**Issue by natsuk4ze** [fluttergems/fluttergems#68]
## Gal is very easy to use Flutter Plugin for handle native gallery apps.

- Name of the package : gal
- It's pub URL : https://pub.dev/packages/gal
- The category/section where it should be added : Edit, Save and Compress Multimedia packages
- gal has features, saving multi media.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @natsuk4ze. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package gal is now live.
https://fluttergems.dev/packages/gal/
