### ISSUE TITLE
[ADD PACKAGE] wtf_sliding_sheet

### ISSUE THREAD

**Issue by ivan-wtf** [fluttergems/fluttergems#70]
- Name of the package: wtf_sliding_sheet

- Pub URL: https://pub.dev/packages/wtf_sliding_sheet

- The category/section where it should be added: Bottom Panels & Bottomsheets

- Reason: The main goal of the package is to provide a custom bottomsheet

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ivan-wtf. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package wtf_sliding_sheet is now live.
https://fluttergems.dev/packages/wtf_sliding_sheet/
