### ISSUE TITLE
[ADD PACKAGE] suggest_a_feature

### ISSUE THREAD

**Issue by ivan-wtf** [fluttergems/fluttergems#71]
- Name of the package: suggest_a_feature

- Pub URL: https://pub.dev/packages/suggest_a_feature

- The category/section where it should be added: Feedback

- Reason: This Flutter package contains ready views (screens) where users can share their suggestions about the application in real time, discuss them with others, and vote for each other's suggestions.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ivan-wtf. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package suggest_a_feature is now live.
https://fluttergems.dev/packages/suggest_a_feature/
