### ISSUE TITLE
[ADD PACKAGE] wtf_rotary_dial

### ISSUE THREAD

**Issue by ivan-wtf** [fluttergems/fluttergems#72]
- Name of the package: wtf_rotary_dial

- Pub URL: https://pub.dev/packages/wtf_rotary_dial

- The category/section where it should be added: Spin Box

- Reason: The package provides a Widget that allows you to dial numbers by rotating the dial

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ivan-wtf. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package wtf_rotary_dial is now live.
https://fluttergems.dev/packages/wtf_rotary_dial/
