### ISSUE TITLE
[ADD PACKAGE] material_table_view

### ISSUE THREAD

**Issue by NikolayNIK** [fluttergems/fluttergems#73]
- Name of the package: `material_table_view`
- It's pub URL: https://pub.dev/packages/material_table_view
- The category/section where it should be added (Check fluttergems.dev for the categories): `Table`
- (Reason) Why is it best suited for this category: It provides a widget displaying widgets in a table form

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @NikolayNIK. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package material_table_view is now live.
https://fluttergems.dev/packages/material_table_view/
