### ISSUE TITLE
[ADD PACKAGE] animated_rating_bar

### ISSUE THREAD

**Issue by codersangam** [fluttergems/fluttergems#80]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Animated Rating Bar
- https://pub.dev/packages/animated_rating_bar
- Feedback
- Allow users to feel the touch of giving feedback through animation.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @codersangam. Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package animated_rating_bar is now live.
https://fluttergems.dev/packages/animated_rating_bar/
