### ISSUE TITLE
[ADD PACKAGE] sugar

### ISSUE THREAD

**Issue by Pante** [fluttergems/fluttergems#81]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Sugar
- https://pub.dev/packages/sugar
- DateTime/Timezone utilities
- I believe it offers several improvements over the existing timezone packages

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Pante 
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package sugar is now live.
https://fluttergems.dev/packages/sugar/
