### ISSUE TITLE
[ADD PACKAGE] media_collection_previewer

### ISSUE THREAD

**Issue by saedkhaled** [fluttergems/fluttergems#82]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- media_collection_previewer
- https://pub.dev/packages/media_collection_previewer
- Multimedia
- Because it is a media collection previewer widget which can be used to preview image, audio, and video files.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @saedkhaled.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package media_collection_previewer is now live.
https://fluttergems.dev/packages/media_collection_previewer/
