### ISSUE TITLE
[ADD PACKAGE] pulse_x

### ISSUE THREAD

**Issue by YeLwinOo-Steve** [fluttergems/fluttergems#83]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Pulse_X state management
- https://pub.dev/packages/pulse_x
- Architecture & Infrastructure
- Pulse_X is a lightweight state management solution for small projects which includes state management, dependency injection, routing and it will aid you in learning state management logic

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @YeLwinOo-Steve 
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package pulse_x is now live.
https://fluttergems.dev/packages/pulse_x/
