### ISSUE TITLE
[ADD PACKAGE] pretty_animated_buttons

### ISSUE THREAD

**Issue by YeLwinOo-Steve** [fluttergems/fluttergems#84]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- Pretty Animated Buttons 
- https://pub.dev/packages/pretty_animated_buttons
- User Input, Form & Settings
- Pretty animated buttons package is a collection of 12 beautifully animated buttons. More animated buttons are coming soon

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @YeLwinOo-Steve.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package pretty_animated_buttons is now live.
https://fluttergems.dev/packages/pretty_animated_buttons/
