### ISSUE TITLE
[BUG] Website doesn't work correctly

### ISSUE THREAD

**Issue by mohamedsalah414** [fluttergems/fluttergems#85]
**Describe the bug/problem**
website doesn't work correctly 

**Screenshot/image(s) to help explain the bug/problem (if applicable)**
![image](https://github.com/fluttergems/fluttergems/assets/36240402/96126374-8785-45d8-983c-39e202156b3e)

**Desktop details where you encountered the problem/bug (if applicable):**
 - OS: [windows]
 - Browser [chrome]

**Comment by ashitaprasad** [comment]
Hi @mohamedsalah414,
Can you check once again and let me know if there is still any issue.

**Comment by mohamedsalah414** [comment]
Yes 
![image](https://github.com/fluttergems/fluttergems/assets/36240402/5d0ca6bd-45a8-48c2-bf6a-32cb265637f1)

**Comment by ashitaprasad** [comment]
Can you please check if the same thing happens when you open the site using mobile device.
Thanks!

**Comment by mohamedsalah414** [comment]
**It works fine after opening VPN [_USA_]**

![image](https://github.com/fluttergems/fluttergems/assets/36240402/7b801987-9e5f-4a51-96b2-5c1f4d45ece1)

**Comment by ashitaprasad** [comment]
Thanks for confirming @mohamedsalah414 👍
