### ISSUE TITLE
[ADD PACKAGE] ultimate_bottom_navbar

### ISSUE THREAD

**Issue by saginbajracharya** [fluttergems/fluttergems#87]
Note: To add multiple packages, open a separate issue for each package.

Details of the package(s) you want to add

- ultimate_bottom_navbar
- [It's pub URL ](https://pub.dev/packages/ultimate_bottom_navbar)
- Bottom Navigation Bar
- Ultimate Bottom Navigation Bar is a bottom navigation bar widget package with various customization

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @saginbajracharya.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package ultimate_bottom_navbar is now live.
https://fluttergems.dev/packages/ultimate_bottom_navbar/

**Comment by saginbajracharya** [comment]
Thank you so much
