### ISSUE TITLE
[ADD PACKAGE] animated_3d_card

### ISSUE THREAD

**Issue by Obada2020** [fluttergems/fluttergems#89]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- animated_3d_card 
- https://pub.dev/packages/animated_3d_card
- animations
- cus it animation packeg

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Obada2020 
Will close this issue once it is live on the website after review.

**Comment by Obada2020** [comment]
I very much appreciate the effort ,
but have question How long does it take to publish the package in fluttergems ?

**Comment by ashitaprasad** [comment]
Package animated_3d_card is now live.
https://fluttergems.dev/packages/animated_3d_card/
