### ISSUE TITLE
[ADD PACKAGE] ordinal_formatter

### ISSUE THREAD

**Issue by ZsomborRajki** [fluttergems/fluttergems#9]
Tiny package to convert numbers into localised ordinal string format.
example: 2 -> 2nd
Supports all locale built in the given native platform. And uses native code under the hood.

- ordinal_formatter
- https://pub.dev/packages/ordinal_formatter
- Text, Icons & Keyboard/Parsing & Other Text Utilities

**Comment by ashitaprasad** [comment]
Hi @ZsomborRajki 
ordinal_formatter is now available on Flutter Gems.
Link - https://fluttergems.dev/parsing-other-utilities/

Cheers 🎉
