### ISSUE TITLE
[ADD PACKAGE] gradiant_button_animations

### ISSUE THREAD

**Issue by Obada2020** [fluttergems/fluttergems#90]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- gradiant_button_animations 
- https://pub.dev/packages/gradiant_button_animations
- animations
- cus it animated package

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @Obada2020 
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package gradiant_button_animations is now live.
https://fluttergems.dev/packages/gradiant_button_animations/
