### ISSUE TITLE
[ADD PACKAGE] flutter_img

### ISSUE THREAD

**Issue by ishafiul** [fluttergems/fluttergems#91]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- flutter_img
- [It's pub URL ](https://pub.dev/packages/flutter_img)
- Image
- flutter_img is a single widget that can display asset images and network images. for network images, it can handle caching and it supports svg image also.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ishafiul.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package flutter_img is now live.
https://fluttergems.dev/packages/flutter_img/
