### ISSUE TITLE
[ADD PACKAGE] janus_client

### ISSUE THREAD

**Issue by shivanshtalwar** [fluttergems/fluttergems#93]
_Note: To add multiple packages, open a separate issue for each package._

**Details of the package(s) you want to add**

- janus_client
- https://pub.dev/packages/janus_client
- https://fluttergems.dev/real-time-communication/
- It is a feature rich webrtc client for open source janus webrtc server that allows developer to implement SFU(videoroom), audio room, streaming, sip calls and what not can be considered as swiss knife for open source webrtc solutions

**Comment by ashitaprasad** [comment]
https://fluttergems.dev/packages/janus_client/
