### ISSUE TITLE
[ADD PACKAGE] reporter

### ISSUE THREAD

**Issue by ahmednfwela** [fluttergems/fluttergems#95]
**Details of the package(s) you want to add**

- Name of the package: `reporter`
- It's pub URL: https://pub.dev/packages/reporter
- The category/section: CSV, Excel, ODS and Sheets
- Reason: it helps generate tabular reports in any format

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @ahmednfwela.
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package reporter is now live.
https://fluttergems.dev/packages/reporter/
