### ISSUE TITLE
[ADD PACKAGE] passkeys

### ISSUE THREAD

**Issue by vincentdelitz** [fluttergems/fluttergems#96]
**Details of the package(s) you want to add**

- passkeys
- https://pub.dev/packages/passkeys
- Biometric & Local Authentication
- The passkeys package allows Flutter developers to easily add passkey authentication (based on FIDO2 / WebAuthn) to any Flutter app. As passkeys leverage facial recognition, fingerprint scan or PIN pattern during the authentication ceremony, I think "BIometric & Local authentication" fits best

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @vincentdelitz .
Will close this issue once it is live on the website after review.

**Comment by ashitaprasad** [comment]
Package passkeys is now live.
https://fluttergems.dev/packages/passkeys/
