### ISSUE TITLE
[ADD PACKAGE] WiFlutter

### ISSUE THREAD

**Issue by weitsai** [fluttergems/fluttergems#98]
- WiFlutter
- https://pub.dev/packages/wiflutter
- WiFi, IoT
- Control Wi-Fi in Flutter like a boss.

**Comment by ashitaprasad** [comment]
Thanks for submitting the package @weitsai .
Will close this issue once it is live on the website after review.

**Comment by weitsai** [comment]
@ashitaprasad Thanks

**Comment by ashitaprasad** [comment]
Package WiFlutter is now live.
https://fluttergems.dev/packages/wiflutter/
